# DISCLAMER: This file is generated by AI because I don't know how to do argparse properly.
import argparse
import logging
import os
import sys

from iSpy.boot import boot


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ispy",
        description="iSpy control surface (trivial wrappers around the boot sequence).",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # -s/--service and -w/--wait come from boot.add_boot_arguments() so they
    # can never drift from `python -m iSpy.boot.boot`.
    setup = subparsers.add_parser(
        "setup",
        help="Fresh first-time install (equivalent to `python -m iSpy.boot.boot -f`)",
    )
    boot.add_boot_arguments(setup)

    start = subparsers.add_parser(
        "start",
        help="Normal boot against the existing Config/config.json (equivalent to `python -m iSpy.boot.boot`)",
    )
    boot.add_boot_arguments(start)

    return parser


def main(argv=None) -> int:
    args = _build_parser().parse_args(argv)
    config = boot.on_boot(
        install_service=args.service,
        fresh=args.command == "setup",
        wait=args.wait,
        replay=args.replay,
        replay_speed=args.replay_speed,
        replay_cam=args.replay_cam,
        replay_loop=not args.replay_no_loop,
    )

    if args.replay:
        # the flags come from the shared add_boot_arguments(), so ignoring them
        # here booted the LIVE camera stack for what the user asked to be a
        # replay - the one outcome replay mode exists to prevent
        from iSpy.core.game_loop import main as run_vision

        run_vision(config=config)
        return 0

    # mirror boot.py's main(): flush everything and hard-exit to dodge
    # RKNN/OpenCV native-extension segfaults during interpreter teardown on ARM
    logging.shutdown()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(0)
    return 0


if __name__ == "__main__":
    main()
