# DISCLAMER: This file is generated by AI because I don't know how to do argparse properly.
import argparse
import logging
import os
import sys

from iSpy.boot import boot


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ispy",
        description="iSpy control surface (trivial wrappers around the boot sequence).",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # -s/--service and -w/--wait come from boot.add_boot_arguments() so they
    # can never drift from `python -m iSpy.boot.boot`.
    setup = subparsers.add_parser(
        "setup",
        help="Fresh first-time install (equivalent to `python -m iSpy.boot.boot -f`)",
    )
    boot.add_boot_arguments(setup)

    start = subparsers.add_parser(
        "start",
        help="Normal boot against the existing Config/config.json (equivalent to `python -m iSpy.boot.boot`)",
    )
    boot.add_boot_arguments(start)

    return parser


def main(argv=None) -> int:
    args = _build_parser().parse_args(argv)
    config = boot.on_boot(
        install_service=args.service and not args.replay,
        fresh=args.command == "setup",
        wait=args.wait and not args.replay,
    )

    if args.replay:
        boot._configure_replay(
            config,
            args.replay,
            args.replay_cam,
            args.replay_speed,
            loop=not args.replay_no_loop,
        )

    # boot only prepares the install - config, models, cameras, service. the
    # vision loop is a separate step, and exiting here is why "ispy start"
    # (what the install scripts tell people to run) brought the web UI up and
    # then did nothing else. ispy-run is the same thing without the boot.
    #
    # imported here, not at module scope: importing game_loop configures
    # logging and pulls in the whole vision stack (torch and all), which
    # "ispy setup" has no use for
    from iSpy.core.game_loop import main as game_loop_main

    game_loop_main(config)

    # mirror boot.py's main(): flush everything and hard-exit to dodge
    # RKNN/OpenCV native-extension segfaults during interpreter teardown on ARM
    logging.shutdown()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(0)
    return 0


if __name__ == "__main__":
    main()
