# DISCLAMER: This file is generated by AI for testing purposes.
import json
import logging
import tempfile
import unittest
from pathlib import Path

from iSpy.config.iSpyConfig import iSpyConfig


class LogLevelConfigTests(unittest.TestCase):
    """iSpyConfig._configure_logging is the last writer of the logging setup -
    boot and the game loop both pin things to INFO before the config is read -
    so the configured log_level has to actually land on the iSpy logger."""

    def setUp(self):
        root = logging.getLogger()
        ispy = logging.getLogger("iSpy")
        saved_handlers = list(root.handlers)
        saved_root_level = root.level
        saved_ispy_level = ispy.level

        def _restore():
            for handler in list(root.handlers):
                if handler not in saved_handlers:
                    root.removeHandler(handler)
                    handler.close()
            root.handlers[:] = saved_handlers
            root.setLevel(saved_root_level)
            ispy.setLevel(saved_ispy_level)

        self.addCleanup(_restore)

        # held for the lifetime of the test - letting the TemporaryDirectory
        # go out of scope deletes it, and iSpyConfig(create=True) would then
        # quietly write and reload a *default* config instead of ours.
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self._seq = 0

    def _load(self, log_level):
        self._seq += 1
        path = Path(self._tmp.name) / f"config{self._seq}.json"
        # log_file "" keeps the run from appending to Outputs/log.txt
        path.write_text(json.dumps({"log_level": log_level, "log_file": ""}))
        return iSpyConfig(str(path))

    def test_configured_level_is_applied_to_the_ispy_logger(self):
        for name, expected in (
            ("DEBUG", logging.DEBUG),
            ("INFO", logging.INFO),
            ("WARNING", logging.WARNING),
            ("ERROR", logging.ERROR),
            ("CRITICAL", logging.CRITICAL),
        ):
            with self.subTest(log_level=name):
                self._load(name)
                self.assertEqual(logging.getLogger("iSpy").getEffectiveLevel(), expected)

    def test_level_is_case_insensitive(self):
        self._load("warning")
        self.assertEqual(logging.getLogger("iSpy").getEffectiveLevel(), logging.WARNING)

    def test_quiet_level_suppresses_child_records(self):
        self._load("WARNING")
        child = logging.getLogger("iSpy.some.module")
        self.assertFalse(child.isEnabledFor(logging.DEBUG))
        self.assertFalse(child.isEnabledFor(logging.INFO))
        self.assertTrue(child.isEnabledFor(logging.WARNING))

    def test_junk_level_falls_back_to_info(self):
        # "handlers" resolves via getattr(logging, ...) to a module attribute
        # that is not a level - setLevel would raise on it.
        for junk in ("handlers", "not-a-level", "", 12.5, None):
            with self.subTest(log_level=junk):
                self._load(junk)
                self.assertEqual(
                    logging.getLogger("iSpy").getEffectiveLevel(), logging.INFO
                )


if __name__ == "__main__":
    unittest.main()
