# DISCLAMER: This file is generated by AI for testing purposes.
"""Focused tests for the monocular voxel world pipeline.

Covers the sparse voxel store, the Depth-Anything -> world-point geometry, and
the pipeline's output contract, without loading any model weights.
"""

import math
import unittest

import numpy as np

from iSpy.vision import triangulation
from iSpy.vision.pipelines import get_pipeline_classes
from iSpy.vision.pipelines.voxel_world import VoxelWorldPipeline
from iSpy.vision.voxel_map import (
    SparseVoxelMap,
    camera_points_to_robot,
    depth_plane_range,
    depth_to_camera_points,
    focal_length_pixels,
    relative_depth_to_distance,
)


class VoxelMapTests(unittest.TestCase):
    def test_integrate_dedups_repeated_hits(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        pts = np.array([[0.05, 0.05, 0.05], [1.0, 0.0, 0.0], [5.0, 5.0, 5.0]])
        self.assertEqual(vmap.integrate(pts), 3)
        # a repeat observation adds hits but no new voxels (0.0 floors into the
        # same 0.1 cube as 0.05)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        self.assertEqual(vmap.count(), 3)
        hits = {tuple(round(c, 2) for c in v[:3]): v[3] for v in vmap.export()}
        self.assertEqual(hits[(0.05, 0.05, 0.05)], 2)

    def test_integrate_drops_non_finite(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        pts = np.array([[0.0, 0.0, 0.0], [np.nan, 1.0, 1.0], [np.inf, 0.0, 0.0]])
        self.assertEqual(vmap.integrate(pts), 1)

    def test_capacity_evicts_least_recent(self):
        vmap = SparseVoxelMap(voxel_size=0.1, max_voxels=2)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]), now=1.0)
        vmap.integrate(np.array([[1.0, 0.0, 0.0]]), now=2.0)
        vmap.integrate(np.array([[2.0, 0.0, 0.0]]), now=3.0)
        self.assertEqual(vmap.count(), 2)
        centers = sorted(round(v[0], 3) for v in vmap.export())
        self.assertAlmostEqual(centers[0], 1.05)
        self.assertAlmostEqual(centers[1], 2.05)

    def test_decay_removes_stale_voxels(self):
        vmap = SparseVoxelMap(voxel_size=0.1, decay_seconds=1.0)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]), now=10.0)
        self.assertEqual(vmap.decay(now=10.5), 0)
        self.assertEqual(vmap.count(), 1)
        self.assertEqual(vmap.decay(now=12.0), 1)
        self.assertEqual(vmap.count(), 0)

    def test_export_sorted_by_hits_and_capped(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        vmap.integrate(np.array([[1.0, 0.0, 0.0], [1.0, 0.0, 0.0]]))
        vmap.integrate(np.array([[2.0, 0.0, 0.0]]))
        exported = vmap.export(max_points=2)
        self.assertEqual(len(exported), 2)
        self.assertAlmostEqual(exported[0][0], 1.05)
        self.assertEqual(exported[0][3], 2)

    def test_export_min_count_filters_noise(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        vmap.integrate(np.array([[1.0, 0.0, 0.0], [1.0, 0.0, 0.0]]))
        exported = vmap.export(min_count=2)
        self.assertEqual(len(exported), 1)
        self.assertAlmostEqual(exported[0][0], 1.05)

    def test_integrate_averages_color_per_voxel(self):
        # two red-ish and one blue point in the same cell -> weighted average
        vmap = SparseVoxelMap(voxel_size=0.5)
        pts = np.array([[0.05, 0.05, 0.05], [0.10, 0.10, 0.10]])
        vmap.integrate(pts, colors=np.array([[200, 0, 0], [200, 0, 0]]))
        vmap.integrate(np.array([[0.20, 0.20, 0.20]]), colors=np.array([[0, 0, 100]]))
        exported = vmap.export()
        self.assertEqual(len(exported[0]), 7)
        r, g, b = exported[0][4:7]
        self.assertAlmostEqual(r, (200 * 2 + 0) / 3, delta=1)
        self.assertEqual(g, 0)
        self.assertAlmostEqual(b, (0 * 2 + 100) / 3, delta=1)

    def test_export_defaults_uncolored_voxels_to_grey(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        exported = vmap.export()
        self.assertEqual(exported[0][4:7], [170, 170, 170])


class GeometryTests(unittest.TestCase):
    def test_vectorized_transform_matches_scalar(self):
        pts = np.array([[0.1, 0.2, 3.0], [1.0, -0.5, 5.0], [-0.3, 0.0, 2.0]])
        batch = camera_points_to_robot(pts, 10.0, 20.0, 30.0, 15.0, -10.0)
        for i, point in enumerate(pts):
            scalar = triangulation.camera_point_to_robot(
                tuple(point), 10.0, 20.0, 30.0, 15.0, -10.0
            )
            np.testing.assert_allclose(batch[i], scalar, rtol=1e-12)

    def test_depth_to_camera_points_filters_invalid(self):
        depth = np.array(
            [
                [0.0, np.nan, 2.0],
                [np.inf, 1.0, 3.0],
            ],
            dtype=np.float64,
        )
        pts = depth_to_camera_points(depth, focal_px=100.0, stride=1)
        self.assertEqual(pts.shape[1], 3)
        self.assertTrue(np.isfinite(pts).all())
        self.assertTrue((pts[:, 2] > 0).all())
        self.assertEqual(len(pts), 3)

    def test_center_pixel_backprojects_to_optical_axis(self):
        depth = np.full((40, 40), 5.0, dtype=np.float64)
        pts = depth_to_camera_points(depth, focal_px=200.0, stride=1)
        center = pts[np.argmin(np.abs(pts[:, 0]) + np.abs(pts[:, 1]))]
        self.assertAlmostEqual(center[0], 0.0, places=6)
        self.assertAlmostEqual(center[1], 0.0, places=6)
        self.assertAlmostEqual(center[2], 5.0, places=6)

    def test_nearer_relative_depth_maps_to_smaller_distance(self):
        depth = np.array([[0.0, 1.0]], dtype=np.float64)
        dist = relative_depth_to_distance(depth, 0.0, 1.0, 10.0, near_depth=0.5)
        # higher relative depth = nearer = smaller distance
        self.assertLess(dist[0, 1], dist[0, 0])
        self.assertAlmostEqual(dist[0, 1], 0.5)  # near plane
        self.assertAlmostEqual(dist[0, 0], 10.0)  # far plane

    def test_inverse_depth_recovers_perspective_not_linear_ramp(self):
        # A disparity (1/z) map for z in 1..10 m must stay ratio-preserving
        # (near:far ~ 1:9) and monotonic, not pile onto the far plane.
        z_true = np.linspace(1.0, 10.0, 400).reshape(1, -1)
        relative = 1.0 / z_true
        dist = relative_depth_to_distance(relative, relative.min(), relative.max(), 10.0, near_depth=0.5)
        self.assertLess(dist.max(), 10.5)
        self.assertGreaterEqual(dist.min(), 0.45)
        self.assertGreater(dist.max() / dist.min(), 5.0)
        # nearer stays nearer (the ends are flat because of percentile clipping)
        self.assertTrue(np.all(np.diff(dist[0]) >= -1e-9))

    def test_depth_plane_range_preserves_scene_ratio(self):
        # self-scaling: the far plane follows the disparity ratio, not Max Depth
        depth = np.linspace(0.2, 0.8, 500)
        d_lo, d_hi, z_near, z_far = depth_plane_range(
            depth, depth.min(), depth.max(), 10.0, near_depth=1.0
        )
        self.assertAlmostEqual(z_near, 1.0, places=6)
        self.assertAlmostEqual(z_far / z_near, d_hi / d_lo, places=6)
        # Max Depth stays a cap when the scene ratio is huge
        _, _, _, capped = depth_plane_range(
            np.array([0.001, 1.0]), 0.001, 1.0, 4.0, near_depth=1.0
        )
        self.assertAlmostEqual(capped, 4.0, places=6)

    def test_flat_depth_map_does_not_divide_by_zero(self):
        depth = np.full((10, 10), 4.0, dtype=np.float64)
        dist = relative_depth_to_distance(depth, 4.0, 4.0, 10.0)
        self.assertTrue(np.isfinite(dist).all())

    def test_room_depth_map_builds_meter_scale_world(self):
        # A 2-5 m room, expressed as DAV2 relative inverse depth. With the near
        # plane anchored at the true nearest distance (2 m) the self-scaling
        # inverse model recovers a ~2-5 m world - not the sub-30cm blob of a
        # collapsed scale and not the 10 m funnel of a forced near..max stretch.
        z_true = np.linspace(2.0, 5.0, 64).reshape(1, -1)
        relative = np.repeat(1.0 / z_true, 48, axis=0)
        dist = relative_depth_to_distance(
            relative, relative.min(), relative.max(), 10.0, near_depth=2.0
        )
        self.assertAlmostEqual(float(dist.min()), 2.0, places=2)
        self.assertAlmostEqual(float(dist.max()), 5.0, delta=0.6)
        cam = depth_to_camera_points(dist, focal_px=200.0, stride=1)
        world = camera_points_to_robot(cam, 0.0, 0.0, 1.0, 0.0, 0.0)
        world = world[world[:, 2] >= -25.0]
        extent = world.max(axis=0) - world.min(axis=0)
        self.assertGreater(extent[1], 1.0)  # forward axis spans > 1 m
        self.assertGreater(world[:, 1].max(), 4.0)  # reaches the room's far wall

    def test_focal_length_prefers_fov_then_defaults(self):
        fov_focal = focal_length_pixels(640, {"fov": 60.0})
        self.assertAlmostEqual(fov_focal, 320.0 / math.tan(math.radians(30.0)))
        default = focal_length_pixels(640, {})
        self.assertAlmostEqual(default, 320.0 / math.tan(math.radians(30.0)))

    def test_focal_length_scales_camera_matrix_by_resolution(self):
        focal = focal_length_pixels(
            1280,
            {"camera_matrix": [[500.0, 0, 0], [0, 500.0, 0], [0, 0, 1]], "resolution": [640, 480]},
        )
        self.assertAlmostEqual(focal, 1000.0)


class VoxelWorldPipelineTests(unittest.TestCase):
    def test_pipeline_is_registered(self):
        self.assertIn("voxel_world", get_pipeline_classes())

    def test_schema_exposes_voxel_settings(self):
        schema = VoxelWorldPipeline.config_schema()
        for key in (
            "voxel_size",
            "pixel_stride",
            "max_voxels",
            "export_max_voxels",
            "min_voxel_count",
            "decay_seconds",
            "depth_scale",
            "min_height",
            "voxel_min_depth",
            "near_depth",
            "auto_ground",
            "auto_world_scale",
        ):
            self.assertIn(key, schema)
            self.assertIn(schema[key]["type"], ("number", "toggle", "select"))
        # depth-anything settings are inherited
        self.assertIn("max_depth", schema)
        self.assertIn("process_every", schema)

    @staticmethod
    def _build_pipeline():
        pipeline = VoxelWorldPipeline.__new__(VoxelWorldPipeline)
        pipeline.logger = None
        pipeline._frame_count = 0
        pipeline._every = 1
        pipeline._last_depth = None
        pipeline._last_objects = []
        pipeline.max_depth = 10.0
        pipeline._z_scale = 1.0
        pipeline.depth_scale = 1.0
        pipeline.near_depth = 0.3
        pipeline.pixel_stride = 4
        pipeline.voxel_min_depth = 0.0
        pipeline.min_height = -100.0
        pipeline.auto_ground = True
        pipeline._ground_offset = None
        pipeline.voxel_size = 0.1
        pipeline.export_max_voxels = 1000
        pipeline.min_voxel_count = 1
        pipeline.unit = "frc"
        pipeline._unit_label = "m"
        pipeline.camera_x = 0.0
        pipeline.camera_y = 0.0
        pipeline.camera_height = 36.0 * 0.0254
        pipeline.camera_yaw = 0.0
        pipeline.camera_pitch = 10.0
        pipeline.calibration = {"fov": 60.0}
        pipeline.voxel_map = SparseVoxelMap(voxel_size=0.1, decay_seconds=0.0)
        return pipeline

    def test_run_emits_single_voxel_object(self):
        pipeline = self._build_pipeline()
        frame = np.zeros((80, 80, 3), dtype=np.uint8)

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        objects, out_frame = pipeline.run()
        self.assertEqual(len(objects), 1)
        obj = objects[0]
        self.assertEqual(obj.vis_type, "voxels")
        meta = obj.vis_meta
        self.assertEqual(meta["kind"], "voxel_map")
        self.assertGreater(meta["count"], 0)
        self.assertTrue(meta["voxels"])
        for voxel in meta["voxels"]:
            self.assertEqual(len(voxel), 7)
            self.assertTrue(all(math.isfinite(v) for v in voxel[:3]))
            self.assertTrue(all(0 <= c <= 255 for c in voxel[4:7]))
        self.assertIsNotNone(out_frame)

    def test_voxel_color_is_sampled_from_the_frame(self):
        # a solid red frame (BGR) must produce red voxels
        pipeline = self._build_pipeline()
        frame = np.zeros((80, 80, 3), dtype=np.uint8)
        frame[:, :, 2] = 255  # red in BGR

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        objects, _ = pipeline.run()
        voxels = objects[0].vis_meta["voxels"]
        self.assertTrue(voxels)
        for v in voxels:
            self.assertGreater(v[4], 200)  # red
            self.assertLess(v[5], 20)
            self.assertLess(v[6], 20)

    def test_voxel_object_reuses_instance_and_resets_pose(self):
        # the voxel world recycles ONE Object so its identity (and the viewer's
        # render group keyed by o.id) stays stable across ticks
        pipeline = self._build_pipeline()
        obj_a = pipeline._voxel_object()
        self.assertEqual(obj_a.name, "voxel_world")
        self.assertEqual(obj_a.vis_type, "voxels")
        obj_b = pipeline._voxel_object()
        self.assertIs(obj_a, obj_b)
        self.assertEqual(obj_a.get_id(), obj_b.get_id())
        # simulate a tracker converting the shared instance in place, then
        # verify the pipeline re-anchors it every tick so roll/pitch/yaw never
        # accumulate a robot_yaw (they would feed a bogus pose to the viewer)
        obj_a.roll = 0.3
        obj_a.pitch = 0.1
        obj_a.yaw = 1.2
        pipeline._voxel_object()
        self.assertEqual(obj_a.roll, 0.0)
        self.assertEqual(obj_a.pitch, 0.0)
        self.assertEqual(obj_a.yaw, 0.0)

    def test_auto_ground_lifts_a_scene_below_the_origin(self):
        # A straight-down camera (pitch 90) with height 0 maps every point
        # below z=0. Auto ground must shift the map so it straddles the grid
        # instead of hanging entirely underneath it.
        pipeline = self._build_pipeline()
        pipeline.camera_height = 0.0
        pipeline.camera_pitch = 90.0
        pipeline.min_height = -100.0
        pipeline.auto_ground = True
        pipeline._ground_offset = None
        frame = np.zeros((80, 80, 3), dtype=np.uint8)

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        objects, _ = pipeline.run()
        meta = objects[0].vis_meta
        self.assertIsNotNone(pipeline._ground_offset)
        self.assertNotAlmostEqual(meta["debug"]["world_z_max"], meta["debug"]["world_z_min"])
        # after centering, the densest plane sits at z~0, so the max is >= 0
        self.assertGreaterEqual(meta["debug"]["world_z_max"], 0.0)

    def test_min_height_never_blanks_the_world(self):
        # A floor clip above the whole reconstruction (a camera height/pitch
        # that does not match the world origin) must not silently delete the
        # map - the clip is skipped and surfaced as a warning instead.
        pipeline = self._build_pipeline()
        pipeline.min_height = 100.0
        frame = np.zeros((80, 80, 3), dtype=np.uint8)

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        objects, _ = pipeline.run()
        self.assertEqual(len(objects), 1)
        meta = objects[0].vis_meta
        self.assertGreater(meta["count"], 0)
        self.assertEqual(meta["debug"]["past_min_height"], 0)
        self.assertIn("Min Height", meta["debug"].get("warning", ""))

        # a second tick must not append the same warning again - the viewer
        # used to show one giant repeating string
        objects, _ = pipeline.run()
        warning = objects[0].vis_meta["debug"].get("warning", "")
        self.assertEqual(warning.count("removed every point"), 1)

    def test_run_reuses_depth_between_inference_frames(self):
        pipeline = self._build_pipeline()
        pipeline._every = 5
        frame = np.zeros((80, 80, 3), dtype=np.uint8)
        calls = {"n": 0}

        def fake_depth(f):
            calls["n"] += 1
            return np.tile(
                np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)[:, None],
                (1, f.shape[1]),
            )

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        pipeline.run()
        first_count = pipeline.voxel_map.count()
        pipeline.run()
        self.assertEqual(calls["n"], 1)
        self.assertEqual(pipeline.voxel_map.count(), first_count)

    def test_run_without_model_returns_raw_frame(self):
        pipeline = self._build_pipeline()
        frame = np.full((20, 20, 3), 7, dtype=np.uint8)
        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: False

        objects, out_frame = pipeline.run()
        self.assertEqual(objects, [])
        self.assertTrue(np.array_equal(out_frame, frame))

    def test_auto_world_scale_stretches_a_small_scene(self):
        # A 1.5 m person in front of a 5 m wall has a disparity ratio of ~3.3.
        # Anchored at the 0.3 m default near plane that collapses the whole
        # world to a sub-metre blob; Auto Scale World must stretch it out so
        # it fills the 10 m cap and the object geometry stays recognizable.
        pipeline = self._build_pipeline()
        frame = np.zeros((80, 80, 3), dtype=np.uint8)
        depth = np.full((80, 80), 5.0)
        depth[25:65, 20:60] = 1.5
        relative = 1.0 / depth

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = lambda f: relative
        pipeline._annotate = lambda f, d: f

        objects, _ = pipeline.run()
        dbg = objects[0].vis_meta["debug"]
        self.assertTrue(dbg["auto_scale"])
        self.assertAlmostEqual(dbg["dist_max"], 10.0, delta=0.1)

        # turning it off keeps the old, collapsed behaviour
        pipeline.auto_world_scale = False
        objects, _ = pipeline.run()
        dbg = objects[0].vis_meta["debug"]
        self.assertFalse(dbg["auto_scale"])
        self.assertLess(dbg["dist_max"], 1.1)

    def test_shadows_method_needs_no_model(self):
        # 'shadows' is a pure heuristic - no optimization, always ready, and
        # the depth map is synthesized on the fly so no inference backend
        # exists.
        pipeline = self._build_pipeline()
        pipeline.depth_method = "shadows"
        frame = np.zeros((80, 80, 3), dtype=np.uint8)
        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._annotate = lambda f, d: f

        self.assertFalse(pipeline._optimization_requested())
        self.assertEqual(pipeline.is_ready(), (True, "ready"))

        objects, _ = pipeline.run()
        meta = objects[0].vis_meta
        self.assertEqual(meta["model"]["method"], "shadows")
        self.assertEqual(meta["model"]["backend"], "synthetic")
        self.assertGreater(meta["count"], 0)
        self.assertTrue(meta["voxels"])

    def test_shadows_estimator_maps_bright_to_near_and_dark_to_far(self):
        # HSV value is read as inverse depth: lit pixels keep a high relative
        # depth (near) and shadowed pixels drop (far) - same convention as
        # Depth Anything, so the rest of the pipeline is method-blind.
        pipeline = self._build_pipeline()
        frame = np.zeros((40, 40, 3), dtype=np.uint8)
        frame[:, :, :] = (40, 40, 40)  # left half = shadow, dark -> far
        frame[:, 20:, :] = (220, 220, 220)  # right half = lit, bright -> near
        depth = pipeline._estimate_shadows(frame)
        self.assertEqual(depth.shape, frame.shape[:2])
        self.assertTrue(np.isfinite(depth).all())
        self.assertGreater(float(depth[:, 20:].mean()), float(depth[:, :20].mean()))

    def test_schema_offers_only_depth_anything_and_shadows(self):
        schema = VoxelWorldPipeline.config_schema()
        self.assertEqual(schema["depth_method"]["options"], ["depth_anything", "shadows"])


if __name__ == "__main__":
    unittest.main()
