# DISCLAMER: This file is generated by AI for testing purposes.
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "iSpy" / "web" / "templates"
STATIC = ROOT / "iSpy" / "web" / "static"


def read(name: str) -> str:
    return (TEMPLATES / name).read_text(encoding="utf-8")


class TestGlobalChrome(unittest.TestCase):
    def test_base_has_favicon_and_theme_color(self):
        html = read("base.html")
        self.assertIn('rel="icon"', html)
        self.assertIn("/static/favicon.svg", html)
        # matched loosely so an HTML reformat (self-closing tags, attribute
        # wrapping) can't break a test that's really about the tag being present
        self.assertIn('name="theme-color"', html)
        self.assertIn('content="#0d1117"', html)

    def test_favicon_exists(self):
        svg = (STATIC / "favicon.svg").read_text(encoding="utf-8")
        self.assertIn("#0d1117", svg)  # dark bg
        self.assertIn("#2f81f7", svg)  # brand accent glyph

    def test_design_css_shared_pieces(self):
        css = (STATIC / "css" / "design.css").read_text(encoding="utf-8")
        for needle in (
            ".skeleton",
            ".skeleton-block",
            ".conn-banner",
            ".sidebar-footer",
            ".chart-waiting",
            ".empty-state.has-icon",
            ".plugin-pill.pill-tracker",
            "a.active::before",
        ):
            self.assertIn(needle, css)


class TestSetupWizardPage(unittest.TestCase):
    SOURCE = (ROOT / "iSpy" / "web" / "Backend" / "SetupWizard.py").read_text(
        encoding="utf-8"
    )

    def test_links_design_system_and_favicon(self):
        self.assertIn("/static/css/design.css", self.SOURCE)
        self.assertIn("/static/favicon.svg", self.SOURCE)

    def test_no_raw_hex_feedback_colors(self):
        self.assertNotIn("#2c7", self.SOURCE)
        self.assertNotIn("#f44", self.SOURCE)

    def test_uses_design_system_classes(self):
        for cls in (
            "btn-ok",
            "setup-alert",
            "form-row",
            "form-label",
            "settings-section",
        ):
            self.assertIn(cls, self.SOURCE)

    def test_submit_has_loading_state(self):
        self.assertIn("Saving", self.SOURCE)
        self.assertIn("disabled = true", self.SOURCE)


class TestInlineStyleCleanup(unittest.TestCase):
    def test_no_border_background_inline_buttons(self):
        offenders = []
        for tpl in TEMPLATES.glob("*.html"):
            if 'style="background:var(--border);"' in tpl.read_text(encoding="utf-8"):
                offenders.append(tpl.name)
        self.assertEqual(offenders, [])

    def test_no_raw_status_hex_in_templates(self):
        offenders = []
        for tpl in TEMPLATES.glob("*.html"):
            text = tpl.read_text(encoding="utf-8")
            for hexcode in ("'#2c7'", "'#f44'", "'#f66'"):
                if hexcode in text:
                    offenders.append(f"{tpl.name}:{hexcode}")
        self.assertEqual(offenders, [])


class TestLoadingAndConnectionStates(unittest.TestCase):
    CASES = {
        "dashboard.html": ["stat-value skeleton", "connLost()", "connOk()"],
        "health.html": ["stat-value skeleton", "skeleton-block", "connTracker(2)"],
        "metrics.html": ["chart-waiting", "markHasData", "connTracker(2)"],
        "logs.html": ["connTracker(2)"],
        "models.html": ["skeleton-block", "has-icon"],
        "datasets.html": ["skeleton-block", "has-icon"],
        "cameras.html": ["camerasConn = connTracker(2)", "has-icon"],
    }

    def test_pages_wired(self):
        for name, needles in self.CASES.items():
            html = read(name)
            for needle in needles:
                self.assertIn(needle, html, f"{name} missing {needle!r}")


class TestVersionEndpoint(unittest.TestCase):
    def test_api_version_serves_package_version(self):
        from iSpy import __version__
        from iSpy.config.iSpyConfig import iSpyConfig
        from iSpy.web.Backend.WebApp import create_app

        web_app = create_app(cameras=[], config=iSpyConfig())
        client = web_app.flask_app.test_client()
        r = client.get("/api/version")
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.get_json()["version"], __version__)


class TestRollbackPage(unittest.TestCase):
    HTML = read("rollback.html")

    def test_toggles_are_not_wrapped_in_the_switch_class(self):
        # .switch input { opacity: 0; width: 0 } outranks .toggle-input, so a
        # toggle inside a .switch renders as nothing at all
        self.assertNotIn('class="switch"', self.HTML)
        self.assertNotIn("<label class=\"switch\">", self.HTML)
        self.assertIn('id="rb-enabled" class="toggle-input"', self.HTML)

    def test_a_toggle_setting_row_is_rendered(self):
        self.assertIn('class="toggle-input" data-key=', self.HTML)

    def test_heading_is_converted_from_radians_for_display(self):
        # robot_pose.heading is radians; printing it raw labelled "deg" showed
        # 1.57 degrees for a 90 degree turn
        self.assertIn("(p.heading * 180) / Math.PI", self.HTML)
        self.assertNotIn("(p.heading || 0) * Math.PI) / 180", self.HTML)

    def test_the_open_segment_is_not_offered_for_scrubbing(self):
        self.assertIn("s.recording", self.HTML)


class TestRollbackCss(unittest.TestCase):
    def test_warning_banner_is_styled(self):
        css = (STATIC / "css" / "design.css").read_text(encoding="utf-8")
        self.assertIn(".vision-warn", css)


class TestReplayCameraIsCliOnly(unittest.TestCase):
    HTML = read("cameras.html")

    def test_replay_is_not_in_the_camera_type_dropdown(self):
        # the modal has no source field for a replay camera, so adding one
        # failed with "name and source required"
        line = next(
            ln for ln in self.HTML.splitlines() if "camera_type: {" in ln
        )
        self.assertNotIn("'replay'", line)

    def test_an_existing_replay_camera_can_still_be_edited(self):
        self.assertIn("opt.value = 'replay'", self.HTML)
        self.assertIn("payload.source = (camModal.data && camModal.data.source)", self.HTML)


class TestRollbackNaNGuard(unittest.TestCase):
    # jsonify emits a bare NaN token, which is not valid JSON - res.json() then
    # throws in the browser and the whole segment loads with an empty timeline

    def test_detection_numbers_are_coerced_through_isfinite(self):
        from iSpy.web.modules.rollback import _trim_detection

        det = _trim_detection(
            {"name": "goal", "confidence": float("nan"), "x": float("inf")}
        )
        self.assertEqual(det["confidence"], 0.0)
        self.assertEqual(det["x"], 0.0)
        self.assertEqual(det["name"], "goal")

    def test_pose_numbers_are_coerced_through_isfinite(self):
        from iSpy.web.modules.rollback import _trim_pose

        pose = _trim_pose({"x": float("nan"), "y": 1.5, "heading": float("-inf")})
        self.assertEqual(pose, {"x": 0.0, "y": 1.5, "heading": 0.0})
        self.assertEqual(_trim_pose(None), {})

    def test_a_trimmed_timeline_is_valid_json(self):
        import json

        from iSpy.web.modules.rollback import _trim_detection, _trim_pose

        timeline = [
            {
                "i": 1,
                "n": 1,
                "d": [_trim_detection({"name": "goal", "x": float("nan")})],
                "p": _trim_pose({"x": float("nan"), "y": 0.0, "heading": float("nan")}),
            }
        ]
        # json.dumps with allow_nan=False is what res.json() effectively requires
        self.assertNotIn("NaN", json.dumps(timeline, allow_nan=False))

    def test_a_non_dict_detection_is_skipped_not_raised(self):
        from iSpy.web.modules.rollback import _trim_detection

        self.assertIsNone(_trim_detection("not a dict"))


if __name__ == "__main__":
    unittest.main()
