# DISCLAMER: This file is generated by AI for testing purposes.
import inspect
import json
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from iSpy.boot import boot
from iSpy.config.iSpyConfig import iSpyCameraConfig
from iSpy.core.rollback import _iter_segments, _sidecar_cams, read_sidecar
from iSpy.vision.Cameras.ReplayCamera import ReplayCamera


def _fake_session(root: Path, stem: str = "rollback_000001") -> Path:
    # a session the replay builder accepts: one segment, one recorded camera.
    # segments are a flat shared-stem group inside the session dir
    session = root / "session_2026-01-01_00-00-00"
    session.mkdir(parents=True, exist_ok=True)
    (session / f"{stem}.json").write_text(
        '{"cams": ["default_cam"], "records": [{"i": 1}]}', encoding="utf-8"
    )
    (session / f"{stem}_default_cam.avi").write_bytes(b"")
    return session


def _patched_boot(tmp: Path):
    """on_boot with every side effect stubbed, so only the config plumbing runs."""
    root = Path(tmp)
    real_config = root / "Config" / "config.json"
    real_config.parent.mkdir(parents=True, exist_ok=True)

    from iSpy.config.iSpyConfig import iSpyConfig

    iSpyConfig(str(real_config))  # materialize a real config file

    return mock.patch.multiple(
        boot,
        _configure_quiet_logging=mock.DEFAULT,
        setup_files=mock.DEFAULT,
        _consume_game_mode_web_off=mock.DEFAULT,
        cleanup_missing_cameras=mock.DEFAULT,
        cleanup_broken_images=mock.DEFAULT,
        validate_system=mock.Mock(return_value=True),
        get_pipeline_classes=mock.Mock(return_value={}),
    ), real_config


class ReplayBootTests(unittest.TestCase):
    def test_game_loop_main_accepts_a_prebuilt_config(self):
        from iSpy.core import game_loop

        self.assertIn("config", inspect.signature(game_loop.main).parameters)

        sentinel = mock.Mock()
        with mock.patch.object(game_loop, "iSpy") as spy:
            with mock.patch.object(game_loop, "iSpyConfig") as loader:
                game_loop.main(config=sentinel)

        # the passed-in config is used verbatim: nothing is reloaded from disk
        loader.assert_not_called()
        spy.assert_called_once_with(sentinel)

    def test_game_loop_main_loads_from_disk_without_a_config(self):
        from iSpy.core import game_loop

        with mock.patch.object(game_loop, "iSpy") as spy:
            with mock.patch.object(game_loop, "iSpyConfig") as loader:
                game_loop.main()

        loader.assert_called_once()
        spy.assert_called_once_with(loader.return_value)

    def test_on_boot_returns_the_replay_config_it_built(self):
        # main() hands this straight to the vision loop - if on_boot returns
        # None the replay cameras are thrown away and vision reloads from disk,
        # so --replay silently does nothing
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            session = _fake_session(root)
            patches, real_config = _patched_boot(root)
            before = real_config.read_text(encoding="utf-8")

            with patches, mock.patch.object(boot, "_PROJECT_ROOT", root):
                with mock.patch.object(
                    boot, "search_for_config", return_value=str(real_config)
                ):
                    config = boot.on_boot(replay=str(session))

            self.assertIsNotNone(config)
            cams = config.get("camera_configs")
            self.assertEqual(list(cams), ["replay_default_cam"])
            self.assertEqual(cams["replay_default_cam"]["source"], str(session))
            self.assertFalse(config.get("rollback", {}).get("enabled"))

            # a config.save() from anywhere during the replay must land on the
            # scratch file, never on the real config
            config.save(quiet=True)
            self.assertTrue((root / "Outputs" / "replay_config.json").exists())
            self.assertEqual(real_config.read_text(encoding="utf-8"), before)

    def test_on_boot_still_saves_the_real_config_without_replay(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            patches, real_config = _patched_boot(root)

            with patches, mock.patch.object(boot, "_PROJECT_ROOT", root):
                with mock.patch.object(
                    boot, "search_for_config", return_value=str(real_config)
                ):
                    config = boot.on_boot()

            self.assertIsNotNone(config)
            self.assertEqual(Path(config.file_path), real_config)

    def test_build_replay_camera_configs_keeps_replay_keys_at_the_top_level(self):
        from iSpy.config.iSpyConfig import iSpyConfig

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            real = root / "Config" / "config.json"
            real.parent.mkdir(parents=True)
            config = iSpyConfig(str(real))
            session = _fake_session(root)

            built = boot.build_replay_camera_configs(config, session, 2.0, False, "")
            entry = next(iter(built.values()))

            self.assertEqual(entry["camera_type"], "replay")
            self.assertEqual(entry["source"], str(session))
            self.assertEqual(entry["replay_cam"], "default_cam")
            self.assertEqual(entry["replay_speed"], 2.0)
            self.assertFalse(entry["loop"])


class CrashedSidecarTests(unittest.TestCase):
    # a power cut leaves the streamed sidecar unterminated - the exact case
    # rollback exists for, so the reader has to salvage it

    def _segment(self, root: Path, stem: str, cam: str, truncate: bool):
        # segments are a flat shared-stem group inside the session dir
        (root / f"{stem}_{cam}.avi").write_bytes(b"fake")
        body = (
            f'{{"stem": "{stem}", "cams": ["{cam}"], "fps": 30.0, "records": ['
            '{"i": 1, "detections": []},'
            '{"i": 2, "detections": [{"name": "goal"}]},'
        )
        if truncate:
            body += '{"i": 3, "detect'  # cut off mid-record, no closing brace
        else:
            body += '{"i": 3, "detections": []}]}'
        (root / f"{stem}.json").write_text(body, encoding="utf-8")
        return root

    def test_read_sidecar_returns_a_clean_sidecar_intact(self):
        with tempfile.TemporaryDirectory() as tmp:
            seg = self._segment(Path(tmp), "rollback_1", "Left", truncate=False)
            data = read_sidecar(seg / "rollback_1.json")
            self.assertEqual([r["i"] for r in data["records"]], [1, 2, 3])
            self.assertEqual(data["cams"], ["Left"])

    def test_read_sidecar_recovers_records_from_a_truncated_sidecar(self):
        with tempfile.TemporaryDirectory() as tmp:
            seg = self._segment(Path(tmp), "rollback_1", "Left", truncate=True)
            data = read_sidecar(seg / "rollback_1.json")
            # the two whole records survive, the partial one is dropped
            self.assertEqual([r["i"] for r in data["records"]], [1, 2])
            # the header is still recovered - without cams the segment lists as
            # a loose file with no camera
            self.assertEqual(data["cams"], ["Left"])
            self.assertEqual(data["stem"], "rollback_1")

    def test_iter_segments_groups_a_crashed_segment_by_its_cameras(self):
        with tempfile.TemporaryDirectory() as tmp:
            self._segment(Path(tmp), "rollback_1", "Left", truncate=True)
            segs = _iter_segments(Path(tmp))
            self.assertEqual(len(segs), 1)
            self.assertEqual(segs[0]["cams"], ["Left"])
            self.assertEqual(
                [p.name for p in segs[0]["files"]],
                ["rollback_1.json", "rollback_1_Left.avi"],
            )

    def test_sidecar_cams_reads_a_header_without_the_records(self):
        with tempfile.TemporaryDirectory() as tmp:
            seg = self._segment(Path(tmp), "rollback_1", "Left", truncate=True)
            self.assertEqual(_sidecar_cams(seg / "rollback_1.json"), ["Left"])

    def test_read_sidecar_tolerates_a_missing_or_empty_file(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self.assertEqual(read_sidecar(root / "nope.json"), {})
            empty = root / "empty.json"
            empty.write_text("", encoding="utf-8")
            self.assertEqual(read_sidecar(empty), {})
            headerless = root / "headerless.json"
            headerless.write_text('{"records": [', encoding="utf-8")
            self.assertEqual(read_sidecar(headerless), {"records": []})


class ReplayCameraFileResolutionTests(unittest.TestCase):
    # a camera name containing an underscore is the common case (camera_1), and
    # the old filename rsplit found the wrong sidecar for it

    def _segment(self, root: Path, stem: str, cams: list):
        for cam in cams:
            (root / f"{stem}_{cam}.avi").write_bytes(b"fake")
        (root / f"{stem}.json").write_text(
            json.dumps({"cams": cams, "records": [{"i": 1, "t": 1.0}]}),
            encoding="utf-8",
        )
        return root

    def _camera(self, root: Path, **overrides):
        cfg = iSpyCameraConfig(
            {
                "name": "replay",
                "camera_type": "replay",
                "source": str(root),
                "replay_cam": "",
                "replay_speed": 1000.0,
                **overrides,
            }
        )
        cam = ReplayCamera(cfg)
        # the fake clips are not real video - stop the reader before it spins
        # on them so nothing is left running for the rest of the suite
        self.addCleanup(cam.release)
        return cam

    def test_underscore_camera_names_still_find_their_records(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self._segment(root, "rollback_2026-01-01_00-00-00", ["camera_1"])

            cam = self._camera(root)
            pairs = cam._resolve_files()

            self.assertEqual(
                [p.name for p, _ in pairs],
                ["rollback_2026-01-01_00-00-00_camera_1.avi"],
            )
            self.assertEqual(pairs[0][1].name, "rollback_2026-01-01_00-00-00.json")
            self.assertEqual(len(cam._load_records(pairs[0][1])), 1)

    def test_blank_cam_selects_the_first_recorded_camera_only(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self._segment(root, "rollback_1", ["Left", "Right"])

            pairs = self._camera(root)._resolve_files()
            # one sidecar carries one record per camera, so concatenating both
            # cameras' clips would play every frame twice
            self.assertEqual([p.name for p, _ in pairs], ["rollback_1_Left.avi"])

    def test_named_cam_selects_that_camera(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self._segment(root, "rollback_1", ["Left", "Right"])

            pairs = self._camera(root, replay_cam="Right")._resolve_files()
            self.assertEqual([p.name for p, _ in pairs], ["rollback_1_Right.avi"])

    def test_a_loose_clip_finds_its_sidecar_by_prefix(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self._segment(root, "rollback_1", ["Left"])
            clip = root / "rollback_1_Left.avi"

            cam = self._camera(root, source=str(clip))
            self.assertEqual(
                [(p.name, s.name) for p, s in cam._resolve_files()],
                [("rollback_1_Left.avi", "rollback_1.json")],
            )

    def test_a_clip_with_no_records_fails_fast(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            clip = root / "loose.avi"
            clip.write_bytes(b"fake")

            cam = self._camera(root, source=str(clip))
            with self.assertRaises(ValueError):
                cam._open_camera()


class ReplayCompareTests(unittest.TestCase):
    def test_a_held_record_is_only_counted_once(self):
        # --replay-no-loop holds the final frame, so the loop re-reports the
        # same record every tick until shutdown
        from iSpy.core.rollback import ReplayCompare

        cmp = ReplayCompare("session_test")
        record = {"i": 7, "detections": [{"name": "goal"}]}
        for _ in range(50):
            cmp.add(record, [{"name": "goal"}])

        self.assertEqual(cmp.summary()["frames"], 1)

        cmp.add({"i": 8, "detections": []}, [])
        self.assertEqual(cmp.summary()["frames"], 2)

    def test_a_non_dict_record_is_refused(self):
        from iSpy.core.rollback import ReplayCompare

        cmp = ReplayCompare("session_test")
        self.assertFalse(cmp.add(None, []))
        self.assertEqual(cmp.summary()["frames"], 0)


class ReplayCameraRecordLookupTests(unittest.TestCase):
    def test_replay_record_is_an_index_not_a_scan(self):
        # the compare looks the record up on every tick; scanning the sidecar
        # for a matching "i" was O(n) per frame
        from iSpy.config.iSpyConfig import iSpyCameraConfig

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            cam = ReplayCamera(
                iSpyCameraConfig(
                    {
                        "name": "replay",
                        "camera_type": "replay",
                        "source": str(root),
                        "replay_speed": 1000.0,
                    }
                )
            )
            self.addCleanup(cam.release)

            cam._records = [{"i": n} for n in range(5)]
            cam._replay_idx = 3
            cam._replay_i = 3
            self.assertEqual(cam.replay_record(), {"i": 3})

            # an index the sidecar does not cover must return nothing, not the
            # last record that happened to share an "i"
            cam._replay_idx = 99
            self.assertIsNone(cam.replay_record())

    def test_destroy_releases_the_open_captures(self):
        # teardown calls destroy(), never release()
        from iSpy.config.iSpyConfig import iSpyCameraConfig

        with tempfile.TemporaryDirectory() as tmp:
            cam = ReplayCamera(
                iSpyCameraConfig(
                    {
                        "name": "replay",
                        "camera_type": "replay",
                        "source": str(tmp),
                    }
                )
            )
            cap = mock.Mock()
            cam._playlist = [{"cap": cap, "next": 5}]

            cam.destroy()

            cap.release.assert_called_once()


class ReplayConfigKeyTests(unittest.TestCase):
    def test_replay_keys_stay_at_the_top_level_of_a_camera(self):
        # a normalize pass would otherwise move them into pipeline.settings,
        # where ReplayCamera never looks for them
        from iSpy.config.iSpyConfig import _CAMERA_CORE_KEYS, normalize_camera_entry

        for key in ("replay_cam", "replay_speed", "loop"):
            self.assertIn(key, _CAMERA_CORE_KEYS)

        cam = normalize_camera_entry(
            {
                "name": "replay_Left",
                "camera_type": "replay",
                "pipeline": "object_detection",
                "replay_cam": "Left",
                "replay_speed": 2.0,
                "loop": False,
            }
        )
        self.assertEqual(cam.get("replay_cam"), "Left")
        self.assertEqual(cam.get("replay_speed"), 2.0)
        self.assertFalse(cam.get("loop"))
        self.assertEqual(
            cam.get("pipeline", {}).get("settings", {}).get("replay_cam"), None
        )


class RollbackWebPayloadTests(unittest.TestCase):
    # the web module reads the same session tree the recorder wrote

    def _module(self, data_dir, recorder=None):
        from iSpy.web.modules.rollback import RollbackModule

        cfg = mock.Mock()
        cfg.get.return_value = {"data_dir": str(data_dir)}
        vision = mock.Mock()
        vision.utilities = {"rollback": recorder} if recorder else {}
        return RollbackModule({"config": cfg, "vision_instance": vision})

    def _session(self, root: Path, stem: str = "rollback_1"):
        session = root / "session_2026-01-01_00-00-00"
        session.mkdir(parents=True, exist_ok=True)
        (session / "session.json").write_text(
            json.dumps(
                {
                    "started": 1.0,
                    "version": "1.2.3",
                    "unit": "metric",
                    "cameras": {"Left": {}},
                }
            ),
            encoding="utf-8",
        )
        (session / f"{stem}.json").write_text(
            json.dumps({"cams": ["Left"], "records": [{"i": 1, "detections": []}]}),
            encoding="utf-8",
        )
        (session / f"{stem}_Left.avi").write_bytes(b"x")
        return session

    def test_segment_payload_flags_the_segment_being_recorded(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            session = self._session(root)
            recorder = mock.Mock(
                _video_output_dir=str(root), _started=True, _stem="rollback_1"
            )
            mod = self._module(root, recorder)

            seg = mod._find_segment(
                {"name": session.name, "path": session}, "rollback_1"
            )
            payload = mod._segment_payload(seg)
            self.assertTrue(payload["recording"])
            self.assertEqual(payload["cams"], ["Left"])

            recorder._started = False
            self.assertFalse(mod._segment_payload(seg)["recording"])

    def test_session_row_reads_session_json_and_caches_it(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            session = self._session(root)
            mod = self._module(root)
            entry = {"name": session.name, "path": session, "legacy": False,
                     "pinned": False, "started": 1.0}

            row = mod._session_row(entry)
            self.assertEqual(row["version"], "1.2.3")
            self.assertEqual(row["unit"], "metric")
            self.assertEqual(row["cameras"], ["Left"])
            self.assertEqual(row["frames"], 1)

            # session.json is written once per run, so rewriting it must not
            # change what the row says
            (session / "session.json").write_text(
                json.dumps({"version": "9.9.9"}), encoding="utf-8"
            )
            self.assertEqual(mod._session_row(entry)["version"], "1.2.3")

    def test_a_crashed_segment_still_reports_its_frames(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            session = root / "session_2026-01-01_00-00-00"
            session.mkdir(parents=True)
            (session / "rollback_1.json").write_text(
                '{"cams": ["Left"], "records": [{"i": 1}, {"i": 2}, {"i": 3',
                encoding="utf-8",
            )
            (session / "rollback_1_Left.avi").write_bytes(b"x")
            mod = self._module(root)

            seg = mod._find_segment(
                {"name": session.name, "path": session}, "rollback_1"
            )
            # two whole records recovered; the truncated third is dropped
            self.assertEqual(mod._segment_payload(seg)["frames"], 2)


class CliReplayTests(unittest.TestCase):
    def test_cli_forwards_the_replay_args_it_parses(self):
        # the flags come from the shared add_boot_arguments(); dropping them
        # booted the live camera stack for a replay request
        from iSpy import cli

        with mock.patch.object(cli.boot, "on_boot") as on_boot:
            on_boot.return_value = mock.Mock()
            with mock.patch("iSpy.core.game_loop.main") as run_vision:
                with mock.patch.object(cli.os, "_exit"):
                    cli.main(
                        [
                            "start",
                            "--replay",
                            "some/session",
                            "--replay-cam",
                            "L",
                            "--replay-no-loop",
                        ]
                    )

        kwargs = on_boot.call_args.kwargs
        self.assertEqual(kwargs["replay"], "some/session")
        self.assertEqual(kwargs["replay_cam"], "L")
        self.assertFalse(kwargs["replay_loop"])
        run_vision.assert_called_once_with(config=on_boot.return_value)


if __name__ == "__main__":
    unittest.main()