# DISCLAMER: This file is generated by AI for testing purposes.
import re
import unittest
from pathlib import Path

TEMPLATES = Path(__file__).resolve().parents[1] / "iSpy" / "web" / "templates"
SETTINGS_HTML = (TEMPLATES / "settings.html").read_text()
BASE_HTML = (TEMPLATES / "base.html").read_text()

REMOVED_KEYS = [
    "distance_threshold",
    "stale_threshold",
    "dbscan.epsilon",
    "dbscan.min_samples",
    "record_mode",
    "record_dir",
    "use_network_tables",
    "network_tables_ip",
]


def data_keys(html: str):
    return [
        key
        for key in re.findall(r'data-key="([^"]+)"', html)
        if not key.startswith("${")
    ]


class TestSettingsPageKeys(unittest.TestCase):
    def test_no_removed_keys_as_data_key(self):
        keys = data_keys(SETTINGS_HTML)
        for key in REMOVED_KEYS:
            self.assertNotIn(
                key, keys, f"removed global key {key!r} still a settings field"
            )

    def test_all_settings_fields_are_still_valid_global_keys(self):
        # top-level keys in iSpyConfig.default_config that the page may expose.
        # "optimize" is deliberately absent: it moved to a per-vision-model
        # pipeline setting (_VISION_MODEL_SETTINGS_KEYS), so it's edited per
        # camera, not here.
        valid = {
            "unit",
            "max_fps",
            "frame_sync",
            "metrics",
            "debug_mode",
            "log_level",
            "health_stale_threshold",
        }
        self.assertTrue(
            set(data_keys(SETTINGS_HTML)) <= valid, data_keys(SETTINGS_HTML)
        )

    def test_bool_key_set_no_longer_contains_removed_keys(self):
        for key in ("record_mode", "use_network_tables"):
            self.assertNotIn(f'"{key}"', SETTINGS_HTML)

    def test_addons_page_is_reachable_from_nav(self):
        # the settings page used to carry its own "Manage add-ons from Add-ons"
        # pointer; the sidebar nav in base.html is now the one route there.
        self.assertIn('href="/addons"', BASE_HTML)


if __name__ == "__main__":
    unittest.main()
