# DISCLAMER: This file is generated by AI for testing purposes.
"""Focused tests for the monocular voxel world pipeline.

Covers the sparse voxel store, the Depth-Anything -> world-point geometry, and
the pipeline's output contract, without loading any model weights.
"""

import math
import unittest

import numpy as np

from iSpy.vision import triangulation
from iSpy.vision.pipelines import get_pipeline_classes
from iSpy.vision.pipelines.voxel_world import VoxelWorldPipeline
from iSpy.vision.voxel_map import (
    SparseVoxelMap,
    camera_points_to_robot,
    depth_to_camera_points,
    focal_length_pixels,
    relative_depth_to_distance,
)


class VoxelMapTests(unittest.TestCase):
    def test_integrate_dedups_repeated_hits(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        pts = np.array([[0.05, 0.05, 0.05], [1.0, 0.0, 0.0], [5.0, 5.0, 5.0]])
        self.assertEqual(vmap.integrate(pts), 3)
        # a repeat observation adds hits but no new voxels (0.0 floors into the
        # same 0.1 cube as 0.05)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        self.assertEqual(vmap.count(), 3)
        hits = {tuple(round(c, 2) for c in v[:3]): v[3] for v in vmap.export()}
        self.assertEqual(hits[(0.05, 0.05, 0.05)], 2)

    def test_integrate_drops_non_finite(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        pts = np.array([[0.0, 0.0, 0.0], [np.nan, 1.0, 1.0], [np.inf, 0.0, 0.0]])
        self.assertEqual(vmap.integrate(pts), 1)

    def test_capacity_evicts_least_recent(self):
        vmap = SparseVoxelMap(voxel_size=0.1, max_voxels=2)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]), now=1.0)
        vmap.integrate(np.array([[1.0, 0.0, 0.0]]), now=2.0)
        vmap.integrate(np.array([[2.0, 0.0, 0.0]]), now=3.0)
        self.assertEqual(vmap.count(), 2)
        centers = sorted(round(v[0], 3) for v in vmap.export())
        self.assertAlmostEqual(centers[0], 1.05)
        self.assertAlmostEqual(centers[1], 2.05)

    def test_decay_removes_stale_voxels(self):
        vmap = SparseVoxelMap(voxel_size=0.1, decay_seconds=1.0)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]), now=10.0)
        self.assertEqual(vmap.decay(now=10.5), 0)
        self.assertEqual(vmap.count(), 1)
        self.assertEqual(vmap.decay(now=12.0), 1)
        self.assertEqual(vmap.count(), 0)

    def test_export_sorted_by_hits_and_capped(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        vmap.integrate(np.array([[1.0, 0.0, 0.0], [1.0, 0.0, 0.0]]))
        vmap.integrate(np.array([[2.0, 0.0, 0.0]]))
        exported = vmap.export(max_points=2)
        self.assertEqual(len(exported), 2)
        self.assertAlmostEqual(exported[0][0], 1.05)
        self.assertEqual(exported[0][3], 2)

    def test_export_min_count_filters_noise(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        vmap.integrate(np.array([[1.0, 0.0, 0.0], [1.0, 0.0, 0.0]]))
        exported = vmap.export(min_count=2)
        self.assertEqual(len(exported), 1)
        self.assertAlmostEqual(exported[0][0], 1.05)


class GeometryTests(unittest.TestCase):
    def test_vectorized_transform_matches_scalar(self):
        pts = np.array([[0.1, 0.2, 3.0], [1.0, -0.5, 5.0], [-0.3, 0.0, 2.0]])
        batch = camera_points_to_robot(pts, 10.0, 20.0, 30.0, 15.0, -10.0)
        for i, point in enumerate(pts):
            scalar = triangulation.camera_point_to_robot(
                tuple(point), 10.0, 20.0, 30.0, 15.0, -10.0
            )
            np.testing.assert_allclose(batch[i], scalar, rtol=1e-12)

    def test_depth_to_camera_points_filters_invalid(self):
        depth = np.array(
            [
                [0.0, np.nan, 2.0],
                [np.inf, 1.0, 3.0],
            ],
            dtype=np.float64,
        )
        pts = depth_to_camera_points(depth, focal_px=100.0, stride=1)
        self.assertEqual(pts.shape[1], 3)
        self.assertTrue(np.isfinite(pts).all())
        self.assertTrue((pts[:, 2] > 0).all())
        self.assertEqual(len(pts), 3)

    def test_center_pixel_backprojects_to_optical_axis(self):
        depth = np.full((40, 40), 5.0, dtype=np.float64)
        pts = depth_to_camera_points(depth, focal_px=200.0, stride=1)
        center = pts[np.argmin(np.abs(pts[:, 0]) + np.abs(pts[:, 1]))]
        self.assertAlmostEqual(center[0], 0.0, places=6)
        self.assertAlmostEqual(center[1], 0.0, places=6)
        self.assertAlmostEqual(center[2], 5.0, places=6)

    def test_nearer_relative_depth_maps_to_smaller_distance(self):
        depth = np.array([[0.0, 1.0]], dtype=np.float64)
        dist = relative_depth_to_distance(depth, 0.0, 1.0, 10.0)
        # higher relative depth = nearer = smaller distance
        self.assertLess(dist[0, 1], dist[0, 0])
        self.assertAlmostEqual(dist[0, 1], 0.0)
        self.assertAlmostEqual(dist[0, 0], 10.0)

    def test_flat_depth_map_does_not_divide_by_zero(self):
        depth = np.full((10, 10), 4.0, dtype=np.float64)
        dist = relative_depth_to_distance(depth, 4.0, 4.0, 10.0)
        self.assertTrue(np.isfinite(dist).all())

    def test_focal_length_prefers_fov_then_defaults(self):
        fov_focal = focal_length_pixels(640, {"fov": 60.0})
        self.assertAlmostEqual(fov_focal, 320.0 / math.tan(math.radians(30.0)))
        default = focal_length_pixels(640, {})
        self.assertAlmostEqual(default, 320.0 / math.tan(math.radians(30.0)))

    def test_focal_length_scales_camera_matrix_by_resolution(self):
        focal = focal_length_pixels(
            1280,
            {"camera_matrix": [[500.0, 0, 0], [0, 500.0, 0], [0, 0, 1]], "resolution": [640, 480]},
        )
        self.assertAlmostEqual(focal, 1000.0)


class VoxelWorldPipelineTests(unittest.TestCase):
    def test_pipeline_is_registered(self):
        self.assertIn("voxel_world", get_pipeline_classes())

    def test_schema_exposes_voxel_settings(self):
        schema = VoxelWorldPipeline.config_schema()
        for key in (
            "voxel_size",
            "pixel_stride",
            "max_voxels",
            "export_max_voxels",
            "min_voxel_count",
            "decay_seconds",
            "depth_scale",
            "min_height",
            "voxel_min_depth",
        ):
            self.assertIn(key, schema)
            self.assertIn(schema[key]["type"], ("number", "toggle", "select"))
        # depth-anything settings are inherited
        self.assertIn("max_depth", schema)
        self.assertIn("process_every", schema)

    @staticmethod
    def _build_pipeline():
        pipeline = VoxelWorldPipeline.__new__(VoxelWorldPipeline)
        pipeline.logger = None
        pipeline._frame_count = 0
        pipeline._every = 1
        pipeline._last_depth = None
        pipeline._last_objects = []
        pipeline.max_depth = 10.0
        pipeline._z_scale = 1.0
        pipeline.depth_scale = 1.0
        pipeline.pixel_stride = 4
        pipeline.voxel_min_depth = 0.0
        pipeline.min_height = -100.0
        pipeline.voxel_size = 0.1
        pipeline.export_max_voxels = 1000
        pipeline.min_voxel_count = 1
        pipeline.unit = "frc"
        pipeline._unit_label = "m"
        pipeline.camera_x = 0.0
        pipeline.camera_y = 0.0
        pipeline.camera_height = 36.0 * 0.0254
        pipeline.camera_yaw = 0.0
        pipeline.camera_pitch = 10.0
        pipeline.calibration = {"fov": 60.0}
        pipeline.voxel_map = SparseVoxelMap(voxel_size=0.1, decay_seconds=0.0)
        return pipeline

    def test_run_emits_single_voxel_object(self):
        pipeline = self._build_pipeline()
        frame = np.zeros((80, 80, 3), dtype=np.uint8)

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        objects, out_frame = pipeline.run()
        self.assertEqual(len(objects), 1)
        obj = objects[0]
        self.assertEqual(obj.vis_type, "voxels")
        meta = obj.vis_meta
        self.assertEqual(meta["kind"], "voxel_map")
        self.assertGreater(meta["count"], 0)
        self.assertTrue(meta["voxels"])
        for voxel in meta["voxels"]:
            self.assertEqual(len(voxel), 4)
            self.assertTrue(all(math.isfinite(v) for v in voxel[:3]))
        self.assertIsNotNone(out_frame)

    def test_run_reuses_depth_between_inference_frames(self):
        pipeline = self._build_pipeline()
        pipeline._every = 5
        frame = np.zeros((80, 80, 3), dtype=np.uint8)
        calls = {"n": 0}

        def fake_depth(f):
            calls["n"] += 1
            return np.tile(
                np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)[:, None],
                (1, f.shape[1]),
            )

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        pipeline.run()
        first_count = pipeline.voxel_map.count()
        pipeline.run()
        self.assertEqual(calls["n"], 1)
        self.assertEqual(pipeline.voxel_map.count(), first_count)

    def test_run_without_model_returns_raw_frame(self):
        pipeline = self._build_pipeline()
        frame = np.full((20, 20, 3), 7, dtype=np.uint8)
        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: False

        objects, out_frame = pipeline.run()
        self.assertEqual(objects, [])
        self.assertTrue(np.array_equal(out_frame, frame))


if __name__ == "__main__":
    unittest.main()
