# DISCLAMER: This file is generated by AI for testing purposes.
"""Focused tests for the monocular voxel world pipeline.

Covers the sparse voxel store, the Depth-Anything -> world-point geometry, and
the pipeline's output contract, without loading any model weights.
"""

import math
import unittest

import numpy as np

from iSpy.vision import triangulation
from iSpy.vision.pipelines import get_pipeline_classes
from iSpy.vision.pipelines.voxel_world import VoxelWorldPipeline
from iSpy.vision.voxel_map import (
    SparseVoxelMap,
    camera_points_to_robot,
    depth_plane_range,
    depth_to_camera_points,
    focal_length_pixels,
    relative_depth_to_distance,
)


class VoxelMapTests(unittest.TestCase):
    def test_integrate_dedups_repeated_hits(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        pts = np.array([[0.05, 0.05, 0.05], [1.0, 0.0, 0.0], [5.0, 5.0, 5.0]])
        self.assertEqual(vmap.integrate(pts), 3)
        # a repeat observation adds hits but no new voxels (0.0 floors into the
        # same 0.1 cube as 0.05)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        self.assertEqual(vmap.count(), 3)
        hits = {tuple(round(c, 2) for c in v[:3]): v[3] for v in vmap.export()}
        self.assertEqual(hits[(0.05, 0.05, 0.05)], 2)

    def test_integrate_drops_non_finite(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        pts = np.array([[0.0, 0.0, 0.0], [np.nan, 1.0, 1.0], [np.inf, 0.0, 0.0]])
        self.assertEqual(vmap.integrate(pts), 1)

    def test_capacity_evicts_least_recent(self):
        vmap = SparseVoxelMap(voxel_size=0.1, max_voxels=2)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]), now=1.0)
        vmap.integrate(np.array([[1.0, 0.0, 0.0]]), now=2.0)
        vmap.integrate(np.array([[2.0, 0.0, 0.0]]), now=3.0)
        self.assertEqual(vmap.count(), 2)
        centers = sorted(round(v[0], 3) for v in vmap.export())
        self.assertAlmostEqual(centers[0], 1.05)
        self.assertAlmostEqual(centers[1], 2.05)

    def test_decay_removes_stale_voxels(self):
        vmap = SparseVoxelMap(voxel_size=0.1, decay_seconds=1.0)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]), now=10.0)
        self.assertEqual(vmap.decay(now=10.5), 0)
        self.assertEqual(vmap.count(), 1)
        self.assertEqual(vmap.decay(now=12.0), 1)
        self.assertEqual(vmap.count(), 0)

    def test_export_sorted_by_hits_and_capped(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        vmap.integrate(np.array([[1.0, 0.0, 0.0], [1.0, 0.0, 0.0]]))
        vmap.integrate(np.array([[2.0, 0.0, 0.0]]))
        exported = vmap.export(max_points=2)
        self.assertEqual(len(exported), 2)
        self.assertAlmostEqual(exported[0][0], 1.05)
        self.assertEqual(exported[0][3], 2)

    def test_export_min_count_filters_noise(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        vmap.integrate(np.array([[1.0, 0.0, 0.0], [1.0, 0.0, 0.0]]))
        exported = vmap.export(min_count=2)
        self.assertEqual(len(exported), 1)
        self.assertAlmostEqual(exported[0][0], 1.05)

    def test_integrate_averages_color_per_voxel(self):
        # two red-ish and one blue point in the same cell -> weighted average
        vmap = SparseVoxelMap(voxel_size=0.5)
        pts = np.array([[0.05, 0.05, 0.05], [0.10, 0.10, 0.10]])
        vmap.integrate(pts, colors=np.array([[200, 0, 0], [200, 0, 0]]))
        vmap.integrate(np.array([[0.20, 0.20, 0.20]]), colors=np.array([[0, 0, 100]]))
        exported = vmap.export()
        self.assertEqual(len(exported[0]), 7)
        r, g, b = exported[0][4:7]
        self.assertAlmostEqual(r, (200 * 2 + 0) / 3, delta=1)
        self.assertEqual(g, 0)
        self.assertAlmostEqual(b, (0 * 2 + 100) / 3, delta=1)

    def test_export_defaults_uncolored_voxels_to_grey(self):
        vmap = SparseVoxelMap(voxel_size=0.1)
        vmap.integrate(np.array([[0.0, 0.0, 0.0]]))
        exported = vmap.export()
        self.assertEqual(exported[0][4:7], [170, 170, 170])


class GeometryTests(unittest.TestCase):
    def test_vectorized_transform_matches_scalar(self):
        pts = np.array([[0.1, 0.2, 3.0], [1.0, -0.5, 5.0], [-0.3, 0.0, 2.0]])
        batch = camera_points_to_robot(pts, 10.0, 20.0, 30.0, 15.0, -10.0)
        for i, point in enumerate(pts):
            scalar = triangulation.camera_point_to_robot(
                tuple(point), 10.0, 20.0, 30.0, 15.0, -10.0
            )
            np.testing.assert_allclose(batch[i], scalar, rtol=1e-12)

    def test_depth_to_camera_points_filters_invalid(self):
        depth = np.array(
            [
                [0.0, np.nan, 2.0],
                [np.inf, 1.0, 3.0],
            ],
            dtype=np.float64,
        )
        pts = depth_to_camera_points(depth, focal_px=100.0, stride=1)
        self.assertEqual(pts.shape[1], 3)
        self.assertTrue(np.isfinite(pts).all())
        self.assertTrue((pts[:, 2] > 0).all())
        self.assertEqual(len(pts), 3)

    def test_center_pixel_backprojects_to_optical_axis(self):
        depth = np.full((40, 40), 5.0, dtype=np.float64)
        pts = depth_to_camera_points(depth, focal_px=200.0, stride=1)
        center = pts[np.argmin(np.abs(pts[:, 0]) + np.abs(pts[:, 1]))]
        self.assertAlmostEqual(center[0], 0.0, places=6)
        self.assertAlmostEqual(center[1], 0.0, places=6)
        self.assertAlmostEqual(center[2], 5.0, places=6)

    def test_nearer_relative_depth_maps_to_smaller_distance(self):
        depth = np.array([[0.0, 1.0]], dtype=np.float64)
        dist = relative_depth_to_distance(depth, 0.0, 1.0, 10.0, near_depth=0.5)
        # higher relative depth = nearer = smaller distance
        self.assertLess(dist[0, 1], dist[0, 0])
        self.assertAlmostEqual(dist[0, 1], 0.5)  # near plane
        self.assertAlmostEqual(dist[0, 0], 10.0)  # far plane

    def test_inverse_depth_recovers_perspective_not_linear_ramp(self):
        # A disparity (1/z) map for z in 1..10 m must stay ratio-preserving
        # (near:far ~ 1:9) and monotonic, not pile onto the far plane.
        z_true = np.linspace(1.0, 10.0, 400).reshape(1, -1)
        relative = 1.0 / z_true
        dist = relative_depth_to_distance(relative, relative.min(), relative.max(), 10.0, near_depth=0.5)
        self.assertLess(dist.max(), 10.5)
        self.assertGreaterEqual(dist.min(), 0.45)
        self.assertGreater(dist.max() / dist.min(), 5.0)
        # nearer stays nearer (the ends are flat because of percentile clipping)
        self.assertTrue(np.all(np.diff(dist[0]) >= -1e-9))

    def test_depth_plane_range_preserves_scene_ratio(self):
        # self-scaling: the far plane follows the disparity ratio, not Max Depth
        depth = np.linspace(0.2, 0.8, 500)
        d_lo, d_hi, z_near, z_far = depth_plane_range(
            depth, depth.min(), depth.max(), 10.0, near_depth=1.0
        )
        self.assertAlmostEqual(z_near, 1.0, places=6)
        self.assertAlmostEqual(z_far / z_near, d_hi / d_lo, places=6)
        # Max Depth stays a cap when the scene ratio is huge
        _, _, _, capped = depth_plane_range(
            np.array([0.001, 1.0]), 0.001, 1.0, 4.0, near_depth=1.0
        )
        self.assertAlmostEqual(capped, 4.0, places=6)

    def test_flat_depth_map_does_not_divide_by_zero(self):
        depth = np.full((10, 10), 4.0, dtype=np.float64)
        dist = relative_depth_to_distance(depth, 4.0, 4.0, 10.0)
        self.assertTrue(np.isfinite(dist).all())

    def test_room_depth_map_builds_meter_scale_world(self):
        # A 2-5 m room, expressed as DAV2 relative inverse depth. With the near
        # plane anchored at the true nearest distance (2 m) the self-scaling
        # inverse model recovers a ~2-5 m world - not the sub-30cm blob of a
        # collapsed scale and not the 10 m funnel of a forced near..max stretch.
        z_true = np.linspace(2.0, 5.0, 64).reshape(1, -1)
        relative = np.repeat(1.0 / z_true, 48, axis=0)
        dist = relative_depth_to_distance(
            relative, relative.min(), relative.max(), 10.0, near_depth=2.0
        )
        self.assertAlmostEqual(float(dist.min()), 2.0, places=2)
        self.assertAlmostEqual(float(dist.max()), 5.0, delta=0.6)
        cam = depth_to_camera_points(dist, focal_px=200.0, stride=1)
        world = camera_points_to_robot(cam, 0.0, 0.0, 1.0, 0.0, 0.0)
        world = world[world[:, 2] >= -25.0]
        extent = world.max(axis=0) - world.min(axis=0)
        self.assertGreater(extent[1], 1.0)  # forward axis spans > 1 m
        self.assertGreater(world[:, 1].max(), 4.0)  # reaches the room's far wall

    def test_focal_length_prefers_fov_then_defaults(self):
        fov_focal = focal_length_pixels(640, {"fov": 60.0})
        self.assertAlmostEqual(fov_focal, 320.0 / math.tan(math.radians(30.0)))
        default = focal_length_pixels(640, {})
        self.assertAlmostEqual(default, 320.0 / math.tan(math.radians(30.0)))

    def test_focal_length_scales_camera_matrix_by_resolution(self):
        focal = focal_length_pixels(
            1280,
            {"camera_matrix": [[500.0, 0, 0], [0, 500.0, 0], [0, 0, 1]], "resolution": [640, 480]},
        )
        self.assertAlmostEqual(focal, 1000.0)


class VoxelWorldPipelineTests(unittest.TestCase):
    def test_pipeline_is_registered(self):
        self.assertIn("voxel_world", get_pipeline_classes())

    def test_schema_exposes_voxel_settings(self):
        schema = VoxelWorldPipeline.config_schema()
        for key in (
            "voxel_size",
            "pixel_stride",
            "max_voxels",
            "export_max_voxels",
            "min_voxel_count",
            "decay_seconds",
            "depth_scale",
            "min_height",
            "voxel_min_depth",
            "near_depth",
            "auto_ground",
            "auto_world_scale",
        ):
            self.assertIn(key, schema)
            self.assertIn(schema[key]["type"], ("number", "toggle", "select"))
        # depth-anything settings are inherited
        self.assertIn("max_depth", schema)
        self.assertIn("process_every", schema)

    @staticmethod
    def _build_pipeline():
        pipeline = VoxelWorldPipeline.__new__(VoxelWorldPipeline)
        pipeline.logger = None
        pipeline._frame_count = 0
        pipeline._every = 1
        pipeline._last_depth = None
        pipeline._last_objects = []
        pipeline.max_depth = 10.0
        pipeline._z_scale = 1.0
        pipeline.depth_scale = 1.0
        pipeline.near_depth = 0.3
        pipeline.pixel_stride = 4
        pipeline.voxel_min_depth = 0.0
        pipeline.min_height = -100.0
        pipeline.auto_ground = True
        pipeline.auto_world_scale = True
        pipeline.debug_viz = False
        pipeline._ground_offset = None
        pipeline.voxel_size = 0.1
        pipeline.export_max_voxels = 1000
        pipeline.min_voxel_count = 1
        pipeline.unit = "frc"
        pipeline._unit_label = "m"
        pipeline.camera_x = 0.0
        pipeline.camera_y = 0.0
        pipeline.camera_height = 36.0 * 0.0254
        pipeline.camera_yaw = 0.0
        pipeline.camera_pitch = 10.0
        pipeline.calibration = {"fov": 60.0}
        pipeline.voxel_map = SparseVoxelMap(voxel_size=0.1, decay_seconds=0.0)
        return pipeline

    def test_run_emits_single_voxel_object(self):
        pipeline = self._build_pipeline()
        frame = np.zeros((80, 80, 3), dtype=np.uint8)

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        objects, out_frame = pipeline.run()
        self.assertEqual(len(objects), 1)
        obj = objects[0]
        self.assertEqual(obj.vis_type, "voxels")
        meta = obj.vis_meta
        self.assertEqual(meta["kind"], "voxel_map")
        self.assertGreater(meta["count"], 0)
        self.assertTrue(meta["voxels"])
        for voxel in meta["voxels"]:
            self.assertEqual(len(voxel), 7)
            self.assertTrue(all(math.isfinite(v) for v in voxel[:3]))
            self.assertTrue(all(0 <= c <= 255 for c in voxel[4:7]))
        self.assertIsNotNone(out_frame)

    def test_voxel_color_is_sampled_from_the_frame(self):
        # a solid red frame (BGR) must produce red voxels
        pipeline = self._build_pipeline()
        frame = np.zeros((80, 80, 3), dtype=np.uint8)
        frame[:, :, 2] = 255  # red in BGR

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        objects, _ = pipeline.run()
        voxels = objects[0].vis_meta["voxels"]
        self.assertTrue(voxels)
        for v in voxels:
            self.assertGreater(v[4], 200)  # red
            self.assertLess(v[5], 20)
            self.assertLess(v[6], 20)

    def test_voxel_object_reuses_instance_and_resets_pose(self):
        # the voxel world recycles ONE Object so its identity (and the viewer's
        # render group keyed by o.id) stays stable across ticks
        pipeline = self._build_pipeline()
        obj_a = pipeline._voxel_object()
        self.assertEqual(obj_a.name, "voxel_world")
        self.assertEqual(obj_a.vis_type, "voxels")
        obj_b = pipeline._voxel_object()
        self.assertIs(obj_a, obj_b)
        self.assertEqual(obj_a.get_id(), obj_b.get_id())
        # simulate a tracker converting the shared instance in place, then
        # verify the pipeline re-anchors it every tick so roll/pitch/yaw never
        # accumulate a robot_yaw (they would feed a bogus pose to the viewer)
        obj_a.roll = 0.3
        obj_a.pitch = 0.1
        obj_a.yaw = 1.2
        pipeline._voxel_object()
        self.assertEqual(obj_a.roll, 0.0)
        self.assertEqual(obj_a.pitch, 0.0)
        self.assertEqual(obj_a.yaw, 0.0)

    def test_auto_ground_lifts_a_scene_below_the_origin(self):
        # A straight-down camera (pitch 90) with height 0 maps every point
        # below z=0. Auto ground must shift the map so it straddles the grid
        # instead of hanging entirely underneath it.
        pipeline = self._build_pipeline()
        pipeline.camera_height = 0.0
        pipeline.camera_pitch = 90.0
        pipeline.min_height = -100.0
        pipeline.auto_ground = True
        pipeline._ground_offset = None
        frame = np.zeros((80, 80, 3), dtype=np.uint8)

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        objects, _ = pipeline.run()
        meta = objects[0].vis_meta
        self.assertIsNotNone(pipeline._ground_offset)
        self.assertNotAlmostEqual(meta["debug"]["world_z_max"], meta["debug"]["world_z_min"])
        # after centering, the densest plane sits at z~0, so the max is >= 0
        self.assertGreaterEqual(meta["debug"]["world_z_max"], 0.0)

    def test_min_height_never_blanks_the_world(self):
        # A floor clip above the whole reconstruction (a camera height/pitch
        # that does not match the world origin) must not silently delete the
        # map - the clip is skipped and surfaced as a warning instead.
        pipeline = self._build_pipeline()
        pipeline.min_height = 100.0
        frame = np.zeros((80, 80, 3), dtype=np.uint8)

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        objects, _ = pipeline.run()
        self.assertEqual(len(objects), 1)
        meta = objects[0].vis_meta
        self.assertGreater(meta["count"], 0)
        self.assertEqual(meta["debug"]["past_min_height"], 0)
        self.assertIn("Min Height", meta["debug"].get("warning", ""))

        # a second tick must not append the same warning again - the viewer
        # used to show one giant repeating string
        objects, _ = pipeline.run()
        warning = objects[0].vis_meta["debug"].get("warning", "")
        self.assertEqual(warning.count("removed every point"), 1)

    def test_run_reuses_depth_between_inference_frames(self):
        pipeline = self._build_pipeline()
        pipeline._every = 5
        frame = np.zeros((80, 80, 3), dtype=np.uint8)
        calls = {"n": 0}

        def fake_depth(f):
            calls["n"] += 1
            return np.tile(
                np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)[:, None],
                (1, f.shape[1]),
            )

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        pipeline.run()
        first_count = pipeline.voxel_map.count()
        pipeline.run()
        self.assertEqual(calls["n"], 1)
        self.assertEqual(pipeline.voxel_map.count(), first_count)

    def test_decay_only_runs_on_integration_frames(self):
        # A voxel is only ever re-observed on a refresh (integration) frame.
        # decay_seconds smaller than the frame time (0.1 s decay on a slow Pi)
        # used to empty the whole map on the intermediate frame - before any
        # cell could be re-observed. Decay must be aligned to that cadence.
        pipeline = self._build_pipeline()
        pipeline._every = 2
        pipeline.decay_seconds = 0.1
        pipeline.voxel_map = SparseVoxelMap(voxel_size=0.1, decay_seconds=0.1)
        frame = np.zeros((80, 80, 3), dtype=np.uint8)

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        decay_calls = []
        original_decay = pipeline.voxel_map.decay
        pipeline.voxel_map.decay = lambda: (decay_calls.append(1) or original_decay())

        objects, _ = pipeline.run()  # frame 1: first frame -> integrate + decay
        self.assertEqual(len(decay_calls), 1)
        objects, _ = pipeline.run()  # frame 2: refresh -> integrate + decay
        self.assertEqual(len(decay_calls), 2)
        objects, _ = pipeline.run()  # frame 3: no refresh -> NO decay, map intact
        self.assertEqual(len(decay_calls), 2)
        self.assertGreater(objects[0].vis_meta["count"], 0)
        objects, _ = pipeline.run()  # frame 4: refresh -> integrate + decay again
        self.assertEqual(len(decay_calls), 3)
        self.assertGreater(objects[0].vis_meta["count"], 0)

    def test_debug_viz_ships_intermediate_geometry(self):
        # debug_viz must put the raw camera-frame cloud, the settled world
        # cloud, the camera frustum, and the mount markers in vis_meta so the
        # 3D viewer can overlay them on the voxels for geometry/visual tests.
        pipeline = self._build_pipeline()
        pipeline.debug_viz = True
        pipeline.camera_pitch = 10.0
        frame = np.zeros((80, 80, 3), dtype=np.uint8)
        frame[:, :, 2] = 120
        frame[:, :, 0] = 200

        def fake_depth(f):
            rows = np.linspace(1.0, 0.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f

        objects, _ = pipeline.run()
        viz = objects[0].vis_meta.get("debug_viz")
        self.assertIsNotNone(viz)
        self.assertGreater(len(viz["raw"]), 0)
        self.assertEqual(len(viz["raw"]), len(viz["world"]))
        for key in ("near", "far", "cam_origin", "axes_origin", "unit", "frustum"):
            self.assertIn(key, viz)
        self.assertEqual(len(viz["frustum"]), 8)  # near rect + far rect corners
        if viz["colors"]:
            self.assertEqual(len(viz["colors"]), len(viz["world"]))
        # every raw point is forward-positive in camera frame (right/down/fwd)
        self.assertTrue(all(p[2] > 0 for p in viz["raw"][:8]))
        # the scalar debug row must not balloon with the arrays
        self.assertNotIn("viz", objects[0].vis_meta["debug"])

    def test_run_without_model_returns_raw_frame(self):
        pipeline = self._build_pipeline()
        frame = np.full((20, 20, 3), 7, dtype=np.uint8)
        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: False

        objects, out_frame = pipeline.run()
        self.assertEqual(objects, [])
        self.assertTrue(np.array_equal(out_frame, frame))

    def test_auto_world_scale_stretches_a_small_scene(self):
        # A 1.5 m person in front of a 5 m wall has a disparity ratio of ~3.3.
        # Anchored at the 0.3 m default near plane that collapses the whole
        # world to a sub-metre blob; Auto Scale World must stretch it out so
        # it fills the 10 m cap and the object geometry stays recognizable.
        pipeline = self._build_pipeline()
        frame = np.zeros((80, 80, 3), dtype=np.uint8)
        depth = np.full((80, 80), 5.0)
        depth[25:65, 20:60] = 1.5
        relative = 1.0 / depth

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = lambda f: relative
        pipeline._annotate = lambda f, d: f

        objects, _ = pipeline.run()
        dbg = objects[0].vis_meta["debug"]
        self.assertTrue(dbg["auto_scale"])
        self.assertAlmostEqual(dbg["dist_max"], 10.0, delta=0.1)

        # turning it off keeps the old, collapsed behaviour
        pipeline.auto_world_scale = False
        objects, _ = pipeline.run()
        dbg = objects[0].vis_meta["debug"]
        self.assertFalse(dbg["auto_scale"])
        self.assertLess(dbg["dist_max"], 1.1)

    def test_shadows_method_needs_no_model(self):
        # 'shadows' is a pure heuristic - no optimization, always ready, and
        # the depth map is synthesized on the fly so no inference backend
        # exists.
        pipeline = self._build_pipeline()
        pipeline.depth_method = "shadows"
        frame = np.zeros((80, 80, 3), dtype=np.uint8)
        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._annotate = lambda f, d: f

        self.assertFalse(pipeline._optimization_requested())
        self.assertEqual(pipeline.is_ready(), (True, "ready"))

        objects, _ = pipeline.run()
        meta = objects[0].vis_meta
        self.assertEqual(meta["model"]["method"], "shadows")
        self.assertEqual(meta["model"]["backend"], "synthetic")
        self.assertGreater(meta["count"], 0)
        self.assertTrue(meta["voxels"])

    def test_shadows_estimator_maps_bright_to_near_and_dark_to_far(self):
        # HSV value is read as inverse depth: lit pixels keep a high relative
        # depth (near) and shadowed pixels drop (far) - same convention as
        # Depth Anything, so the rest of the pipeline is method-blind.
        pipeline = self._build_pipeline()
        frame = np.zeros((40, 40, 3), dtype=np.uint8)
        frame[:, :, :] = (40, 40, 40)  # left half = shadow, dark -> far
        frame[:, 20:, :] = (220, 220, 220)  # right half = lit, bright -> near
        depth = pipeline._estimate_shadows(frame)
        self.assertEqual(depth.shape, frame.shape[:2])
        self.assertTrue(np.isfinite(depth).all())
        self.assertGreater(float(depth[:, 20:].mean()), float(depth[:, :20].mean()))

    def test_schema_offers_only_depth_anything_and_shadows(self):
        schema = VoxelWorldPipeline.config_schema()
        self.assertEqual(schema["depth_method"]["options"], ["depth_anything", "shadows"])

    # ------------------------------------------------------------------
    # mount geometry: the whole point of "not correct" debugging. A
    # level, real-height camera must reconstruct the world as a shallow
    # floor band stretching FORWARD (+Y), while the Pi's pitch=90/height=0
    # combination provably collapses the whole depth range into a
    # vertical smear below the robot (world_z extent >> forward extent).
    # These tests pin that behaviour so the geometry cannot silently
    # regress.
    # ------------------------------------------------------------------

    @staticmethod
    def _run_mount(pitch, height, yaw=0.0):
        pipeline = VoxelWorldPipelineTests._build_pipeline()
        pipeline.camera_pitch = pitch
        pipeline.camera_height = height
        pipeline.camera_yaw = yaw
        pipeline.debug_viz = True
        frame = np.zeros((80, 80, 3), dtype=np.uint8)

        # row ramp: top row = far (low inverse depth), bottom = near
        def fake_depth(f):
            rows = np.linspace(0.1, 1.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f
        objects, _ = pipeline.run()
        return objects[0].vis_meta, pipeline

    @staticmethod
    def _corr(a, b):
        """Pearson correlation; the mount-transform semantics being tested were
        scene-robust correlations, not absolute ranges."""
        a = np.asarray(a, dtype=np.float64)
        b = np.asarray(b, dtype=np.float64)
        if a.size != b.size or a.size < 2:
            return 0.0
        am = a - a.mean()
        bm = b - b.mean()
        den = float(np.sqrt(float((am ** 2).sum()) * float((bm ** 2).sum())))
        if den == 0.0:
            return 0.0
        return float((am * bm).sum() / den)

    def test_level_camera_distance_flows_forward_not_down(self):
        # Camera 0.3 m up, level (pitch 0): forward camera distance must ride
        # robot +Y (forward). Check it two ways - the back-projected cloud's
        # distance correlates with +Y, and the debug frustum points +Y instead
        # of straight down.
        meta, pipeline = self._run_mount(pitch=0.0, height=0.3)
        viz = meta["debug_viz"]
        raw_d = [p[2] for p in viz["raw"]]
        self.assertGreater(self._corr([p[1] for p in viz["world"]], raw_d), 0.85)
        # forward axis of the mount must be ~horizontal (+Y)
        dx, dy, dz = self._frustum_forward(viz)
        self.assertGreater(dy, 0.9)
        self.assertLess(abs(dz), 0.35)
        self.assertGreater(len(meta["voxels"]), 0)

    @staticmethod
    def _frustum_forward(viz):
        """Normalized direction from cam_origin to the far-rectangle centroid,
        i.e. where the configured mount says 'forward' is."""
        o = viz["cam_origin"]
        far = np.asarray(viz["frustum"][4:], dtype=np.float64)
        c = far.mean(axis=0)
        d = c - np.asarray(o, dtype=np.float64)
        n = float(np.linalg.norm(d))
        if n == 0:
            return 0.0, 0.0, 0.0
        return float(d[0] / n), float(d[1] / n), float(d[2] / n)

    def test_pitch_90_height_0_produces_the_documented_vertical_smear(self):
        # The Pi config (pitch 90, height 0, yaw 90): forward camera distance
        # rides robot -Z (straight DOWN), so the entire depth range becomes a
        # vertical column under the robot instead of distance - the "terrible
        # and not correct" look from the log. Pin it so nobody "fixes" the
        # transform into a different bug.
        meta, pipeline = self._run_mount(pitch=90.0, height=0.0, yaw=90.0)
        viz = meta["debug_viz"]
        raw_d = [p[2] for p in viz["raw"]]
        self.assertLess(self._corr([p[2] for p in viz["world"]], raw_d), -0.85)
        self.assertLess(abs(self._corr([p[1] for p in viz["world"]], raw_d)), 0.5)
        # the mount's forward axis must point straight DOWN
        dx, dy, dz = self._frustum_forward(viz)
        self.assertLess(dz, -0.9)
        self.assertLess(abs(dy), 0.3)
        voxels = np.asarray([v[:3] for v in meta["voxels"]])
        self.assertGreater(voxels.shape[0], 0)
        # height extent is comparable to forward extent - the smear
        z_range = float(voxels[:, 2].max() - voxels[:, 2].min())
        y_range = float(voxels[:, 1].max() - voxels[:, 1].min())
        self.assertGreater(z_range, 2.0)
        self.assertGreaterEqual(z_range, 0.6 * y_range)

    def test_debug_frustum_rotates_with_the_mount(self):
        # The debug frustum must be transformed with the same camera->robot
        # matrix as the voxels, so checking it in the viewer is honest.
        pipeline = self._build_pipeline()
        pipeline.debug_viz = True
        pipeline.camera_pitch = 20.0
        pipeline.camera_height = 0.25
        frame = np.zeros((64, 64, 3), dtype=np.uint8)

        def fake_depth(f):
            rows = np.linspace(0.1, 1.0, f.shape[0], dtype=np.float64)
            return np.tile(rows[:, None], (1, f.shape[1]))

        pipeline.get_frame = lambda: frame
        pipeline._is_processable = lambda: True
        pipeline._infer_depth = fake_depth
        pipeline._annotate = lambda f, d: f
        objects, _ = pipeline.run()
        viz = objects[0].vis_meta["debug_viz"]

        # pitch 20 tilts the view volume up from level: far-top corner must be
        # the highest point and still ahead of the camera in +Y
        far = viz["frustum"][4:]
        self.assertTrue(all(c[1] > 0 for c in far))
        self.assertGreater(max(c[2] for c in far), min(c[2] for c in far))
        near = viz["frustum"][:4]
        # near plane is closer than the far plane along +Y
        self.assertLess(max(c[1] for c in near), min(c[1] for c in far))
        self.assertIn("axes_origin", viz)
        self.assertIn("cam_origin", viz)


if __name__ == "__main__":
    unittest.main()
