# DISCLAMER: This file is generated by AI for testing purposes.
import json
import shutil
import tempfile
import time
import unittest
from pathlib import Path
from unittest import mock

import numpy as np

from iSpy.config.iSpyConfig import iSpyAddonConfig, iSpyConfig
from iSpy.core.rollback import RollBack
from iSpy.plugins._loader import load_plugins
from iSpy.plugins.bases import (
    AddonBase,
    FrameProcessorBase,
    TrackerBase,
    UtilityBase,
)
from iSpy.vision.Object import Object

PLUGIN_ROOT = Path(__file__).resolve().parents[1] / "iSpy" / "plugins"

BARE_CONTEXT = {
    "config": iSpyAddonConfig({}),
    "global_config": None,
    "cameras": [],
    "flask_app": None,
    "vision_instance": None,
}


def addon_context(cls, settings: dict | None = None, vision=None) -> dict:
    ctx = dict(BARE_CONTEXT)
    ctx["config"] = iSpyAddonConfig(settings or {}, defaults=cls.default_settings())
    ctx["vision_instance"] = vision
    return ctx


class AddonDiscoveryTests(unittest.TestCase):
    def test_all_builtin_addons_are_discovered(self):
        trackers = load_plugins(PLUGIN_ROOT / "trackers", TrackerBase)
        utilities = load_plugins(PLUGIN_ROOT / "utilities", UtilityBase)
        fps = load_plugins(PLUGIN_ROOT / "frame_processors", FrameProcessorBase)
        self.assertTrue({"FRC/object_tracker", "path_planner"} <= set(trackers))
        self.assertIn("FRC/network_table_handler", utilities)
        # RollBack is core code now (iSpy/core/rollback.py), not an add-on -
        # add-on discovery must not turn it up
        self.assertNotIn("rollback", utilities)
        self.assertIn("example/example_frame_processor", fps)
        self.assertIn("example/example_tracker", trackers)
        self.assertIn("example/example_utility", utilities)

    def test_every_addon_is_an_addonbase_subclass(self):
        for subdir, base in (
            ("trackers", TrackerBase),
            ("utilities", UtilityBase),
            ("frame_processors", FrameProcessorBase),
        ):
            for name, cls in load_plugins(PLUGIN_ROOT / subdir, base).items():
                self.assertTrue(issubclass(cls, AddonBase), name)

    def test_addon_schemas_are_valid(self):
        valid_types = {"text", "number", "toggle", "list"}
        for subdir, base in (
            ("trackers", TrackerBase),
            ("utilities", UtilityBase),
            ("frame_processors", FrameProcessorBase),
        ):
            for name, cls in load_plugins(PLUGIN_ROOT / subdir, base).items():
                schema = cls.config_schema()
                self.assertIsInstance(schema, dict, name)
                for key, defn in schema.items():
                    self.assertIsInstance(defn, dict, f"{name}.{key}")
                    self.assertIn("type", defn, f"{name}.{key}")
                    self.assertIn(defn["type"], valid_types, f"{name}.{key}")
                    if defn["type"] == "number":
                        self.assertIsInstance(defn.get("default", 0), (int, float))
                    elif defn["type"] == "toggle":
                        self.assertIsInstance(defn.get("default", False), bool)
                    elif defn["type"] == "list":
                        self.assertIn("fields", defn, f"{name}.{key}")
                    else:
                        self.assertIsInstance(defn.get("default", ""), str)
                    self.assertIn("label", defn, f"{name}.{key}")

    def test_addon_default_settings_match_schemas(self):
        for subdir, base in (
            ("trackers", TrackerBase),
            ("utilities", UtilityBase),
            ("frame_processors", FrameProcessorBase),
        ):
            for name, cls in load_plugins(PLUGIN_ROOT / subdir, base).items():
                for key, value in cls.default_settings().items():
                    self.assertEqual(cls.config_schema()[key]["default"], value, name)

    def test_empty_plugin_name_guard(self):
        # Every discovered add-on must carry a unique, string plugin_name.
        seen = set()
        for subdir, base in (
            ("trackers", TrackerBase),
            ("utilities", UtilityBase),
            ("frame_processors", FrameProcessorBase),
        ):
            for name in load_plugins(PLUGIN_ROOT / subdir, base):
                self.assertIsInstance(name, str)
                self.assertNotIn(name, seen)
                seen.add(name)


class AddonBaseTests(unittest.TestCase):
    def test_base_default_schema_is_empty(self):
        self.assertEqual(AddonBase.config_schema(), {})

    def test_base_context_normalizes_config(self):
        inst = AddonBase({"config": {"a": 1}})
        self.assertIsInstance(inst.config, iSpyAddonConfig)
        self.assertEqual(inst.config.get("a"), 1)
        inst2 = AddonBase({})
        self.assertIsInstance(inst2.config, iSpyAddonConfig)
        self.assertEqual(inst2.config.to_dict(), {})

    def test_status_mixin_contract(self):
        inst = AddonBase({})
        self.assertEqual(inst.get_status(), "idle")
        inst.update_status("running")
        self.assertEqual(inst.get_status(), "running")


class ObjectTrackerTests(unittest.TestCase):
    def _make(self, settings=None):
        return load_plugins(PLUGIN_ROOT / "trackers", TrackerBase)["FRC/object_tracker"](
            addon_context(
                load_plugins(PLUGIN_ROOT / "trackers", TrackerBase)[
                    "FRC/object_tracker"
                ],
                settings,
            )
        )

    def test_schema_defaults_apply(self):
        tracker = self._make()
        self.assertEqual(tracker.distance_threshold, 0.5)
        self.assertEqual(tracker.stale_threshold, 1.0)

    def test_custom_settings_apply(self):
        tracker = self._make({"distance_threshold": 0.9, "stale_threshold": 2.5})
        self.assertEqual(tracker.distance_threshold, 0.9)
        self.assertEqual(tracker.stale_threshold, 2.5)

    def test_invalid_distance_threshold_falls_back(self):
        tracker = self._make({"distance_threshold": -4})
        self.assertEqual(tracker.distance_threshold, 0.5)

    def test_nearby_detections_merge(self):
        tracker = self._make()
        fuels = tracker.update([Object(0.0, 0.0), Object(0.1, 0.05)], 0, 0, 0)
        self.assertEqual(len(fuels), 1)
        first_id = fuels[0].get_id()
        # same spot again -> same object, not a new one
        fuels = tracker.update([Object(0.03, -0.02)], 0, 0, 0)
        self.assertEqual(len(fuels), 1)
        self.assertEqual(fuels[0].get_id(), first_id)

    def test_distant_detections_stay_separate(self):
        tracker = self._make({"distance_threshold": 0.3})
        fuels = tracker.update([Object(0.0, 0.0), Object(5.0, 5.0)], 0, 0, 0)
        self.assertEqual(len(fuels), 2)

    def test_different_names_never_merge_even_when_close(self):
        # a cone 10cm from a robot must not merge into the robot
        cone = Object(0.0, 0.0)
        cone.name = "cone"
        robot = Object(0.1, 0.05)
        robot.name = "robot"
        tracked = self._make().update([cone, robot], 0, 0, 0)
        self.assertEqual(len(tracked), 2)
        names = {o.name for o in tracked}
        self.assertEqual(names, {"cone", "robot"})

    def test_same_name_close_detections_still_merge(self):
        tracker = self._make()
        a = Object(0.0, 0.0)
        a.name = "cone"
        b = Object(0.03, -0.02)
        b.name = "cone"
        tracked = tracker.update([a], 0, 0, 0)
        first_id = tracked[0].get_id()
        tracked = tracker.update([b], 0, 0, 0)
        self.assertEqual(len(tracked), 1)
        self.assertEqual(tracked[0].get_id(), first_id)

    def test_empty_names_are_treated_as_equal(self):
        # legacy pipelines that never set .name keep old merge behavior
        tracker = self._make()
        tracked = tracker.update([Object(0.0, 0.0)], 0, 0, 0)
        first_id = tracked[0].get_id()
        tracked = tracker.update([Object(0.03, -0.02)], 0, 0, 0)
        self.assertEqual(len(tracked), 1)
        self.assertEqual(tracked[0].get_id(), first_id)

    def test_persistent_object_remerges_by_id_not_distance(self):
        # the voxel world reuses ONE Object across ticks; its centroid jumps
        # as the robot moves, so a distance gate would spawn a ghost duplicate
        # (and the original dies on its stale timer -> flicker). Same id must
        # be treated as the same object no matter how far it "moved".
        tracker = self._make({"distance_threshold": 0.5})
        obj = Object(0.0, 0.0)
        obj.name = "voxel_world"
        tracked = tracker.update([obj], 0, 0, 0)
        self.assertEqual(len(tracked), 1)
        obj.x = 100.0  # far jump, same instance/id
        tracked = tracker.update([obj], 0, 0, 0)
        self.assertEqual(len(tracked), 1)
        self.assertEqual(tracked[0].get_id(), obj.get_id())

    def test_stale_objects_are_dropped(self):
        tracker = self._make({"stale_threshold": 0.05})
        tracker.update([Object(0.0, 0.0)], 0, 0, 0)
        time.sleep(0.1)
        fuels = tracker.update([], 0, 0, 0)
        self.assertEqual(fuels, [])

    def test_robot_transform_applied(self):
        tracker = self._make()
        fuels = tracker.update([Object(1.0, 0.0)], 10, 20, 0)
        pos = fuels[0].get_position_normally()
        self.assertAlmostEqual(pos[0], 11.0)
        self.assertAlmostEqual(pos[1], 20.0)

    def test_stop_clears_tracked_list(self):
        tracker = self._make()
        tracker.update([Object(0.0, 0.0)], 0, 0, 0)
        self.assertTrue(tracker.tracked_objects)
        tracker.stop()
        self.assertEqual(tracker.tracked_objects, [])


class PathPlannerTests(unittest.TestCase):
    def _make(self, settings=None):
        cls = load_plugins(PLUGIN_ROOT / "trackers", TrackerBase)["path_planner"]
        return cls(addon_context(cls, settings))

    def test_schema_defaults_apply(self):
        planner = self._make()
        self.assertEqual(planner.epsilon, 0.3)
        self.assertEqual(planner.min_samples, 3)

    def test_custom_settings_apply(self):
        planner = self._make({"epsilon": 1.0, "min_samples": 2})
        self.assertEqual(planner.epsilon, 1.0)
        self.assertEqual(planner.min_samples, 2)

    def test_clusters_and_noise_are_separated(self):
        planner = self._make({"epsilon": 0.3, "min_samples": 3})
        detections = [
            Object(0.0, 0.0),
            Object(0.1, 0.0),
            Object(0.2, 0.0),  # cluster
            Object(9.0, 9.0),  # noise
        ]
        cleaned = planner.update(detections, 0, 0, 0)
        self.assertIs(cleaned, planner.cluster_positions)
        self.assertEqual(len(cleaned), 3)
        self.assertEqual(len(planner.get_noise_positions()), 1)

    def test_empty_input(self):
        planner = self._make()
        self.assertEqual(planner.update([], 0, 0, 0), [])
        self.assertEqual(planner.get_noise_positions(), [])

    def test_run_returns_clusters(self):
        planner = self._make({"epsilon": 0.3, "min_samples": 3})
        planner.update([Object(0.0, 0.0), Object(0.1, 0.0), Object(0.2, 0.0)], 0, 0, 0)
        self.assertEqual(len(planner.run()), 3)

    def test_stop_does_not_raise(self):
        self._make().stop()


class RollBackTests(unittest.TestCase):
    def test_schema_defaults_apply(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            self.assertEqual(rec._video_output_dir, tmp)
            self.assertEqual(rec._fps, 30.0)
            self.assertEqual(rec._max_queue, 60)
            self.assertEqual(rec._downsample, 1)
            self.assertEqual(rec._segment_seconds, 300)
            self.assertEqual(rec._max_total_bytes, 2048 * 1024 * 1024)

    def test_records_one_avi_per_camera_into_a_session_dir(self):
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("time.sleep"):
                rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
                left = np.zeros((48, 64, 3), dtype=np.uint8)
                right = np.full((48, 64, 3), 200, dtype=np.uint8)
                for _ in range(5):
                    rec.update({"raw_frames": {"Left": left, "Right": right}})
                rec.stop()
            sessions = list(Path(tmp).glob("session_*"))
            self.assertEqual(len(sessions), 1)
            avis = sorted(p.name for p in sessions[0].glob("*.avi"))
            self.assertEqual(len(avis), 2)
            self.assertIn("Left", avis[0])
            self.assertIn("Right", avis[1])
            for name in avis:
                self.assertGreater(
                    (sessions[0] / name).stat().st_size,
                    24,
                    f"{name} must contain frames",
                )

    def test_each_camera_avi_holds_its_own_pixels(self):
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("time.sleep"):
                rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
                for _ in range(5):
                    rec.update(
                        {
                            "raw_frames": {
                                "Left": np.zeros((48, 64, 3), dtype=np.uint8),
                                "Right": np.full((48, 64, 3), 200, dtype=np.uint8),
                            }
                        }
                    )
                rec.stop()
            session = next(Path(tmp).glob("session_*"))
            import cv2

            for name, expected in (("Left", 0), ("Right", 200)):
                cap = cv2.VideoCapture(str(next(session.glob(f"*_{name}.avi"))))
                ok, frame = cap.read()
                cap.release()
                self.assertTrue(ok, name)
                self.assertLessEqual(abs(int(frame[0, 0, 0]) - expected), 4, name)

    def test_session_json_records_what_the_run_was(self):
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("time.sleep"):
                rec = RollBack(
                    addon_context(RollBack, {"data_dir": tmp}, vision=_FakeVision())
                )
                rec.update({"raw_frames": {"Left": np.zeros((8, 8, 3), np.uint8)}})
                rec.stop()
            meta = json.loads(
                (next(Path(tmp).glob("session_*")) / "session.json").read_text()
            )
            self.assertIn("started", meta)
            self.assertIn("version", meta)
            self.assertEqual(meta["unit"], "frc")
            self.assertEqual(list(meta["cameras"]), ["Left"])
            cam = meta["cameras"]["Left"]
            for key in ("source", "pipeline", "x", "y", "height", "yaw", "pitch"):
                self.assertIn(key, cam)
            self.assertIn("calibration", cam)
            self.assertEqual(cam["pipeline"], "object_detection")

    def test_replay_mode_records_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(
                addon_context(RollBack, {"data_dir": tmp}, vision=_FakeVision(replay=True))
            )
            rec.update({"raw_frames": {"Left": np.zeros((8, 8, 3), np.uint8)}})
            rec.stop()
            self.assertFalse(rec._started)
            self.assertEqual(list(Path(tmp).iterdir()), [])

    def test_enabled_false_records_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("time.sleep"):
                rec = RollBack(
                    addon_context(RollBack, {"enabled": False, "data_dir": tmp})
                )
                rec.update({"raw_frames": {"Left": np.zeros((8, 8, 3), np.uint8)}})
                rec.stop()
            self.assertEqual(list(Path(tmp).iterdir()), [])

    def test_records_only_every_nth_frame(self):
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("time.sleep"):
                rec = RollBack(
                    addon_context(RollBack, {"data_dir": tmp, "downsample": 3})
                )
                for _ in range(6):
                    rec.update({"raw_frames": {"Left": np.zeros((8, 8, 3), np.uint8)}})
                rec.stop()
            self.assertGreaterEqual(rec._frame_counter, 6)
            session = next(Path(tmp).glob("session_*"))
            import cv2

            cap = cv2.VideoCapture(str(next(session.glob("*.avi"))))
            written = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            cap.release()
            self.assertEqual(written, 2, "every 3rd of 6 frames")

    def test_ignores_frame_data_without_raw_frames(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            rec.update({"frame": np.zeros((8, 8, 3), np.uint8)})  # legacy shape
            self.assertFalse(rec._started)
            rec.update({"raw_frames": {}})  # every camera skipped
            self.assertFalse(rec._started)
            rec.update({})
            self.assertFalse(rec._started)
            rec.stop()
            # a session is opened at process start, but no frame was usable so
            # no video was ever written
            self.assertEqual(list(Path(tmp).rglob("*.avi")), [])

    def test_stop_before_start_is_safe(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            rec.stop()  # no-op, no crash


class _FakeCamConfig:
    def __init__(self, data):
        self._data = data

    def get(self, key, default=None):
        return self._data.get(key, default)


class _FakeCam:
    def __init__(self, name):
        self.source = "0"
        self.plugin_name = "object_detection"
        self.config = _FakeCamConfig(
            {
                "name": name,
                "x": 10,
                "y": 20,
                "height": 30,
                "yaw": 15,
                "pitch": 5,
                "calibration": {"fov": 90},
            }
        )


class _FakeVision:
    def __init__(self, replay=False):
        self.cameras = [_FakeCam("Left")]
        self.replay_mode = replay


def _session_dir(root, name):
    path = Path(root) / name
    path.mkdir(parents=True, exist_ok=True)
    return path


class RollBackSessionTests(unittest.TestCase):
    def test_stem_avoids_a_name_already_taken_this_second(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            rec._cams = ["Left"]
            rec._session_dir = _session_dir(tmp, "session_2026-01-01_00-00-00")
            with mock.patch("iSpy.core.rollback.datetime") as fake:
                fake.now.return_value.strftime.return_value = "2026-01-01_00-00-00"
                first = rec._next_segment_stem()
                (rec._session_dir / f"{first}_Left.avi").write_bytes(b"")
                second = rec._next_segment_stem()
            self.assertEqual(first, "rollback_2026-01-01_00-00-00")
            self.assertEqual(second, "rollback_2026-01-01_00-00-00_01")

    def test_sanitize_cam(self):
        from iSpy.core.rollback import _sanitize_cam

        self.assertEqual(_sanitize_cam("Left Camera"), "Left_Camera")
        self.assertEqual(_sanitize_cam("a/b\\c:d"), "a_b_c_d")
        self.assertEqual(_sanitize_cam("???"), "cam")
        self.assertEqual(_sanitize_cam(""), "cam")

    def test_segment_expired(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(
                addon_context(RollBack, {"data_dir": tmp, "segment_minutes": 1})
            )
            rec._segment_opened_at = time.time() - 61
            self.assertTrue(rec._segment_expired())
            rec._segment_opened_at = time.time()
            self.assertFalse(rec._segment_expired())
            rec._segment_opened_at = None
            self.assertFalse(rec._segment_expired())

    def test_rotation_writes_a_second_segment(self):
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("time.sleep"):
                rec = RollBack(
                    addon_context(RollBack, {"data_dir": tmp, "segment_minutes": 1})
                )
                frame = np.zeros((48, 64, 3), dtype=np.uint8)
                for _ in range(3):
                    rec.update({"raw_frames": {"Left": frame}})
                # wait on the writers, not the stem - the stem is assigned
                # before the VideoWriter opens, and forcing the timestamp in
                # that window just gets overwritten by _open_segment()
                deadline = time.time() + 5
                while not rec._writers and time.time() < deadline:
                    time.sleep(0.01)
                self.assertTrue(rec._writers, "worker never opened a segment")
                first_stem = rec._stem
                rec._segment_opened_at = time.time() - 61
                for _ in range(3):
                    rec.update({"raw_frames": {"Left": frame}})
                deadline = time.time() + 5
                while rec._stem == first_stem and time.time() < deadline:
                    time.sleep(0.01)
                rec.stop()
            session = next(Path(tmp).glob("session_*"))
            self.assertGreaterEqual(len(list(session.glob("*.avi"))), 2)

    def test_camera_joining_mid_session_rotates(self):
        # a camera that comes up after the session started cannot join the open
        # segment - the worker rotates so each segment has an exact cam list
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("time.sleep"):
                rec = RollBack(
                    addon_context(RollBack, {"data_dir": tmp, "segment_minutes": 30})
                )
                left = np.zeros((48, 64, 3), dtype=np.uint8)
                right = np.zeros((48, 64, 3), dtype=np.uint8)
                for _ in range(3):
                    rec.update({"raw_frames": {"Left": left}})
                deadline = time.time() + 5
                while not rec._writers and time.time() < deadline:
                    time.sleep(0.01)
                first_stem = rec._stem

                for _ in range(3):
                    rec.update({"raw_frames": {"Left": left, "Right": right}})
                # wait on the writers - _cams is adopted before _open_segment
                # has actually opened anything for the new camera
                deadline = time.time() + 5
                while sorted(rec._writers) != ["Left", "Right"] and time.time() < deadline:
                    time.sleep(0.01)
                self.assertEqual(rec._cams, ["Left", "Right"], "right never joined")
                self.assertNotEqual(rec._stem, first_stem, "segment did not rotate")
                self.assertEqual(sorted(rec._writers), ["Left", "Right"])
                second_stem = rec._stem

                # a camera going away is NOT a reason to rotate. _raw_frames
                # drops any camera whose frame is over a second old, so a flaky
                # USB port used to rotate out and back in on every blip and left
                # a pile of one-second segments. the open file keeps being fed
                # the camera's last frame instead
                for _ in range(3):
                    rec.update({"raw_frames": {"Left": left}})
                time.sleep(0.2)
                self.assertEqual(rec._stem, second_stem, "a drop rotated the segment")
                self.assertEqual(sorted(rec._writers), ["Left", "Right"])
                self.assertEqual(rec._cams, ["Left", "Right"])
                self.assertIsNone(rec._cams_pending)
                rec.stop()

            # the opening segment is left-only, the later one carries both
            files = list(Path(tmp).rglob("*.avi"))
            stems = {p.stem.rsplit("_", 1)[0] for p in files}
            self.assertEqual(len(stems), 2, [p.name for p in files])
            first_files = [p for p in files if p.stem.rsplit("_", 1)[0] == first_stem]
            self.assertEqual([p.name for p in first_files], [f"{first_stem}_Left.avi"])
            self.assertEqual(
                sorted(p.name for p in files if p.stem.rsplit("_", 1)[0] == second_stem),
                [f"{second_stem}_Left.avi", f"{second_stem}_Right.avi"],
            )

    def test_a_camera_that_comes_back_does_not_churn_segments(self):
        # the segment a flaky camera is dropped from is kept open and padded, so
        # it is still one segment when the camera returns - no rotate out,
        # rotate back, rotate out again
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("time.sleep"):
                rec = RollBack(
                    addon_context(RollBack, {"data_dir": tmp, "segment_minutes": 30})
                )
                frame = np.zeros((48, 64, 3), dtype=np.uint8)
                for _ in range(3):
                    rec.update({"raw_frames": {"Left": frame}})
                deadline = time.time() + 5
                while not rec._writers and time.time() < deadline:
                    time.sleep(0.01)
                stem = rec._stem

                for _ in range(6):
                    rec.update({"raw_frames": {"Left": frame}})
                    rec.update({"raw_frames": {}})
                time.sleep(0.2)
                self.assertEqual(rec._stem, stem)
                rec.stop()

            stems = {p.stem.rsplit("_", 1)[0] for p in Path(tmp).rglob("*.avi")}
            self.assertEqual(len(stems), 1, "a camera blip split the recording")

    def test_sidecar_is_written_and_matches_the_video(self):
        from iSpy.core.rollback import _iter_segments

        # one sidecar per segment, sharing the stem with the per-camera avis and
        # holding one record per encoded frame
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            frame = np.zeros((48, 64, 3), dtype=np.uint8)
            pose = {"x": 1.0, "y": 2.0, "heading": 0.5}
            for n in range(5):
                rec.update(
                    {
                        "raw_frames": {"Left": frame, "Right": frame},
                        "detections": [{"name": "ball", "confidence": 0.5}],
                        "detection_count": 1,
                        "robot_pose": pose,
                    }
                )
            rec.stop()
            session = rec._session_dir

            sidecar = next(session.glob("rollback_*.json"))
            data = json.loads(sidecar.read_text())
            self.assertEqual(data["cams"], ["Left", "Right"])
            self.assertEqual(data["session"], session.name)
            self.assertEqual(data["stem"], sidecar.stem)
            self.assertEqual(len(data["records"]), 5)

            first = data["records"][0]
            self.assertEqual(first["i"], 1)
            self.assertEqual(first["cams"], ["Left", "Right"])
            self.assertEqual(first["detection_count"], 1)
            self.assertEqual(first["detections"][0]["name"], "ball")
            self.assertEqual(first["robot_pose"], pose)
            self.assertEqual(
                [r["i"] for r in data["records"]], [1, 2, 3, 4, 5]
            )
            stamps = [r["t"] for r in data["records"]]
            self.assertEqual(stamps, sorted(stamps), "record t must be monotonic")

            # the sidecar is what groups the segment together
            segs = _iter_segments(session)
            self.assertEqual(len(segs), 1)
            self.assertEqual(segs[0]["stem"], sidecar.stem)
            self.assertEqual(segs[0]["cams"], ["Left", "Right"])
            self.assertEqual(len(segs[0]["files"]), 3)

    def test_unserializable_detection_does_not_kill_the_worker(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            frame = np.zeros((48, 64, 3), dtype=np.uint8)

            class Hostile:
                def to_dict(self):
                    raise RuntimeError("nope")

            rec.update(
                {
                    "raw_frames": {"Left": frame},
                    "detections": [Hostile()],
                    "detection_count": 1,
                }
            )
            rec.update({"raw_frames": {"Left": frame}})
            rec.stop()
            data = json.loads(next(rec._session_dir.glob("rollback_*.json")).read_text())
            self.assertEqual(len(data["records"]), 2)
            self.assertEqual(data["records"][0]["detections"], [])
            self.assertEqual(data["records"][0]["detection_count"], 1)

    def test_sessions_are_listed_oldest_first(self):
        from iSpy.core.rollback import _iter_sessions

        with tempfile.TemporaryDirectory() as tmp:
            for name in ("session_2026-03-01_00-00-00", "session_2026-01-01_00-00-00"):
                d = _session_dir(tmp, name)
                (d / "session.json").write_text(json.dumps({"started": 1.0}))
            sessions = _iter_sessions(tmp)
            self.assertEqual(
                [s["name"] for s in sessions],
                ["session_2026-01-01_00-00-00", "session_2026-03-01_00-00-00"],
            )
            self.assertFalse(sessions[0]["pinned"])
            self.assertEqual(sessions[0]["started"], 1.0)
            self.assertFalse(sessions[0]["legacy"])

    def test_loose_files_become_one_legacy_session(self):
        from iSpy.core.rollback import _iter_sessions

        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "recording_2026-01-01_00-00-00.mp4").write_bytes(b"x" * 10)
            (Path(tmp) / "notes.txt").write_bytes(b"x")
            sessions = _iter_sessions(tmp)
            self.assertEqual(len(sessions), 1)
            self.assertEqual(sessions[0]["name"], "_legacy")
            self.assertTrue(sessions[0]["legacy"])
            self.assertIsNone(sessions[0]["started"])

    def test_sessions_and_legacy_are_listed_together(self):
        from iSpy.core.rollback import _iter_sessions

        with tempfile.TemporaryDirectory() as tmp:
            _session_dir(tmp, "session_2026-02-01_00-00-00")
            (Path(tmp) / "recording_2026-01-01_00-00-00.mp4").write_bytes(b"x")
            names = [s["name"] for s in _iter_sessions(tmp)]
            self.assertEqual(names, ["_legacy", "session_2026-02-01_00-00-00"])

    def test_pinned_flag_reads_the_pin_file(self):
        from iSpy.core.rollback import _iter_sessions

        with tempfile.TemporaryDirectory() as tmp:
            d = _session_dir(tmp, "session_2026-01-01_00-00-00")
            (d / "PINNED").write_text("")
            self.assertTrue(_iter_sessions(tmp)[0]["pinned"])

    def test_missing_directory_lists_nothing(self):
        from iSpy.core.rollback import _iter_sessions, _iter_segments

        self.assertEqual(_iter_segments("no/such/place"), [])
        self.assertEqual(_iter_sessions("no/such/place"), [])

    def test_segments_group_sidecar_with_per_camera_avis(self):
        from iSpy.core.rollback import _iter_segments

        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "rollback_2026-01-01_00-00-00.json").write_text(
                json.dumps({"cams": ["Left", "Right"]})
            )
            (Path(tmp) / "rollback_2026-01-01_00-00-00_Left.avi").write_bytes(b"x")
            (Path(tmp) / "rollback_2026-01-01_00-00-00_Right.avi").write_bytes(b"x")
            segs = _iter_segments(tmp)
            self.assertEqual(len(segs), 1)
            self.assertEqual(segs[0]["stem"], "rollback_2026-01-01_00-00-00")
            self.assertEqual(segs[0]["cams"], ["Left", "Right"])
            self.assertEqual(len(segs[0]["files"]), 3)

    def test_segment_files_without_a_sidecar_are_standalone(self):
        from iSpy.core.rollback import _iter_segments

        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "rollback_2026-01-01_00-00-00_Left.avi").write_bytes(b"x")
            (Path(tmp) / "recording_2026-02-01_00-00-00.mp4").write_bytes(b"x")
            (Path(tmp) / "notes.txt").write_bytes(b"x")
            (Path(tmp) / "some_other_clip.mp4").write_bytes(b"x")
            (Path(tmp) / "rollback_2026-03-01_00-00-00.avi.part").write_bytes(b"x")
            segs = _iter_segments(tmp)
            self.assertEqual(
                [s["stem"] for s in segs],
                [
                    "recording_2026-02-01_00-00-00",
                    "rollback_2026-01-01_00-00-00_Left",
                ],
            )
            self.assertEqual(segs[0]["cams"], [])


class RollBackRetentionTests(unittest.TestCase):
    def _make(self, tmp, **overrides):
        settings = {"data_dir": tmp}
        settings.update(overrides)
        rec = RollBack(addon_context(RollBack, settings))
        # the recorder opens its own session at process start - drop it so each
        # test keeps control of the exact set of sessions it is reasoning about
        if rec._session_dir is not None:
            shutil.rmtree(rec._session_dir, ignore_errors=True)
            rec._session_name = None
            rec._session_dir = None
        rec._max_total_bytes = overrides.get("_cap", 2000)
        return rec

    def test_deletes_oldest_session_first(self):
        with tempfile.TemporaryDirectory() as tmp:
            for i, size in ((1, 1000), (2, 1000), (3, 1000)):
                d = _session_dir(tmp, f"session_2026-01-0{i}_00-00-00")
                (d / "a.avi").write_bytes(b"x" * size)
            rec = self._make(tmp)
            rec._enforce_retention()
            names = [s["name"] for s in _iter(tmp)]
            self.assertEqual(
                names,
                ["session_2026-01-02_00-00-00", "session_2026-01-03_00-00-00"],
            )

    def test_never_deletes_the_active_session(self):
        with tempfile.TemporaryDirectory() as tmp:
            old = _session_dir(tmp, "session_2026-01-01_00-00-00")
            (old / "a.avi").write_bytes(b"x" * 1000)
            rec = self._make(tmp, _cap=0)
            rec._session_name = "session_2026-01-01_00-00-00"
            rec._enforce_retention()
            self.assertTrue(old.is_dir(), "active session must survive")

    def test_never_deletes_a_pinned_session(self):
        with tempfile.TemporaryDirectory() as tmp:
            pinned = _session_dir(tmp, "session_2026-01-01_00-00-00")
            (pinned / "a.avi").write_bytes(b"x" * 1000)
            (pinned / "PINNED").write_text("")
            fresh = _session_dir(tmp, "session_2026-02-01_00-00-00")
            (fresh / "a.avi").write_bytes(b"x" * 1000)
            rec = self._make(tmp, _cap=0)
            rec._session_name = "session_2026-03-01_00-00-00"
            rec._enforce_retention()
            self.assertTrue(pinned.is_dir(), "pinned session must survive")
            self.assertFalse(fresh.is_dir(), "unpinned older session goes first")

    def test_warns_when_only_pinned_and_active_remain_over_cap(self):
        with tempfile.TemporaryDirectory() as tmp:
            for i in (1, 2):
                d = _session_dir(tmp, f"session_2026-01-0{i}_00-00-00")
                (d / "a.avi").write_bytes(b"x" * 1000)
                (d / "PINNED").write_text("")
            rec = self._make(tmp, _cap=0)
            rec._session_name = "session_2026-03-01_00-00-00"
            with self.assertLogs("iSpy.core.rollback", level="WARNING") as logs:
                rec._enforce_retention()
            self.assertTrue(any("pinned" in m for m in logs.output), logs.output)
            self.assertEqual(len(_iter(tmp)), 2)

    def test_under_cap_deletes_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            for i in (1, 2, 3):
                d = _session_dir(tmp, f"session_2026-01-0{i}_00-00-00")
                (d / "a.avi").write_bytes(b"x" * 100)
            rec = self._make(tmp, _cap=10_000_000)
            rec._enforce_retention()
            self.assertEqual(len(_iter(tmp)), 3)

    def test_legacy_loose_files_are_reclaimable(self):
        # loose files in the data_dir root are a single "_legacy" session, so
        # they are reclaimed as one unit - oldest-first against session dirs
        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "recording_2026-01-01_00-00-00.mp4").write_bytes(b"x" * 4000)
            (Path(tmp) / "rollback_2025-01-01_00-00-00.avi").write_bytes(b"x" * 1000)
            keep = _session_dir(tmp, "session_2026-02-01_00-00-00")
            (keep / "a.avi").write_bytes(b"x" * 500)
            rec = self._make(tmp, _cap=1000)
            rec._enforce_retention()
            self.assertEqual(list(Path(tmp).glob("*.mp4")), [])
            self.assertEqual(list(Path(tmp).glob("rollback_*.avi")), [])
            self.assertTrue(keep.is_dir(), "newer session must survive")

    def test_pinned_legacy_session_survives(self):
        with tempfile.TemporaryDirectory() as tmp:
            old = Path(tmp) / "recording_2026-01-01_00-00-00.mp4"
            old.write_bytes(b"x" * 4000)
            (Path(tmp) / "PINNED").write_text("")
            rec = self._make(tmp, _cap=0)
            rec._enforce_retention()
            self.assertTrue(old.exists())


class ReplayCameraTests(unittest.TestCase):
    # a recording is played back as if it were a live camera, so the whole
    # pipeline can run over a past run with no robot attached

    def _session(self, tmp, count=6, cams=("Left", "Right")):
        rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
        frame = np.zeros((48, 64, 3), dtype=np.uint8)
        for n in range(count):
            rec.update(
                {
                    "raw_frames": {cam: frame for cam in cams},
                    "detections": [{"name": "ball", "confidence": 0.5}],
                    "detection_count": 1,
                    "robot_pose": {"x": float(n), "y": 1.0, "heading": 0.0},
                }
            )
        rec.stop()
        return rec._session_dir

    def test_replay_camera_is_registered(self):
        from iSpy.vision.Cameras import BUILTIN_CAMERAS, CAMERA_TYPE_LABELS
        from iSpy.vision.Cameras.ReplayCamera import ReplayCamera

        self.assertIs(BUILTIN_CAMERAS["replay"], ReplayCamera)
        self.assertIn("replay", CAMERA_TYPE_LABELS)

    def test_replays_a_session_and_exposes_its_pose(self):
        from iSpy.vision.Cameras.ReplayCamera import ReplayCamera

        with tempfile.TemporaryDirectory() as tmp:
            session = self._session(tmp)
            cam = ReplayCamera(
                {
                    "source": str(session),
                    "replay_cam": "Left",
                    "replay_speed": 50.0,
                    "loop": False,
                },
                input_size=(64, 48),
            )
            self.assertTrue(cam._connected)
            self.assertEqual(len(cam._playlist), 1)
            self.assertEqual(len(cam._records), 6)

            # the pose comes off the sidecar, matched to the frame being served
            seen = []
            real_publish = cam._publish

            def spy(frame):
                seen.append(cam.replay_record_i())
                real_publish(frame)

            cam._publish = spy
            deadline = time.time() + 10
            while not cam.replay_finished() and time.time() < deadline:
                time.sleep(0.002)
            cam.release()

            self.assertEqual(seen, [1, 2, 3, 4, 5, 6])
            self.assertEqual(cam.replay_pose()["x"], 5.0)

    def test_replay_speed_and_loop_come_from_config(self):
        from iSpy.vision.Cameras.ReplayCamera import ReplayCamera

        with tempfile.TemporaryDirectory() as tmp:
            session = self._session(tmp)
            cam = ReplayCamera(
                {"source": str(session), "replay_speed": 2.5, "loop": False},
                input_size=(64, 48),
            )
            self.assertEqual(cam._replay_speed, 2.5)
            self.assertFalse(cam._replay_loop)
            # no replay_cam given - it takes the first camera it finds
            self.assertTrue(cam._playlist)
            cam.release()

    def test_age_is_always_zero_so_it_is_never_called_dead(self):
        from iSpy.vision.Cameras.ReplayCamera import ReplayCamera

        with tempfile.TemporaryDirectory() as tmp:
            session = self._session(tmp)
            cam = ReplayCamera(
                {"source": str(session), "replay_speed": 50.0}, input_size=(64, 48)
            )
            self.assertEqual(cam.get_frame_age(), 0.0)
            cam.release()

    def test_missing_source_does_not_pretend_to_be_connected(self):
        from iSpy.vision.Cameras.ReplayCamera import ReplayCamera

        with tempfile.TemporaryDirectory() as tmp:
            cam = ReplayCamera({"source": str(Path(tmp) / "nope")}, input_size=(64, 48))
            self.assertFalse(cam._connected)

    def test_replay_mode_and_pose_override_live_utilities(self):
        # a replayed run must report the recorded pose, not whatever a utility
        # is publishing, and must tell the recorder to stay quiet
        from iSpy.iSpy import iSpy

        vision = iSpy.__new__(iSpy)

        class ReplayCam:
            def replay_pose(self):
                return {"x": 3.0, "y": 4.0, "heading": 0.5}

        class LiveUtility:
            def get_robot_pose(self):
                return None

        vision.cameras = [ReplayCam()]
        vision.utilities = {"nt": LiveUtility()}
        pose = vision._get_pose()
        self.assertAlmostEqual(pose.X(), 3.0)
        self.assertAlmostEqual(pose.Y(), 4.0)
        self.assertTrue(vision.replay_mode)

        vision.cameras = [object()]
        self.assertFalse(vision.replay_mode)


class ReplayBootTests(unittest.TestCase):
    # --replay must build a throwaway camera config and never save it over the
    # real one, or quitting a replay would leave the robot pointed at a video

    def _session(self, tmp, cams=("Left", "Right")):
        session = _session_dir(tmp, "session_2026-01-01_00-00-00")
        (session / "rollback_x.json").write_text(
            json.dumps(
                {
                    "cams": list(cams),
                    "records": [
                        {"i": 1, "t": 1.0, "robot_pose": {"x": 0, "y": 0, "heading": 0}}
                    ],
                }
            )
        )
        for cam in cams:
            (session / f"rollback_x_{cam}.avi").write_bytes(b"x")
        return session

    def _config(self, tmp):
        from iSpy.config.iSpyConfig import iSpyConfig

        cfg_dir = _session_dir(tmp, "Config")
        cfg = iSpyConfig(str(cfg_dir / "config.json"), create=True)
        cfg.set(
            "camera_configs",
            {
                "front": {
                    "name": "front",
                    "pipeline": "line",
                    "camera_type": "opencv",
                    "source": 0,
                }
            },
        )
        return cfg

    def test_recorded_cameras_are_discovered_from_sidecars(self):
        from iSpy.boot.boot import _recorded_cameras

        with tempfile.TemporaryDirectory() as tmp:
            session = self._session(tmp)
            self.assertEqual(_recorded_cameras(session), ["Left", "Right"])

    def test_one_replay_camera_per_recorded_camera(self):
        from iSpy.boot.boot import build_replay_camera_configs

        with tempfile.TemporaryDirectory() as tmp:
            session = self._session(tmp)
            built = build_replay_camera_configs(self._config(tmp), session, 2.0, True, "")
            self.assertEqual(set(built), {"replay_Left", "replay_Right"})
            for entry in built.values():
                self.assertEqual(entry["camera_type"], "replay")
                self.assertEqual(entry["source"], str(session))
                self.assertEqual(entry["replay_speed"], 2.0)
                # the vision stack has to be the one already configured
                self.assertEqual(entry["pipeline"], "line")

    def test_replay_can_select_a_single_camera_and_disable_loop(self):
        from iSpy.boot.boot import build_replay_camera_configs

        with tempfile.TemporaryDirectory() as tmp:
            session = self._session(tmp)
            built = build_replay_camera_configs(
                self._config(tmp), session, 1.0, False, "Right"
            )
            self.assertEqual(set(built), {"replay_Right"})
            self.assertEqual(built["replay_Right"]["replay_cam"], "Right")
            self.assertFalse(built["replay_Right"]["loop"])

    def test_empty_session_is_rejected_loudly(self):
        from iSpy.boot.boot import build_replay_camera_configs

        with tempfile.TemporaryDirectory() as tmp:
            empty = _session_dir(tmp, "session_empty")
            with self.assertRaises(RuntimeError):
                build_replay_camera_configs(self._config(tmp), empty)

    def test_replay_arguments_are_registered(self):
        from iSpy.boot.boot import add_boot_arguments
        import argparse

        parser = add_boot_arguments(argparse.ArgumentParser())
        args = parser.parse_args(["--replay", "some/session", "--replay-speed", "3"])
        self.assertEqual(args.replay, "some/session")
        self.assertEqual(args.replay_speed, 3.0)
        self.assertEqual(args.replay_cam, "")
        self.assertFalse(args.replay_no_loop)
        # main() turns this into replay_loop
        self.assertTrue(not args.replay_no_loop)
        args = parser.parse_args(["--replay", "s", "--replay-no-loop", "--replay-cam", "L"])
        self.assertTrue(args.replay_no_loop)
        self.assertEqual(args.replay_cam, "L")
        # absent by default, so a normal boot is unaffected
        plain = parser.parse_args([])
        self.assertEqual(plain.replay, "")
        self.assertFalse(plain.replay_no_loop)


def _iter(root):
    from iSpy.core.rollback import _iter_sessions

    return _iter_sessions(root)


class RollBackDiskGuardTests(unittest.TestCase):
    def test_recorder_stays_idle_when_the_disk_is_full(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            with mock.patch(
                "shutil.disk_usage", return_value=mock.Mock(free=1024)
            ):
                self.assertIsNotNone(rec._disk_problem())
                rec.update({"raw_frames": {"Left": np.zeros((8, 8, 3), np.uint8)}})
            self.assertFalse(rec._started)
            # the session dir is opened at process start, but nothing is encoded
            self.assertEqual(list(Path(tmp).rglob("*.avi")), [])
            rec.stop()

    def test_recorder_starts_when_there_is_room(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            with mock.patch(
                "shutil.disk_usage", return_value=mock.Mock(free=10 * 1024**3)
            ):
                self.assertIsNone(rec._disk_problem())

    def test_unwritable_output_dir_does_not_raise(self):
        # a bad data_dir must not take vision down at boot - the recorder
        # simply never becomes active. a file standing where a folder has to
        # be fails on every OS, unlike a bare "Z:/..." drive letter
        with tempfile.TemporaryDirectory() as tmp:
            blocker = Path(tmp) / "not-a-folder"
            blocker.write_text("")
            rec = RollBack(
                addon_context(RollBack, {"data_dir": str(blocker / "sessions")})
            )
            self.assertIsNotNone(rec._disk_problem())
            rec.update({"raw_frames": {"Left": np.zeros((8, 8, 3), np.uint8)}})
            self.assertFalse(rec._started)
            rec.stop()


class RollBackWorkerResilienceTests(unittest.TestCase):
    def _started(self, tmp, **settings):
        rec = RollBack(addon_context(RollBack, {"data_dir": tmp, **settings}))
        frame = np.zeros((48, 64, 3), dtype=np.uint8)
        rec.update({"raw_frames": {"Left": frame}})
        deadline = time.time() + 5
        while not rec._writers and time.time() < deadline:
            time.sleep(0.01)
        return rec, frame

    def test_one_bad_tick_does_not_stop_the_worker(self):
        # a raised encoder error used to kill the thread outright, leaving
        # _started True and silently recording nothing for the rest of the run
        with tempfile.TemporaryDirectory() as tmp:
            rec, frame = self._started(tmp)
            self.assertTrue(rec._started)

            calls = []
            real = rec._write_segment

            def flaky(item):
                if not calls:
                    calls.append("boom")
                    raise RuntimeError("encoder")
                calls.append("ok")
                return real(item)

            with mock.patch.object(rec, "_write_segment", side_effect=flaky):
                rec.update({"raw_frames": {"Left": frame}})
                deadline = time.time() + 5
                while len(calls) < 2 and time.time() < deadline:
                    rec.update({"raw_frames": {"Left": frame}})

            self.assertIsNotNone(rec._thread, "worker thread died")
            self.assertGreaterEqual(len(calls), 2, "recording did not resume")
            self.assertEqual(calls[:2], ["boom", "ok"])
            rec.stop()

    def test_full_queue_drops_the_oldest_tick_and_counts_it(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec, _frame = self._started(tmp, max_queue=2)
            rec.stop()

        # a standalone recorder over a full queue - no worker to drain it, so
        # the eviction path is what has to keep the newest ticks
        rec = RollBack(addon_context(RollBack, {"data_dir": tmp, "max_queue": 2}))
        rec._started = True
        for n in range(5):
            rec._write({"frames": {}, "record": {"i": n}})

        self.assertEqual(rec._dropped, 3)
        self.assertEqual(rec._queue.qsize(), 2)
        rec._started = False

    def test_a_camera_with_no_frame_is_padded_from_its_last_frame(self):
        # a short clip is worse than a duplicated one: the sidecar has a record
        # for every tick, so a missing frame shifts every later record
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            rec.stop()

            good = np.full((48, 64, 3), 200, np.uint8)
            rec._size = (64, 48)
            rec._stem = "rollback_test"
            rec._session_name = "session_test"
            rec._session_dir = Path(tmp)
            rec._cams = ["Left"]
            rec._segment_opened_at = time.time()

            written = []
            writer = mock.Mock(write=written.append)
            rec._writers = {"Left": writer}
            rec._open_sidecar()

            try:
                rec._write_segment({"frames": {"Left": good}, "record": {"i": 1}})
                rec._write_segment({"frames": {}, "record": {"i": 2}})
                rec._write_segment({"frames": {"Left": None}, "record": {"i": 3}})
            finally:
                rec._close_segment()

            self.assertEqual(len(written), 3)
            self.assertEqual(int(written[1][0, 0, 0]), 200, "last frame not reused")
            self.assertEqual(int(written[2][0, 0, 0]), 200, "padding not reused")

    def test_sidecar_is_flushed_while_the_segment_is_still_open(self):
        # the sidecar is only closed on a clean stop, so whatever is still in
        # the write buffer is exactly what a power cut would lose
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            rec.stop()

            rec._stem = "rollback_test"
            rec._session_name = "session_test"
            rec._session_dir = Path(tmp)
            rec._cams = ["Left"]
            rec._segment_opened_at = time.time()
            rec._open_sidecar()

            for n in range(30):
                rec._write_sidecar({"i": n})
            self.assertIsNotNone(rec._sidecar, "sidecar closed early")
            self.assertIn('"i": 29', rec._sidecar_path().read_text(encoding="utf-8"))
            rec._close_sidecar()

    def test_disk_filling_mid_session_pauses_recording(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec, frame = self._started(tmp)
            self.assertTrue(rec._started)

            with mock.patch(
                "shutil.disk_usage", return_value=mock.Mock(free=1024)
            ):
                for _ in range(150):
                    rec.update({"raw_frames": {"Left": frame}})
                self.assertTrue(rec._disk_paused, "mid-run disk guard never fired")

                rec._queue.join()
                queued = rec._queue.qsize()
                rec.update({"raw_frames": {"Left": frame}})
                self.assertEqual(rec._queue.qsize(), queued, "paused tick was kept")

            # and it resumes on its own once the volume has room again
            rec._queue.join()
            for _ in range(150):
                rec.update({"raw_frames": {"Left": frame}})
            self.assertFalse(rec._disk_paused)
            self.assertGreater(rec._frame_counter, 150)
            rec.stop()

    def test_a_bad_disk_warning_is_rate_limited(self):
        with tempfile.TemporaryDirectory() as tmp:
            rec = RollBack(addon_context(RollBack, {"data_dir": tmp}))
            with mock.patch(
                "shutil.disk_usage", return_value=mock.Mock(free=1024)
            ), mock.patch.object(rec, "_disk_problem", return_value="full"):
                with self.assertLogs(rec.logger, level="WARNING") as logs:
                    for _ in range(200):
                        rec.update(
                            {"raw_frames": {"Left": np.zeros((8, 8, 3), np.uint8)}}
                        )

            self.assertEqual(
                len(logs.output), 1, f"expected one warning, got {len(logs.output)}"
            )
            rec.stop()


class RollBackPauseTests(unittest.TestCase):
    def test_a_paused_loop_does_not_re_record_the_held_frame(self):
        import iSpy.iSpy as ispy_mod

        seen = {}

        vision = ispy_mod.iSpy.__new__(ispy_mod.iSpy)
        vision.logger = mock.Mock()
        vision.config = mock.Mock()
        vision.config.get.return_value = 0
        vision.shutdown_event = mock.Mock()
        # live, then paused, then exit
        vision.shutdown_event.is_set.side_effect = [False, False, True]
        vision.pause_event = mock.Mock()
        vision.pause_event.is_set.side_effect = [False, True]
        vision.cameras = [mock.Mock()]
        vision.camera_handler = None
        vision.web_app = None

        def _capture(frame):
            seen.update(frame)

        vision._update_utilities = _capture
        vision._update_web = _capture
        vision._run_loop_body_solo = mock.Mock(
            return_value={
                "raw_frames": {"Left": np.zeros((8, 8, 3), np.uint8)},
                "fps": 30.0,
                "code_times": {},
            }
        )
        vision._finish_replay_compare = mock.Mock()
        vision._stop_all_plugins = mock.Mock()

        vision.run_solo_mode()

        self.assertTrue(seen, "the paused loop never published the frozen frame")
        self.assertEqual(
            seen["raw_frames"],
            {},
            "a paused loop must not hand the recorder the same frame again",
        )
        self.assertEqual(seen["fps"], 0)


class NetworkTableHandlerTests(unittest.TestCase):
    def _fresh_module(self, is_connected=True):
        import importlib
        import sys

        sys.modules.pop("iSpy.plugins.utilities.BuiltIn.NetworkHandler", None)
        fake = mock.Mock()
        fake.isConnected.return_value = is_connected
        fake.getTable = mock.Mock(return_value=fake)
        fake.getStructArrayTopic = mock.Mock(return_value=fake)
        fake.getStructTopic = mock.Mock(return_value=fake)
        fake.getDoubleTopic = mock.Mock(return_value=fake)
        fake.getBooleanTopic = mock.Mock(return_value=fake)
        fake.getStringTopic = mock.Mock(return_value=fake)
        fake.subscribe = mock.Mock(return_value=fake)
        fake.publish = mock.Mock(return_value=fake)
        fake.get = mock.Mock(return_value={"x": 1.0, "y": 2.0})
        self._fake_inst = fake
        ntcore_fake = mock.Mock()
        ntcore_fake.NetworkTableInstance.getDefault.return_value = fake
        with mock.patch.dict(sys.modules, {"ntcore": ntcore_fake}):
            return importlib.import_module(
                "iSpy.plugins.utilities.BuiltIn.NetworkHandler"
            )

    def _handler(self, settings=None):
        mod = self._fresh_module()
        cls = mod.NetworkTableHandler
        return cls(addon_context(cls, settings))

    def test_ip_comes_from_addon_settings(self):
        handler = self._handler({"network_tables_ip": "10.1.2.3"})
        self._fake_inst.setServer.assert_called_with("10.1.2.3")
        self._fake_inst.startClient4.assert_called_once()

    def test_default_ip_applies(self):
        handler = self._handler({})
        self._fake_inst.setServer.assert_called_with("10.0.0.2")

    def test_connection_retries_are_non_blocking(self):
        # connecting must never stall boot: startClient4 resolves in the
        # background and __init__ returns immediately with not-connected state.
        mod = self._fresh_module(is_connected=False)
        with mock.patch("time.sleep") as sleep:
            handler = mod.NetworkTableHandler(addon_context(mod.NetworkTableHandler))
            self.assertEqual(sleep.call_count, 0)  # no polling sleep anywhere
            self.assertFalse(handler.isConnected())

    def test_update_publishes_vision_data_when_connected(self):
        handler = self._handler({})
        handler.update(
            {
                "detections": [],
                "fps": 30.5,
                "detection_count": 2,
                "camera_lag_s": 0.04,
                "cameras": [],
            }
        )
        self.assertGreaterEqual(self._fake_inst.flush.call_count, 1)
        self._fake_inst.getStringTopic.assert_called_with("vision_data")

    def test_update_with_connected_false_is_noop(self):
        mod = self._fresh_module(is_connected=False)
        handler = mod.NetworkTableHandler(addon_context(mod.NetworkTableHandler))
        handler.update({"detections": []})
        self.assertEqual(self._fake_inst.flush.call_count, 0)

    def test_update_with_detection_objects_publishes_json(self):
        handler = self._handler({})
        det = Object(1.0, 2.0, 3.0)
        handler.update(
            {
                "detections": [det],
                "fps": 10,
                "detection_count": 1,
                "camera_lag_s": 0.0,
                "cameras": [],
            }
        )
        self._fake_inst.getStringTopic.assert_called_with("vision_data")

    def test_update_is_pipeline_agnostic(self):
        # detections from ANY pipeline (april tag, qr, depth, custom) flow
        # through unchanged - the publisher only touches generic Object
        # accessors, never YOLO-specific fields
        handler = self._handler({})
        tag = Object(0.5, -1.25, 2.0)
        tag.name = "april_tag_3"
        tag.roll = 0.1
        tag.pitch = -0.2
        tag.yaw = 3.0
        qr = Object(9.0, 8.0, 7.0)
        qr.name = "qr_code"
        handler.update(
            {
                "detections": [tag, qr],
                "fps": 60,
                "detection_count": 2,
                "camera_lag_s": 0.0,
                "cameras": [],
            }
        )
        self._fake_inst.getStringTopic.assert_called_with("vision_data")
        pub = handler._subscribers["pub/VisionData/vision_data"]
        detections = json.loads(pub.set.call_args[0][0])
        self.assertEqual(len(detections), 2)
        self.assertAlmostEqual(detections[0]["x"], 0.5)
        self.assertAlmostEqual(detections[0]["y"], -1.25)
        self.assertAlmostEqual(detections[1]["z"], 7.0)

    def test_get_robot_pose(self):
        handler = self._handler({})
        result = handler.get_robot_pose()
        self._fake_inst.getStructTopic.assert_called_once()
        self.assertEqual(result, {"x": 1.0, "y": 2.0})

    def test_stop_is_safe(self):
        handler = self._handler({})
        handler.stop()
        handler.update({"detections": []})


class HealthModuleTests(unittest.TestCase):
    """The always-on HealthModule (iSpy/web/modules/health.py) is the single
    canonical health implementation since health_reporter/status_reporter
    were merged into it."""

    class FakeCamera:
        def __init__(self, name, age):
            self.source = name
            self.config = {"name": name}
            self._age = age

        def get_frame_age(self):
            return self._age

    def _make(self, threshold=None, cameras=None, vision=None):
        from iSpy.web.modules.health import HealthModule

        cfg = iSpyConfig()
        if threshold is not None:
            cfg.config["health_stale_threshold"] = threshold
        ctx = {"config": cfg, "cameras": cameras or [], "vision_instance": vision}
        return HealthModule(ctx)

    def test_stale_threshold_from_top_level_config(self):
        # used to live under utilities.health_reporter.stale_threshold;
        # now a plain top-level config key read by the core module
        self.assertEqual(self._make()._stale_threshold, 1.0)
        self.assertEqual(self._make(threshold=2.5)._stale_threshold, 2.5)

    def test_payload_reflects_updates(self):
        mod = self._make()
        mod.update({"fps": 25.0, "vision_s": 0.02, "detection_count": 7})
        payload, _healthy = mod._build_payload()
        self.assertEqual(payload["fps"], 25.0)
        self.assertEqual(payload["vision_ms"], 20.0)
        self.assertEqual(payload["detections"], 7)
        self.assertGreaterEqual(payload["loop_count"], 1)
        self.assertIn("cameras", payload)
        self.assertIn("addon_health", payload)

    def test_camera_status_marks_stale(self):
        mod = self._make(cameras=[self.FakeCamera("a", 0.1), self.FakeCamera("b", 5.0)])
        payload, healthy = mod._build_payload()
        by_name = {c["name"]: c for c in payload["cameras"]}
        self.assertTrue(by_name["a"]["ok"])
        self.assertFalse(by_name["b"]["ok"])
        self.assertFalse(healthy)

    def test_addon_health_from_network_table_handler(self):
        vision = mock.Mock()
        vision.utilities = {
            "FRC/network_table_handler": mock.Mock(
                get_health=lambda: {
                    "color": "green",
                    "state": "Connected",
                    "metrics": [{"label": "Robot IP", "value": "10.1.2.3"}],
                }
            ),
        }
        mod = self._make(vision=vision)
        payload, healthy = mod._build_payload()
        self.assertTrue(healthy)
        self.assertEqual(len(payload["addon_health"]), 1)
        entry = payload["addon_health"][0]
        self.assertEqual(entry["name"], "FRC/network_table_handler")
        self.assertEqual(entry["type"], "utility")
        self.assertEqual(entry["color"], "green")
        self.assertEqual(entry["state"], "Connected")
        self.assertEqual(entry["metrics"], [{"label": "Robot IP", "value": "10.1.2.3"}])

    def test_unhealthy_addon_degrades_banner(self):
        vision = mock.Mock()
        vision.utilities = {
            "FRC/network_table_handler": mock.Mock(
                get_health=lambda: {
                    "color": "red",
                    "state": "Disconnected",
                    "metrics": [],
                }
            ),
        }
        mod = self._make(vision=vision)
        payload, healthy = mod._build_payload()
        self.assertFalse(healthy)
        self.assertEqual(payload["status"], "degraded")

    def test_only_utilities_and_pipelines_contribute(self):
        vision = mock.Mock()
        vision.utilities = {
            "util": mock.Mock(get_health=lambda: {"state": "up", "metrics": []})
        }
        vision.trackers = {
            "tracker": mock.Mock(get_health=lambda: {"state": "x", "metrics": []})
        }
        vision.frame_processors = {
            "fp": mock.Mock(get_health=lambda: {"state": "x", "metrics": []})
        }
        mod = self._make(vision=vision)
        payload, _healthy = mod._build_payload()
        names = [entry["name"] for entry in payload["addon_health"]]
        self.assertEqual(names, ["util"])

    def test_legacy_ok_rows_shape_is_honored(self):
        vision = mock.Mock()
        vision.utilities = {
            "old_addon": mock.Mock(
                get_health=lambda: {
                    "ok": False,
                    "title": "Old",
                    "info": "bad link",
                    "rows": [{"label": "L", "value": "V"}],
                }
            ),
        }
        mod = self._make(vision=vision)
        payload, healthy = mod._build_payload()
        entry = payload["addon_health"][0]
        self.assertEqual(entry["color"], "red")
        self.assertEqual(entry["state"], "bad link")
        self.assertEqual(entry["metrics"], [{"label": "L", "value": "V"}])
        self.assertFalse(healthy)

    def test_pipeline_contributes_health(self):
        class FakePipeline:
            source = "cam0"
            config = {"name": "front"}

            def get_frame_age(self):
                return 0.05

            def get_health(self):
                return {
                    "color": "yellow",
                    "state": "calibrating",
                    "metrics": [{"label": "Frame age", "value": "12ms"}],
                }

        mod = self._make(cameras=[FakePipeline()])
        payload, healthy = mod._build_payload()
        self.assertTrue(healthy)
        self.assertEqual(
            payload["addon_health"],
            [
                {
                    "name": "cam0",
                    "type": "pipeline",
                    "color": "yellow",
                    "state": "calibrating",
                    "metrics": [{"label": "Frame age", "value": "12ms"}],
                }
            ],
        )

    def test_broken_camera_counts_as_bad(self):
        class BrokenCam:
            source = "broken"

            def get_frame_age(self):
                raise RuntimeError("boom")

        mod = self._make(cameras=[BrokenCam()])
        payload, healthy = mod._build_payload()
        self.assertFalse(healthy)
        self.assertFalse(payload["cameras"][0]["ok"])

    def test_plugin_statuses_pulled_from_vision_instance(self):
        vision = mock.Mock()
        vision.trackers = {
            "FRC/object_tracker": mock.Mock(get_status=lambda: "running")
        }
        vision.utilities = {}
        vision.frame_processors = {}
        mod = self._make(vision=vision)
        statuses = mod._plugin_statuses()
        self.assertEqual(
            statuses,
            [
                {
                    "name": "FRC/object_tracker",
                    "type": "tracker",
                    "status": "running",
                }
            ],
        )

    def test_stop_is_safe(self):
        self._make().stop()


class DashboardModuleTests(unittest.TestCase):
    """System-card hardware aggregation: group by accelerator type, hide
    generic camera names, best-effort utilization reading."""

    class FakeCam:
        def __init__(self, name, hardware):
            self.source = name
            self.config = {"name": name}
            self._hardware = hardware

        def active_hardware(self):
            return self._hardware

    def _make(self, cameras=None):
        from iSpy.web.modules.dashboard import DashboardModule

        return DashboardModule(
            {
                "config": iSpyConfig(),
                "cameras": cameras or [],
                "vision_instance": None,
            }
        )

    def test_groups_by_hardware_type_and_filters_generic_names(self):
        cams = [
            self.FakeCam("default_cam", "npu"),
            self.FakeCam("front_left", "npu"),
            self.FakeCam("Front-6d", "gpu"),
            self.FakeCam("cpu-only", None),
        ]
        hw = self._make(cams)._get_hardware()
        by_type = {h["hardware"]: h for h in hw}
        self.assertEqual(set(by_type), {"npu", "gpu"})
        self.assertEqual(by_type["npu"]["cameras"], ["front_left"])
        self.assertEqual(by_type["gpu"]["cameras"], ["Front-6d"])
        self.assertIn("load_percent", by_type["npu"])

    def test_pipelines_without_accelerator_are_omitted(self):
        cams = [self.FakeCam("cpu_cam", None), self.FakeCam("other", "")]
        self.assertEqual(self._make(cams)._get_hardware(), [])

    def test_npu_load_reads_sysfs(self):
        mod = self._make()
        with mock.patch("pathlib.Path.read_text", return_value="42\n"):
            self.assertEqual(mod._read_hardware_load("npu"), 42)

    def test_npu_load_rejects_raw_busy_counter(self):
        # A raw busy-clock counter (>100) must NOT be clamped into a fake
        # 100% - that clamp was why the NPU bar always sat at 100%.
        mod = self._make()
        with mock.patch("pathlib.Path.read_text", return_value="250"):
            self.assertIsNone(mod._read_hardware_load("npu"))

    def test_npu_load_parses_load_at_freq(self):
        mod = self._make()
        with mock.patch("pathlib.Path.read_text", return_value="54@760000000\n"):
            self.assertEqual(mod._read_hardware_load("npu"), 54)

    def test_npu_load_parses_per_core_debugfs(self):
        mod = self._make()
        with mock.patch(
            "pathlib.Path.read_text",
            return_value="NPU load:  Core0:  0%, Core1:  10%, Core2:  20%,",
        ):
            self.assertEqual(mod._read_hardware_load("npu"), 10)

    def test_npu_load_parses_aggregate_percent(self):
        mod = self._make()
        with mock.patch("pathlib.Path.read_text", return_value="NPU load:  37%"):
            self.assertEqual(mod._read_hardware_load("npu"), 37)

    def test_npu_load_respects_env_override_paths(self):
        mod = self._make()
        with mock.patch.dict("os.environ", {"ISPY_NPU_LOAD_PATHS": "/custom/npu/load"}):
            with mock.patch("pathlib.Path.read_text", return_value="63\n"):
                self.assertEqual(mod._read_hardware_load("npu"), 63)

    def test_npu_load_none_when_sysfs_unavailable(self):
        mod = self._make()
        with mock.patch("pathlib.Path.read_text", side_effect=FileNotFoundError):
            self.assertIsNone(mod._read_hardware_load("npu"))

    def test_unknown_hardware_load_is_none(self):
        mod = self._make()
        self.assertIsNone(mod._read_hardware_load("tpu"))
        self.assertIsNone(mod._read_hardware_load("cpu"))

    def test_gpu_load_uses_nvidia_smi_and_caches(self):
        mod = self._make()
        fake_run = mock.Mock(return_value=mock.Mock(returncode=0, stdout="37\n"))
        with (
            mock.patch("shutil.which", return_value="/usr/bin/nvidia-smi"),
            mock.patch("subprocess.run", fake_run),
        ):
            self.assertEqual(mod._read_hardware_load("gpu"), 37)
        fake_run.assert_called_once()
        with mock.patch("shutil.which") as which_mock:
            self.assertEqual(mod._read_hardware_load("gpu"), 37)
        which_mock.assert_not_called()

    def test_gpu_load_none_without_nvidia_smi(self):
        mod = self._make()
        with mock.patch("shutil.which", return_value=None):
            self.assertIsNone(mod._read_hardware_load("gpu"))


class ExampleAddonTests(unittest.TestCase):
    def test_example_tracker_counts_updates(self):
        cls = load_plugins(PLUGIN_ROOT / "trackers", TrackerBase)["example/example_tracker"]
        tracker = cls(addon_context(cls, {"count_start": 5}))
        self.assertEqual(tracker.count, 5)
        out = tracker.update([], 0, 0, 0)
        self.assertEqual(out, [])
        self.assertEqual(tracker.count, 6)

    def test_example_frame_processor_blackens(self):
        cls = load_plugins(PLUGIN_ROOT / "frame_processors", FrameProcessorBase)[
            "example/example_frame_processor"
        ]
        fp = cls(addon_context(cls))
        frame = np.full((10, 10, 3), 255, dtype=np.uint8)
        out = fp.process(frame)
        self.assertTrue(np.all(out == 0))
        fp.stop()  # safe

    def test_example_utility_ignores_missing_flask(self):
        cls = load_plugins(PLUGIN_ROOT / "utilities", UtilityBase)["example/example_utility"]
        util = cls(addon_context(cls))
        self.assertIsNone(util.flask_app)
        self.assertIsNone(util.get_robot_pose())
        util.stop()

    def test_example_utility_registers_route_with_flask(self):
        import flask

        cls = load_plugins(PLUGIN_ROOT / "utilities", UtilityBase)["example/example_utility"]
        app = flask.Flask(__name__)
        ctx = addon_context(cls)
        ctx["flask_app"] = app
        util = cls(ctx)
        with app.test_client() as client:
            resp = client.get("/ispy-example")
            self.assertEqual(resp.status_code, 200)
            self.assertIn("hello", resp.get_data(as_text=True))

    def test_example_utility_declares_and_publishes_output(self):
        # template utilities demonstrate the addon output system:
        # output_key declared in schema -> counter published every tick
        cls = load_plugins(PLUGIN_ROOT / "utilities", UtilityBase)["example/example_utility"]
        self.assertIn("output_key", cls.config_schema())
        util = cls(addon_context(cls))
        frame_data = {}
        util.update(frame_data)
        util.update(frame_data)
        self.assertEqual(frame_data["addon_data"]["example_output"], 2)


if __name__ == "__main__":
    unittest.main()
