import math
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np

from iSpy.vision.Object import Object
from iSpy.vision.genericYolo import Box, Results, GenericYolo
from iSpy.vision.ObjectDetectionCamera import ObjectDetectionCamera
from iSpy.config.iSpyConfig import iSpyConfig, iSpyCameraConfig
from iSpy.plugins.trackers.BuiltIn.ObjectTracker import ObjectTracker

# Generated by AI. Supposed to help make sure everything works.

def test_object_z():
    o = Object(1, 2, z=3)
    assert o.x == 1
    assert o.y == 2
    assert o.z == 3
    pos = o.get_position()
    assert pos.shape == (3,), f"expected 3D, got {pos.shape}"
    assert pos[2] == 3
    print("  PASS Object.__init__ stores z")


def test_object_relative_to_all_angles():
    o = Object(1, 0, z=0.5, roll=0.1, pitch=0.2, yaw=0.3)
    o.relative_to(10, 20, robot_z=2, robot_roll=0.05, robot_pitch=0.15, robot_yaw=math.pi / 2)
    # yaw rotation: (x=1, y=0) rotated 90° -> (-0, 1) ≈ (0, 1), then + (10, 20)
    assert abs(o.x - 10) < 1e-9, f"x={o.x}"
    assert abs(o.y - 21) < 1e-9, f"y={o.y}"
    assert abs(o.z - 2.5) < 1e-9, f"z={o.z}"
    assert abs(o.roll - 0.15) < 1e-9, f"roll={o.roll}"
    assert abs(o.pitch - 0.35) < 1e-9, f"pitch={o.pitch}"
    assert abs(o.yaw - (0.3 + math.pi / 2) % (2 * math.pi)) < 1e-9, f"yaw={o.yaw}"
    print("  PASS Object.relative_to transforms z, roll, pitch, yaw")


def test_object_get_position_3d():
    o = Object(1, 2, z=3)
    p = o.get_position()
    assert isinstance(p, np.ndarray)
    assert p.shape == (3,)
    assert np.allclose(p, [1, 2, 3])
    print("  PASS Object.get_position returns 3D")


def test_object_get_position_normally_3d():
    o = Object(1, 2, z=3)
    p = o.get_position_normally()
    assert p == (1, 2, 3)
    print("  PASS Object.get_position_normally returns 3D")


_ROOT = Path(__file__).resolve().parents[2]


def _make_cfg():
    cfg = iSpyConfig()
    cfg.set("vision_model", "file_path", str(_ROOT / "iSpy" / "assets" / "_default_box.pt"))
    cfg.set("vision_model", "task", "detect")
    cfg.set("vision_model", "num_classes", 1)
    cfg.set("vision_model", "min_conf", 0.5)
    cfg.set("vision_model", "input_size", [640, 640])
    cfg.set("vision_model", "margin", 0)
    cfg.set("vision_model", "device", "cpu")
    cfg.set("vision_model", "output", {
        "format": "raw",
        "layout": "features_first",
        "quantization": "none",
        "box_format": "xyxy",
        "score_mode": "objectness",
        "scores_are_logits": False,
        "apply_software_nms": True,
        "nms_iou": 0.5,
    })
    return cfg


def _make_camera(yaw=0):
    cfg = _make_cfg()
    cam_cfg = iSpyCameraConfig({
        "name": "test", "source": 99,
        "fps_cap": 1000, "yaw": yaw, "pitch": 0, "height": 1.0,
        "x": 0, "y": 0, "z": 0,
        "subsystem": "test",
        "calibration": {"distance": 1.0, "game_piece_size": 1.0, "size": 100, "fov": 90},
    })
    return ObjectDetectionCamera(cam_cfg, cfg)


def test_box_pnp_path():
    camera = _make_camera()

    # PnP Box with translation and rotation
    box = Box([0, 0, 100, 100], 0.9,
              translation=(0.5, 0.1, 2.0),
              rotation=(0.1, 0.2, 0.3))
    obj = camera._box_to_object(box, 640, 480)
    assert obj is not None
    # With yaw=0, forward=fz=2.0, left_right=-fx=-0.5, height=-fy=-0.1
    # x_rot = 2*1 + (-0.5)*0 = 2, y_rot = 2*0 - (-0.5)*1 = 0.5
    # pnp.object_points are meters and unit="meter", so _pnp_point_to_robot
    # nets out to meters (camera offsets are 0).
    assert abs(obj.x - 2.0) < 1e-6, f"x={obj.x}"
    assert abs(obj.y - 0.5) < 1e-6, f"y={obj.y}"
    assert abs(obj.z - (-0.1)) < 1e-6, f"z={obj.z}"
    assert abs(obj.roll - 0.1) < 1e-9
    assert abs(obj.pitch - 0.2) < 1e-9
    assert abs(obj.yaw - 0.3) < 1e-9
    print("  PASS _box_to_object uses PnP translation and rotation")


def test_box_bbox_only_path():
    camera = _make_camera()

    box = Box([100, 100, 200, 200], 0.9)
    obj = camera._box_to_object(box, 640, 480)
    assert obj is not None
    # bbox-only: z defaults to 0, angles default to 0
    assert obj.z == 0.0, f"z={obj.z}"
    assert obj.roll == 0.0
    assert obj.pitch == 0.0
    assert obj.yaw == 0.0
    print("  PASS _box_to_object bbox-only: z=0, angles=0")


def test_tracker_ema_z_and_angles():
    config_dict = {"distance_threshold": 0.5, "stale_threshold": 2.0}
    cfg = iSpyConfig()
    for k, v in config_dict.items():
        cfg.set(k, v)
    tracker = ObjectTracker(cfg)

    # Inject an existing object
    existing = Object(1, 2, z=0.5, roll=0.1, pitch=0.2, yaw=0.3)
    tracker.fuel_list = [existing]

    # New detection near the existing one
    new_obj = Object(1.1, 2.1, z=0.6, roll=0.15, pitch=0.25, yaw=0.35)
    tracker._merge([new_obj])

    merged = tracker.fuel_list[0]
    alpha = 0.3
    assert abs(merged.x - (1 + alpha * 0.1)) < 1e-6
    assert abs(merged.y - (2 + alpha * 0.1)) < 1e-6
    assert abs(merged.z - (0.5 + alpha * 0.1)) < 1e-6
    assert abs(merged.roll - (0.1 + alpha * 0.05)) < 1e-6
    assert abs(merged.pitch - (0.2 + alpha * 0.05)) < 1e-6
    assert abs(merged.yaw - (0.3 + alpha * 0.05)) < 1e-6
    print("  PASS ObjectTracker EMA on z and angles")


def test_tracker_angle_wrapping():
    alpha = 0.3
    config_dict = {"distance_threshold": 0.5, "stale_threshold": 2.0}
    cfg = iSpyConfig()
    for k, v in config_dict.items():
        cfg.set(k, v)
    tracker = ObjectTracker(cfg)

    # Existing at +175° (radians), new at -175° (should cross through +180°, not go the long way)
    existing = Object(0, 0, z=0, yaw=math.radians(175))
    tracker.fuel_list = [existing]

    new_obj = Object(0.01, 0.01, z=0, yaw=math.radians(-175))
    tracker._merge([new_obj])

    merged_deg = math.degrees(tracker.fuel_list[0].yaw)
    # Should be near ~178°, not near 0° (which would be the long way)
    assert merged_deg > 170 or merged_deg < -170, f"yaw wrapped wrong: {merged_deg}°"
    print(f"  PASS ObjectTracker angle wrapping: {merged_deg:.1f}° (shortest path)")


def test_results_plot_shows_translation():
    frame = np.zeros((480, 640, 3), dtype=np.uint8)
    boxes = [
        Box([10, 10, 100, 100], 0.9, translation=(0.5, 0.1, 2.0), rotation=(0.1, 0.2, 0.3)),
        Box([200, 200, 300, 300], 0.8),
    ]
    r = Results(boxes, (480, 640))
    out = r.plot(frame.copy())
    assert out.shape == frame.shape
    print("  PASS Results.plot runs with/without translation")


def test_fuel_struct_z():
    from iSpy.plugins.utilities.BuiltIn.NetworkHandler import FuelStruct
    fs = FuelStruct(x=1.0, y=2.0, z=3.0, roll=0.1, pitch=0.2, yaw=0.3)
    assert hasattr(fs, "z"), "FuelStruct missing z"
    assert fs.z == 3.0
    print("  PASS FuelStruct has z field")


def test_has_rotation():
    no_rot = Object(0, 0)
    assert not no_rot.has_rotation()
    with_rot = Object(0, 0, roll=0.1)
    assert with_rot.has_rotation()
    print("  PASS Object.has_rotation works with z-only objects")


def test_pnp_to_robot_coordinates():
    cfg = _make_cfg()
    cam_cfg = iSpyCameraConfig({
        "name": "test", "source": 99,
        "fps_cap": 1000, "yaw": 45, "pitch": 0, "height": 1.0,
        "x": 0.5, "y": 0.3, "z": 0.2,
        "subsystem": "test",
        "calibration": {"distance": 1.0, "game_piece_size": 1.0, "size": 100, "fov": 90},
    })
    camera = ObjectDetectionCamera(cam_cfg, cfg)

    tvec = (1.0, 0.5, 3.0)
    pt = camera._pnp_to_robot_coordinates(tvec)
    assert len(pt) == 3, f"expected 3D, got {len(pt)}"
    # pnp.object_points are meters, so the output is meters.  Camera offsets
    # are stored in the internal inch convention and converted in.
    # yaw=45°: cos=sin≈0.7071
    c = math.cos(math.radians(45))
    s = math.sin(math.radians(45))
    inch_to_m = 0.0254
    x_rot = 3.0 * c + (-1.0) * s
    y_rot = 3.0 * s - (-1.0) * c
    expected_x = x_rot + 0.5 * inch_to_m
    expected_y = y_rot + 0.3 * inch_to_m
    expected_z = (-0.5) + 0.2 * inch_to_m
    assert abs(pt[0] - expected_x) < 1e-6, f"x={pt[0]} != {expected_x}"
    assert abs(pt[1] - expected_y) < 1e-6
    assert abs(pt[2] - expected_z) < 1e-6
    print("  PASS _pnp_to_robot_coordinates with yaw+offsets")


def test_object_str_shows_z():
    o = Object(1, 2, z=3)
    s = str(o)
    assert "Z:" in s
    print("  PASS Object.__str__ shows Z")


def test_camera_config_default_has_z():
    cfg = iSpyCameraConfig()
    assert cfg.get("z") == 0
    print("  PASS iSpyCameraConfig default includes z=0")


def test_camera_loads_camera_z():
    cfg = _make_cfg()
    cam_cfg = iSpyCameraConfig({
        "name": "ztest", "source": 99,
        "fps_cap": 30, "yaw": 0, "pitch": 0, "height": 0,
        "x": 0, "y": 0, "z": 1.5,
        "subsystem": "test",
        "calibration": {"distance": 1, "game_piece_size": 1, "size": 100, "fov": 90},
    })
    camera = ObjectDetectionCamera(cam_cfg, cfg)
    assert camera.camera_z == 1.5
    print("  PASS ObjectDetectionCamera loads camera_z from config")


_PNP_OBJECT_POINTS = [
    [0.0, 1.0, 0.1], [-0.03, 0.95, 0.1], [0.03, 0.95, 0.1],
    [-0.08, 0.93, 0.0], [0.08, 0.93, 0.0], [-0.2, 0.8, 0.0],
    [0.2, 0.8, 0.0], [-0.35, 0.55, -0.05], [0.35, 0.55, -0.05],
    [-0.4, 0.3, -0.1], [0.4, 0.3, -0.1], [-0.15, 0.0, 0.0],
    [0.15, 0.0, 0.0], [-0.15, -0.45, 0.0], [0.15, -0.45, 0.0],
    [-0.15, -0.9, 0.0], [0.15, -0.9, 0.0],
]


def _make_pnp_yolo(mode):
    import logging
    gy = GenericYolo.__new__(GenericYolo)
    gy.logger = logging.getLogger("temp_tests")
    gy.pnp_config = {
        "object_points": _PNP_OBJECT_POINTS,
        "camera_matrix": [[600, 0, 320], [0, 600, 240], [0, 0, 1]],
        "dist_coeffs": [0, 0, 0, 0, 0],
        "min_keypoint_conf": 0.5,
        "mode": mode,
    }
    return gy


def test_solve_pnp_flexible_recovers_depth_and_shape():
    import cv2
    gy = _make_pnp_yolo("flexible")
    obj_pts = np.asarray(gy.pnp_config["object_points"], dtype=np.float64)
    K = np.asarray(gy.pnp_config["camera_matrix"], dtype=np.float64)
    dist = np.zeros(5)

    # Synthetic upright person ~1.9 m tall standing 3 m ahead, model y-up
    # projected into the camera's y-down frame.
    rvec_true, _ = cv2.Rodrigues(np.diag([-1.0, -1.0, 1.0]))
    proj, _ = cv2.projectPoints(obj_pts, rvec_true, np.array([0.0, 0.0, 3.0]), K, dist)
    kpts = np.column_stack([proj[:, 0], np.ones((len(obj_pts), 1))])

    euler, tvec, kpts_3d = gy._solve_pnp(kpts, 640, 480)
    assert tvec is not None, "solvePnP failed"
    assert tvec[2] > 2.0, f"depth collapsed to degenerate {tvec[2]:.3f} m"
    k3 = np.asarray(kpts_3d)
    span = float(k3[:, 1].max() - k3[:, 1].min())
    assert 1.5 < span < 2.4, f"vertical span {span:.2f} m not a ~1.9 m person"
    assert k3[0][1] < k3[15][1], "nose below ankles - skeleton is upside down"
    print(f"  PASS _solve_pnp flexible: depth={tvec[2]:.2f} m span={span:.2f} m upright")


def test_solve_pnp_rigid_recovers_full_pose():
    import cv2
    gy = _make_pnp_yolo("rigid")
    obj_pts = np.asarray(gy.pnp_config["object_points"], dtype=np.float64)
    K = np.asarray(gy.pnp_config["camera_matrix"], dtype=np.float64)
    dist = np.zeros(5)

    # Known 6DOF pose: tilted/rotated rigid object at (0.4, -0.2, 3.0).
    rvec_true = np.array([0.25, -0.4, 0.6])
    R_true, _ = cv2.Rodrigues(rvec_true)
    t_true = np.array([0.4, -0.2, 3.0])
    proj, _ = cv2.projectPoints(obj_pts, rvec_true, t_true, K, dist)
    kpts = np.column_stack([proj[:, 0], np.ones((len(obj_pts), 1))])

    euler, tvec, kpts_3d = gy._solve_pnp(kpts, 640, 480)
    assert tvec is not None, "solvePnP failed"
    assert np.allclose(tvec, t_true, atol=1e-3), f"tvec {tvec} != {t_true}"
    # Rigid mode: keypoints_3d must be the fitted model, not the billboard.
    expected = (R_true @ obj_pts.T).T + t_true
    got = np.asarray(kpts_3d)
    assert got.shape == expected.shape
    assert np.allclose(got, expected, atol=1e-2), "rigid keypoints_3d != fitted model"
    sy = math.sqrt(R_true[0, 0] ** 2 + R_true[1, 0] ** 2)
    exp_roll = math.atan2(R_true[2, 1], R_true[2, 2])
    exp_pitch = math.atan2(-R_true[2, 0], sy)
    exp_yaw = math.atan2(R_true[1, 0], R_true[0, 0])
    roll, pitch, yaw = euler
    assert abs(roll - exp_roll) < 1e-2, f"roll {roll} != {exp_roll}"
    assert abs(pitch - exp_pitch) < 1e-2, f"pitch {pitch} != {exp_pitch}"
    assert abs(yaw - exp_yaw) < 1e-2, f"yaw {yaw} != {exp_yaw}"
    print(f"  PASS _solve_pnp rigid: xyz={tvec.round(3)} rpy=({roll:.3f},{pitch:.3f},{yaw:.3f})")


def main():
    tests = [
        ("Object z", test_object_z),
        ("Object relative_to all angles", test_object_relative_to_all_angles),
        ("Object get_position 3D", test_object_get_position_3d),
        ("Object get_position_normally 3D", test_object_get_position_normally_3d),
        ("Box PnP path", test_box_pnp_path),
        ("Box bbox-only path", test_box_bbox_only_path),
        ("Tracker EMA z+angles", test_tracker_ema_z_and_angles),
        ("Tracker angle wrapping", test_tracker_angle_wrapping),
        ("Results.plot translation", test_results_plot_shows_translation),
        ("FuelStruct z", test_fuel_struct_z),
        ("has_rotation", test_has_rotation),
        ("_pnp_to_robot_coordinates", test_pnp_to_robot_coordinates),
        ("Object.__str__ shows Z", test_object_str_shows_z),
        ("Camera config default z", test_camera_config_default_has_z),
        ("Camera loads camera_z", test_camera_loads_camera_z),
        ("_solve_pnp flexible depth/shape", test_solve_pnp_flexible_recovers_depth_and_shape),
        ("_solve_pnp rigid full 6DOF", test_solve_pnp_rigid_recovers_full_pose),
    ]

    passed = 0
    failed = 0
    for name, fn in tests:
        print(f"Test: {name}")
        try:
            fn()
            passed += 1
            print(f"  OK\n")
        except Exception as e:
            failed += 1
            print(f"  FAIL: {e}\n")

    print(f"=" * 40)
    print(f"Total: {passed + failed}  Passed: {passed}  Failed: {failed}")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
