"""
RKNN NPU validation suite.

Runs the full "is the NPU model actually good" checklist:
  1. Correctness    - .rknn vs .pt box/conf agreement on held-out images
  2. Accuracy       - precision/recall/mAP-ish vs a labeled (YOLO-format) val set
  3. Quant analysis - per-layer cosine similarity via rknn.accuracy_analysis()
  4. Speed          - FPS across all NPU core masks (via ObjectDetectionCamera)
  5. Stability       - long-run FPS/thermal drift
  6. Edge cases     - empty frame, corner objects, overlapping objects

Usage:
    python -m iSpy.validations.test_rknn --pt YoloModels/pytorch/model.pt \
        --rknn YoloModels/rknn/model.rknn --val-dir ValSet --duration 300

Only sections with the required inputs available will run; missing inputs are
skipped with a clear reason rather than crashing the whole suite.
"""

# Generated by Claude

import argparse
import glob as _glob
import json
import logging
import os
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import cv2

_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent.parent.resolve()
if not (_PROJECT_ROOT / "iSpy").is_dir():
    _PROJECT_ROOT = Path.cwd()
sys.path.insert(0, str(_PROJECT_ROOT))

os.environ.setdefault("RKNN_LOG_LEVEL", "3")
os.environ.setdefault("YOLO_VERBOSE", "False")

logging.basicConfig(level=logging.WARNING, format="%(message)s", force=True)
for name in list(logging.root.manager.loggerDict):
    if not name.startswith("iSpy") and name != "rknn-test":
        logging.getLogger(name).setLevel(logging.CRITICAL + 1)
logger = logging.getLogger("rknn-test")
logger.setLevel(logging.INFO)


# ─── Terminal formatting helpers ─────────────────────────────────────────────

class C:
    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    GREEN = "\033[32m"
    RED = "\033[31m"
    YELLOW = "\033[33m"
    CYAN = "\033[36m"
    BLUE = "\033[34m"

_USE_COLOR = sys.stdout.isatty()


def _c(text, color):
    if not _USE_COLOR:
        return text
    return f"{color}{text}{C.RESET}"


def _pass(cond: bool) -> str:
    return _c("PASS", C.GREEN) if cond else _c("FAIL", C.RED)


def _status(status: str) -> str:
    return {
        "PASS": _c("PASS", C.GREEN),
        "FAIL": _c("FAIL", C.RED),
        "WARN": _c("WARN", C.YELLOW),
        "SKIP": _c("SKIP", C.DIM),
    }.get(status, status)


def section(title: str):
    width = 74
    print()
    print(_c("=" * width, C.CYAN))
    print(_c(f"  {title}", C.BOLD + C.CYAN))
    print(_c("=" * width, C.CYAN))


def subline(label: str, value: str, status: str | None = None):
    tag = f"  [{_status(status)}]" if status else ""
    print(f"  {label:<38} {value}{tag}")


def warn(msg: str):
    print(_c(f"  ! {msg}", C.YELLOW))


def skip(msg: str):
    print(_c(f"  - skipped: {msg}", C.DIM))


# ─── Result container ────────────────────────────────────────────────────────

@dataclass
class SuiteResults:
    correctness: dict = field(default_factory=dict)
    accuracy: dict = field(default_factory=dict)
    quant_analysis: dict = field(default_factory=dict)
    speed: dict = field(default_factory=dict)
    stability: dict = field(default_factory=dict)
    edge_cases: dict = field(default_factory=dict)
    overall_verdict: str = "UNKNOWN"
    verdict_reasons: list = field(default_factory=list)


# ─── 1. Correctness: .rknn vs .pt agreement ──────────────────────────────────

def run_correctness(pt_config, rknn_config, images: list[Path], results: SuiteResults):
    section("1. CORRECTNESS  -  .rknn vs .pt box agreement")

    if not images:
        skip("no test images provided (--images / --val-dir)")
        results.correctness["status"] = "SKIP"
        return

    from iSpy.vision.genericYolo import GenericYolo

    try:
        pt_model = GenericYolo(pt_config, core_mask=None)
    except Exception as e:
        warn(f"Could not load .pt model: {e}")
        results.correctness["status"] = "SKIP"
        return

    try:
        rknn_model = GenericYolo(rknn_config, core_mask=7)
    except Exception as e:
        warn(f"Could not load .rknn model: {e}")
        results.correctness["status"] = "SKIP"
        return

    per_image = []
    for img_path in images:
        frame = cv2.imread(str(img_path))
        if frame is None:
            continue
        pt_res = pt_model.predict(frame, orig_shape=frame.shape)
        rknn_res = rknn_model.predict(frame, orig_shape=frame.shape)

        matched, iou_sum = _match_boxes(pt_res.boxes, rknn_res.boxes)
        n_pt, n_rknn = len(pt_res.boxes), len(rknn_res.boxes)
        avg_iou = iou_sum / matched if matched else 0.0

        per_image.append({
            "image": img_path.name,
            "pt_boxes": n_pt,
            "rknn_boxes": n_rknn,
            "matched": matched,
            "avg_iou": avg_iou,
        })

    if not per_image:
        warn("No readable images found.")
        results.correctness["status"] = "SKIP"
        return

    total_pt = sum(r["pt_boxes"] for r in per_image)
    total_rknn = sum(r["rknn_boxes"] for r in per_image)
    total_matched = sum(r["matched"] for r in per_image)
    match_rate = total_matched / total_pt if total_pt else 0.0
    mean_iou = np.mean([r["avg_iou"] for r in per_image if r["matched"] > 0]) if any(
        r["matched"] > 0 for r in per_image
    ) else 0.0

    subline("Images tested", str(len(per_image)))
    subline(".pt total boxes", str(total_pt))
    subline(".rknn total boxes", str(total_rknn))
    subline("Matched (IoU>0.5, same class)", f"{total_matched}/{total_pt}")
    subline("Match rate", f"{match_rate * 100:.1f}%", "PASS" if match_rate >= 0.85 else "FAIL")
    subline("Mean IoU on matches", f"{mean_iou:.3f}", "PASS" if mean_iou >= 0.7 else "WARN")

    worst = sorted(per_image, key=lambda r: r["matched"] / max(r["pt_boxes"], 1))[:3]
    if worst and worst[0]["pt_boxes"] > 0:
        print(f"\n  {_c('Worst-agreeing images:', C.DIM)}")
        for r in worst:
            if r["pt_boxes"] == 0:
                continue
            print(f"    {r['image']:<30} pt={r['pt_boxes']} rknn={r['rknn_boxes']} matched={r['matched']}")

    results.correctness = {
        "status": "PASS" if match_rate >= 0.85 else "FAIL",
        "match_rate": match_rate,
        "mean_iou": mean_iou,
        "total_pt_boxes": total_pt,
        "total_rknn_boxes": total_rknn,
        "per_image": per_image,
    }

    try:
        pt_model.release()
    except Exception:
        pass
    try:
        rknn_model.release()
    except Exception:
        pass


def _iou(a, b) -> float:
    ax1, ay1, ax2, ay2 = a
    bx1, by1, bx2, by2 = b
    ix1, iy1 = max(ax1, bx1), max(ay1, by1)
    ix2, iy2 = min(ax2, bx2), min(ay2, by2)
    iw, ih = max(0.0, ix2 - ix1), max(0.0, iy2 - iy1)
    inter = iw * ih
    area_a = max(0.0, ax2 - ax1) * max(0.0, ay2 - ay1)
    area_b = max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
    union = area_a + area_b - inter
    return inter / union if union > 0 else 0.0


def _match_boxes(ref_boxes, test_boxes, iou_thresh=0.5):
    used = set()
    matched = 0
    iou_sum = 0.0
    for rb in ref_boxes:
        best_iou, best_idx = 0.0, -1
        for i, tb in enumerate(test_boxes):
            if i in used or tb.cls_id != rb.cls_id:
                continue
            v = _iou(rb.xyxy, tb.xyxy)
            if v > best_iou:
                best_iou, best_idx = v, i
        if best_idx >= 0 and best_iou >= iou_thresh:
            used.add(best_idx)
            matched += 1
            iou_sum += best_iou
    return matched, iou_sum


# ─── 2. Accuracy: precision/recall against labeled val set ──────────────────

def _load_yolo_labels(label_path: Path, img_w: int, img_h: int) -> list[tuple[int, list[float]]]:
    boxes = []
    if not label_path.exists():
        return boxes
    for line in label_path.read_text().splitlines():
        parts = line.split()
        if len(parts) < 5:
            continue
        cls_id = int(float(parts[0]))
        cx, cy, w, h = (float(x) for x in parts[1:5])
        x1 = (cx - w / 2) * img_w
        y1 = (cy - h / 2) * img_h
        x2 = (cx + w / 2) * img_w
        y2 = (cy + h / 2) * img_h
        boxes.append((cls_id, [x1, y1, x2, y2]))
    return boxes


def run_accuracy(rknn_config, val_dir: Path | None, results: SuiteResults):
    section("2. ACCURACY  -  precision / recall vs labeled val set")

    if val_dir is None or not val_dir.exists():
        skip("no --val-dir provided (expects <val_dir>/images/*.jpg + <val_dir>/labels/*.txt in YOLO format)")
        results.accuracy["status"] = "SKIP"
        return

    images_dir = val_dir / "images"
    labels_dir = val_dir / "labels"
    if not images_dir.exists() or not labels_dir.exists():
        warn(f"Expected {images_dir} and {labels_dir} - not found.")
        results.accuracy["status"] = "SKIP"
        return

    img_paths = sorted(
        p for ext in ("*.jpg", "*.jpeg", "*.png") for p in images_dir.glob(ext)
    )
    if not img_paths:
        warn("No images found in val set.")
        results.accuracy["status"] = "SKIP"
        return

    from iSpy.vision.genericYolo import GenericYolo
    try:
        model = GenericYolo(rknn_config, core_mask=7)
    except Exception as e:
        warn(f"Could not load .rknn model: {e}")
        results.accuracy["status"] = "SKIP"
        return

    tp = fp = fn = 0
    per_class = {}

    for img_path in img_paths:
        frame = cv2.imread(str(img_path))
        if frame is None:
            continue
        h, w = frame.shape[:2]
        label_path = labels_dir / f"{img_path.stem}.txt"
        gt_boxes = _load_yolo_labels(label_path, w, h)

        res = model.predict(frame, orig_shape=frame.shape)
        pred_boxes = [(b.cls_id, b.xyxy) for b in res.boxes]

        used_pred = set()
        for cls_id, gt_box in gt_boxes:
            per_class.setdefault(cls_id, {"tp": 0, "fp": 0, "fn": 0})
            best_iou, best_idx = 0.0, -1
            for i, (p_cls, p_box) in enumerate(pred_boxes):
                if i in used_pred or p_cls != cls_id:
                    continue
                v = _iou(gt_box, p_box)
                if v > best_iou:
                    best_iou, best_idx = v, i
            if best_idx >= 0 and best_iou >= 0.5:
                used_pred.add(best_idx)
                tp += 1
                per_class[cls_id]["tp"] += 1
            else:
                fn += 1
                per_class[cls_id]["fn"] += 1

        for i, (p_cls, _) in enumerate(pred_boxes):
            if i not in used_pred:
                fp += 1
                per_class.setdefault(p_cls, {"tp": 0, "fp": 0, "fn": 0})
                per_class[p_cls]["fp"] += 1

    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0

    subline("Images evaluated", str(len(img_paths)))
    subline("True positives (IoU>0.5)", str(tp))
    subline("False positives", str(fp))
    subline("False negatives (missed)", str(fn))
    subline("Precision", f"{precision * 100:.1f}%", "PASS" if precision >= 0.85 else "WARN")
    subline("Recall", f"{recall * 100:.1f}%", "PASS" if recall >= 0.85 else "FAIL")
    subline("F1", f"{f1:.3f}")

    if len(per_class) > 1:
        print(f"\n  {_c('Per-class breakdown:', C.DIM)}")
        for cls_id, counts in sorted(per_class.items()):
            c_tp, c_fp, c_fn = counts["tp"], counts["fp"], counts["fn"]
            c_recall = c_tp / (c_tp + c_fn) if (c_tp + c_fn) else 0.0
            print(f"    class {cls_id}: tp={c_tp} fp={c_fp} fn={c_fn} recall={c_recall * 100:.1f}%")

    results.accuracy = {
        "status": "PASS" if recall >= 0.85 else "FAIL",
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "tp": tp, "fp": fp, "fn": fn,
        "per_class": per_class,
    }

    try:
        model.release()
    except Exception:
        pass


# ─── 3. Quant analysis: rknn.accuracy_analysis() ─────────────────────────────

def run_quant_analysis(onnx_path: Path | None, input_size, dataset_txt: Path | None,
                        sample_image: Path | None, out_dir: Path, results: SuiteResults):
    section("3. QUANT ANALYSIS  -  per-layer cosine similarity")

    if onnx_path is None or not onnx_path.exists():
        skip("no --onnx path provided (needs the ONNX used to build the .rknn)")
        results.quant_analysis["status"] = "SKIP"
        return
    if sample_image is None or not sample_image.exists():
        skip("no --sample-image provided for accuracy_analysis()")
        results.quant_analysis["status"] = "SKIP"
        return

    try:
        from rknn.api import RKNN
    except ImportError:
        skip("rknn-toolkit2 (full, not lite) not installed - analysis requires the build-side API")
        results.quant_analysis["status"] = "SKIP"
        return

    rknn = RKNN(verbose=False)
    analysis_dir = out_dir / "quant_analysis"
    analysis_dir.mkdir(parents=True, exist_ok=True)

    try:
        rknn.config(
            mean_values=[[0, 0, 0]],
            std_values=[[255, 255, 255]],
            target_platform="rk3588",
        )
        ret = rknn.load_onnx(model=str(onnx_path))
        if ret != 0:
            warn(f"load_onnx failed (code {ret})")
            results.quant_analysis["status"] = "FAIL"
            return

        if dataset_txt and dataset_txt.exists():
            ret = rknn.build(do_quantization=True, dataset=str(dataset_txt))
        else:
            warn("no calibration dataset.txt found - skipping quantized build/analysis")
            results.quant_analysis["status"] = "SKIP"
            return

        if ret != 0:
            warn(f"build failed (code {ret})")
            results.quant_analysis["status"] = "FAIL"
            return

        rknn.accuracy_analysis(inputs=[str(sample_image)], output_dir=str(analysis_dir))

        subline("Analysis output", str(analysis_dir))
        report_files = list(analysis_dir.glob("*.txt")) + list(analysis_dir.glob("*.log"))
        worst_layers = []
        for rf in report_files:
            try:
                text = rf.read_text(errors="ignore")
                for line in text.splitlines():
                    if "cos" in line.lower():
                        worst_layers.append(line.strip())
            except Exception:
                pass

        if worst_layers:
            print(f"\n  {_c('Layers with cosine-similarity data (see full report for all):', C.DIM)}")
            for line in worst_layers[:10]:
                print(f"    {line}")
            subline("Status", "review report for outlier layers", "WARN")
        else:
            subline("Status", "report generated - inspect manually", "WARN")

        results.quant_analysis = {
            "status": "WARN",
            "output_dir": str(analysis_dir),
            "note": "Automated cosine-similarity threshold parsing is best-effort; "
                    "inspect the report directly for the final output tensor's layer.",
        }
    except Exception as e:
        warn(f"accuracy_analysis failed: {e}")
        results.quant_analysis["status"] = "FAIL"
    finally:
        rknn.release()


# ─── 4. Speed: FPS across core masks ─────────────────────────────────────────

def run_speed(rknn_config, duration: float, results: SuiteResults):
    section("4. SPEED  -  FPS across NPU core masks")

    from iSpy.vision.ObjectDetectionCamera import ObjectDetectionCamera
    from iSpy.config.iSpyConfig import iSpyConfig, iSpyCameraConfig

    masks = [
        (1, "NPU-core0"),
        (2, "NPU-core1"),
        (4, "NPU-core2"),
        (3, "NPU-cores0+1"),
        (7, "NPU-all3"),
    ]
    n = len(_glob.glob("/dev/rknpu*"))
    if n and n < 3:
        masks = masks[:2]

    config = iSpyConfig()
    config.set("vision_model", rknn_config)
    cam_cfg = iSpyCameraConfig({
        "name": "bench", "source": 99, "fps_cap": 1000,
        "yaw": 0, "pitch": 0, "height": 1.0, "x": 0, "y": 0,
        "subsystem": "bench",
        "calibration": {"distance": 1.0, "game_piece_size": 1.0, "size": 100, "fov": 90},
    })

    rows = []
    for core_mask, label in masks:
        try:
            camera = ObjectDetectionCamera(cam_cfg, config, core_mask=core_mask)
            for _ in range(5):
                camera.run()
            count = 0
            start = time.perf_counter()
            while time.perf_counter() - start < duration:
                camera.run()
                count += 1
            elapsed = time.perf_counter() - start
            camera.destroy()
            fps = count / elapsed
            rows.append({"label": label, "core_mask": core_mask, "fps": fps,
                         "inference_ms": elapsed / count * 1000 if count else None})
        except Exception as e:
            rows.append({"label": label, "core_mask": core_mask, "fps": None, "error": str(e)})

    for r in rows:
        if r.get("fps"):
            subline(r["label"], f"{r['fps']:.1f} FPS  ({r['inference_ms']:.1f} ms/frame)")
        else:
            subline(r["label"], f"ERROR: {r.get('error', 'unknown')}", "FAIL")

    best = max((r for r in rows if r.get("fps")), key=lambda r: r["fps"], default=None)
    if best:
        print()
        subline("Best config", f"{best['label']} @ {best['fps']:.1f} FPS", "PASS")

    results.speed = {"status": "PASS" if best else "FAIL", "results": rows,
                      "best": best["label"] if best else None}


# ─── 5. Stability: long-run drift + thermal ──────────────────────────────────

def _read_soc_temp() -> float | None:
    for path in _glob.glob("/sys/class/thermal/thermal_zone*/temp"):
        try:
            val = int(open(path).read().strip())
            return val / 1000.0
        except Exception:
            continue
    return None


def run_stability(rknn_config, duration: float, results: SuiteResults):
    section("5. STABILITY  -  long-run FPS drift + thermal")

    if duration < 30:
        skip(f"duration ({duration:.0f}s) too short for a meaningful stability run - use --duration 300+")
        results.stability["status"] = "SKIP"
        return

    from iSpy.vision.ObjectDetectionCamera import ObjectDetectionCamera
    from iSpy.config.iSpyConfig import iSpyConfig, iSpyCameraConfig

    config = iSpyConfig()
    config.set("vision_model", rknn_config)
    cam_cfg = iSpyCameraConfig({
        "name": "stability", "source": 99, "fps_cap": 1000,
        "yaw": 0, "pitch": 0, "height": 1.0, "x": 0, "y": 0,
        "subsystem": "bench",
        "calibration": {"distance": 1.0, "game_piece_size": 1.0, "size": 100, "fov": 90},
    })

    try:
        camera = ObjectDetectionCamera(cam_cfg, config, core_mask=7)
    except Exception as e:
        warn(f"Could not init camera/model: {e}")
        results.stability["status"] = "SKIP"
        return

    for _ in range(5):
        camera.run()

    window_s = 10.0
    samples = []  # (elapsed_s, fps, temp)
    start = time.perf_counter()
    window_start = start
    window_count = 0

    print(f"  Running for {duration:.0f}s (this will take a while)...")
    while time.perf_counter() - start < duration:
        camera.run()
        window_count += 1
        now = time.perf_counter()
        if now - window_start >= window_s:
            fps = window_count / (now - window_start)
            temp = _read_soc_temp()
            samples.append((now - start, fps, temp))
            window_start = now
            window_count = 0

    camera.destroy()

    if len(samples) < 2:
        warn("Not enough samples collected for drift analysis.")
        results.stability["status"] = "SKIP"
        return

    first_fps = samples[0][1]
    last_fps = samples[-1][1]
    min_fps = min(s[1] for s in samples)
    drift_pct = (first_fps - min_fps) / first_fps * 100 if first_fps else 0.0

    temps = [s[2] for s in samples if s[2] is not None]

    subline("Samples", f"{len(samples)} windows @ {window_s:.0f}s each")
    subline("First-window FPS", f"{first_fps:.1f}")
    subline("Last-window FPS", f"{last_fps:.1f}")
    subline("Min FPS observed", f"{min_fps:.1f}")
    subline("FPS drift (peak->min)", f"{drift_pct:.1f}%", "PASS" if drift_pct <= 10 else "FAIL")
    if temps:
        subline("SoC temp start->end", f"{temps[0]:.1f}C -> {temps[-1]:.1f}C",
                 "WARN" if temps[-1] - temps[0] > 15 else "PASS")
    else:
        subline("SoC temp", "unavailable (no thermal_zone found)", "SKIP")

    results.stability = {
        "status": "PASS" if drift_pct <= 10 else "FAIL",
        "drift_pct": drift_pct,
        "first_fps": first_fps,
        "last_fps": last_fps,
        "min_fps": min_fps,
        "temps": temps,
        "samples": samples,
    }


# ─── 6. Edge cases ────────────────────────────────────────────────────────────

def run_edge_cases(rknn_config, input_size, results: SuiteResults):
    section("6. EDGE CASES  -  empty frame, corners, overlaps")

    from iSpy.vision.genericYolo import GenericYolo
    try:
        model = GenericYolo(rknn_config, core_mask=7)
    except Exception as e:
        warn(f"Could not load .rknn model: {e}")
        results.edge_cases["status"] = "SKIP"
        return

    checks = []

    # 6a. Empty / blank frame - should not crash, should return 0 or near-0 boxes
    try:
        blank = np.full((480, 640, 3), 20, dtype=np.uint8)
        res = model.predict(blank, orig_shape=blank.shape)
        ok = res is not None and isinstance(res.boxes, list)
        checks.append(("Blank frame handled without crash", ok))
    except Exception as e:
        checks.append((f"Blank frame handled without crash (raised: {e})", False))

    # 6b. Solid noise frame - should not produce absurd box counts
    try:
        noise = np.random.randint(0, 256, (480, 640, 3), dtype=np.uint8)
        res = model.predict(noise, orig_shape=noise.shape)
        ok = len(res.boxes) < 50  # sanity ceiling, not a real detector should never do this
        checks.append((f"Noise frame doesn't explode box count ({len(res.boxes)} boxes)", ok))
    except Exception as e:
        checks.append((f"Noise frame handled without crash (raised: {e})", False))

    # 6c. All-black frame
    try:
        black = np.zeros((480, 640, 3), dtype=np.uint8)
        res = model.predict(black, orig_shape=black.shape)
        ok = res is not None
        checks.append(("All-black frame handled without crash", ok))
    except Exception as e:
        checks.append((f"All-black frame handled without crash (raised: {e})", False))

    # 6d. Non-square / unusual aspect ratio input
    try:
        wide = np.full((240, 1280, 3), 40, dtype=np.uint8)
        res = model.predict(wide, orig_shape=wide.shape)
        boxes_in_bounds = all(
            0 <= b.xyxy[0] <= wide.shape[1] and 0 <= b.xyxy[2] <= wide.shape[1]
            and 0 <= b.xyxy[1] <= wide.shape[0] and 0 <= b.xyxy[3] <= wide.shape[0]
            for b in res.boxes
        )
        checks.append(("Wide-aspect frame: boxes stay within image bounds", boxes_in_bounds))
    except Exception as e:
        checks.append((f"Wide-aspect frame handled without crash (raised: {e})", False))

    for label, ok in checks:
        subline(label, "", "PASS" if ok else "FAIL")

    passed = sum(1 for _, ok in checks if ok)
    results.edge_cases = {
        "status": "PASS" if passed == len(checks) else "FAIL",
        "passed": passed,
        "total": len(checks),
        "checks": [{"label": l, "passed": ok} for l, ok in checks],
    }

    try:
        model.release()
    except Exception:
        pass


# ─── Verdict + summary ────────────────────────────────────────────────────────

def print_summary(results: SuiteResults):
    section("SUMMARY")

    rows = [
        ("Correctness (vs .pt)", results.correctness.get("status", "SKIP")),
        ("Accuracy (val set)", results.accuracy.get("status", "SKIP")),
        ("Quant layer analysis", results.quant_analysis.get("status", "SKIP")),
        ("Speed", results.speed.get("status", "SKIP")),
        ("Stability (long-run)", results.stability.get("status", "SKIP")),
        ("Edge cases", results.edge_cases.get("status", "SKIP")),
    ]
    for label, status in rows:
        subline(label, "", status)

    hard_fails = [label for label, status in rows if status == "FAIL"]
    ran = [status for _, status in rows if status != "SKIP"]

    print()
    if not ran:
        verdict = "INCONCLUSIVE"
        reasons = ["No sections ran - provide --images/--val-dir/--onnx/--sample-image as needed."]
    elif hard_fails:
        verdict = "NOT READY"
        reasons = [f"Failing section(s): {', '.join(hard_fails)}"]
    elif any(status == "SKIP" for _, status in rows):
        verdict = "PARTIALLY VALIDATED"
        skipped = [label for label, status in rows if status == "SKIP"]
        reasons = [f"Skipped (missing inputs): {', '.join(skipped)}"]
    else:
        verdict = "READY"
        reasons = ["All sections passed."]

    color = {"READY": C.GREEN, "PARTIALLY VALIDATED": C.YELLOW,
             "NOT READY": C.RED, "INCONCLUSIVE": C.DIM}[verdict]
    print(_c(f"  VERDICT: {verdict}", C.BOLD + color))
    for r in reasons:
        print(f"    - {r}")
    print()

    results.overall_verdict = verdict
    results.verdict_reasons = reasons


def save_json_report(results: SuiteResults, out_path: Path):
    def _clean(obj):
        if isinstance(obj, dict):
            return {k: _clean(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [_clean(v) for v in obj]
        if isinstance(obj, (np.floating,)):
            return float(obj)
        if isinstance(obj, (np.integer,)):
            return int(obj)
        if isinstance(obj, tuple):
            return [_clean(v) for v in obj]
        return obj

    payload = _clean({
        "overall_verdict": results.overall_verdict,
        "verdict_reasons": results.verdict_reasons,
        "correctness": results.correctness,
        "accuracy": results.accuracy,
        "quant_analysis": results.quant_analysis,
        "speed": results.speed,
        "stability": results.stability,
        "edge_cases": results.edge_cases,
    })
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(payload, f, indent=2)
    print(f"  Full report saved to {out_path}\n")


# ─── CLI ──────────────────────────────────────────────────────────────────────

def _build_config(file_path: str, extra: dict | None = None) -> dict:
    cfg = {"file_path": file_path}
    if extra:
        cfg.update(extra)
    return cfg


def main():
    parser = argparse.ArgumentParser(description="Full RKNN NPU validation suite")
    parser.add_argument("--rknn", required=True, help="Path to .rknn model")
    parser.add_argument("--pt", default=None, help="Path to source .pt model (for correctness check)")
    parser.add_argument("--onnx", default=None, help="Path to intermediate .onnx (for quant analysis)")
    parser.add_argument("--images", nargs="*", default=None, help="Explicit test images for correctness check")
    parser.add_argument("--val-dir", default=None,
                         help="Dir with images/ + labels/ (YOLO txt format) for accuracy check")
    parser.add_argument("--dataset-txt", default=None, help="RKNN calibration dataset.txt")
    parser.add_argument("--sample-image", default=None, help="Single image for accuracy_analysis()")
    parser.add_argument("--input-size", type=int, nargs=2, default=[640, 640])
    parser.add_argument("--duration", type=float, default=5.0, help="Speed-test duration (s) per core mask")
    parser.add_argument("--stability-duration", type=float, default=0.0,
                         help="Stability-test duration (s), 0 = skip")
    parser.add_argument("--output", default=str(_PROJECT_ROOT / "Outputs" / "rknn_test_report.json"))
    parser.add_argument("--skip", nargs="*", default=[],
                         choices=["correctness", "accuracy", "quant", "speed", "stability", "edge"],
                         help="Sections to skip")
    args = parser.parse_args()

    print(_c("\n  iSpy RKNN NPU Validation Suite", C.BOLD))
    print(_c(f"  Model: {args.rknn}\n", C.DIM))

    rknn_config = _build_config(args.rknn)
    results = SuiteResults()

    # Correctness
    if "correctness" not in args.skip:
        images = [Path(p) for p in args.images] if args.images else []
        if args.val_dir and not images:
            vd = Path(args.val_dir) / "images"
            if vd.exists():
                images = sorted(vd.glob("*.jpg")) + sorted(vd.glob("*.png"))
                images = images[:20]  # cap for runtime
        if args.pt and images:
            pt_config = _build_config(args.pt)
            run_correctness(pt_config, rknn_config, images, results)
        else:
            section("1. CORRECTNESS  -  .rknn vs .pt box agreement")
            skip("requires both --pt and (--images or --val-dir)")
            results.correctness["status"] = "SKIP"
    else:
        results.correctness["status"] = "SKIP"

    # Accuracy
    if "accuracy" not in args.skip:
        val_dir = Path(args.val_dir) if args.val_dir else None
        run_accuracy(rknn_config, val_dir, results)
    else:
        results.accuracy["status"] = "SKIP"

    # Quant analysis
    if "quant" not in args.skip:
        onnx_path = Path(args.onnx) if args.onnx else None
        dataset_txt = Path(args.dataset_txt) if args.dataset_txt else None
        sample_image = Path(args.sample_image) if args.sample_image else None
        if sample_image is None and args.val_dir:
            vd = Path(args.val_dir) / "images"
            found = sorted(vd.glob("*.jpg")) + sorted(vd.glob("*.png")) if vd.exists() else []
            sample_image = found[0] if found else None
        run_quant_analysis(
            onnx_path, tuple(args.input_size), dataset_txt, sample_image,
            _PROJECT_ROOT / "Outputs", results,
        )
    else:
        results.quant_analysis["status"] = "SKIP"

    # Speed
    if "speed" not in args.skip:
        run_speed(rknn_config, args.duration, results)
    else:
        results.speed["status"] = "SKIP"

    # Stability
    if "stability" not in args.skip and args.stability_duration > 0:
        run_stability(rknn_config, args.stability_duration, results)
    else:
        section("5. STABILITY  -  long-run FPS drift + thermal")
        skip("--stability-duration not set (>0 required) or --skip stability passed")
        results.stability["status"] = "SKIP"

    # Edge cases
    if "edge" not in args.skip:
        run_edge_cases(rknn_config, tuple(args.input_size), results)
    else:
        results.edge_cases["status"] = "SKIP"

    print_summary(results)
    save_json_report(results, Path(args.output))

    return 0 if results.overall_verdict in ("READY", "PARTIALLY VALIDATED") else 1


if __name__ == "__main__":
    sys.exit(main())